### PR TITLE
Add hidden config to stop throwing errors for passengers

### LINKED ISSUE #3443: Option to disable passenger checks altogether
### Feature request

**Feature description**

I'd like a feature where there is some kind of an option (config, system property (`-D`), env var) to disable the checks for whether a player is a vehicle altogether.

**How the feature is useful**

I've got a fork of Paper for a server where it allows us (in certain cases) to teleport even with passengers and inside vehicles. It'd be nice to be able to use this with all plugins we use, including EssentialsX, as it does this logic in the `teleport` method of `CraftPlayer`. In EssentialsX, this is however never called, leading us to either have to fork it (which would not be ideal), or learn to live with it (less ideal).

I was asked to open an issue as a reminder for Josh to do this when he becomes available.

Thank you!

### PR DESCRIPTION
**Pull request by JRoy**
Closes #3443

cc @Proximyst

### CODE REVIEW

**Review by Proximyst — APPROVED** [review]
Exactly as requested, thank you!

**Comment by pop4959** [comment]
Is there even a reason why we need the passengerTeleportFail in the first place? Just so that the command doesn't silently fail? I'd be interested to know what the behavior is (since we could potentially just remove these checks altogether).

**Review by mdcfe — APPROVED** [review]

**Comment by JRoy** [comment]
The teleport will silently fail as the server will refuse to teleport people with passengers. This error is in place to help users understand why the command didn't work if someone disabled the option (not this one) in the config.

**Comment by pop4959** [comment]
Ah I see. I'm just asking because maybe we want to instead consider checking if the teleport was successful, and if not, *then* check if they were mounted, and if so, print the error. According to the documentation for [Entity::teleport(Location)](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html#teleport-org.bukkit.Location-), in theory this should be doable, and we can avoid adding potentially unnecessary config bloat.

**Comment by pop4959** [comment]
Actually upon re-reading the API, it seems like entities are dismounted anyways. So again, why do we have this extra code? It seems like this is the behavior as far back as 1.8.8 (which is the oldest that Essentials supports).

**Comment by JRoy** [comment]
Async teleportation has made that more difficult and would probably require method refactoring to do such a thing and the teleport method can fail for a number of different reasons other than passengers. Even then, I don't think the teleport actually "fails" but the server just refuses to teleport.

> Actually upon re-reading the API, it seems like entities are dismounted anyways. So again, why do we have this extra code? It seems like this is the behavior as far back as 1.8.8 (which is the oldest that Essentials supports).

This is only if the player you're trying to teleport *is* the passenger, not if the player you're trying to teleport *has* passengers.

**Comment by pop4959** [comment]
Fair enough, I just thought it was worth discussing. If it's not easily doable right now, we can leave this off to a later date. A small config option for this is really no huge hassle.

**Review by pop4959 — APPROVED** [review]

**Pull request merged**
