### PR TITLE
Only use convert spawners tagged by the give command

### LINKED ISSUE #3811: Essentials seems to reset the spawners' values and only keeps them from pigs
### Information

**Full output of `/ess version`:**
```
> ess version
[22:43:20 INFO]: CONSOLE issued server command: /ess version
[22:43:20 INFO]: Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-318 (MC: 1.16.4)
[22:43:20 INFO]: EssentialsX version: 2.18.2.0
[22:43:20 INFO]: LuckPerms version: 5.2.49
[22:43:20 INFO]: Vault version: 1.7.3-b131
[22:43:20 INFO]: EssentialsXChat version: 2.18.2.0
```

**Server startup log:**
https://gist.github.com/marcopaggioro/e9a85f503dfabb36154b7e3336f15a7c

**EssentialsX config:**
https://gist.github.com/marcopaggioro/321074e5645b13c0b0522056740220e3

### Details

**Description:**  
When I try to place a custom spawner created from /minecraft:give command It not works. The placed spawner is a pig spawner, It lose all data.

**Steps to reproduce:**  
1. Place command block
2. Execute this command
```
minecraft:give PLAYER_NAME_HERE spawner{display:{Name:'{"text":"Spawner L1","color":"gold","bold":true,"italic":false}'},BlockEntityTag:{SpawnData:{id:"minecraft:zombie",DeathLootTable:"aresondungeons:d1/entities/zombie_p1",HandItems:[{id:"minecraft:stone_sword",Count:1b,tag:{Enchantments:[{id:"minecraft:sharpness",lvl:2s}]}},{}],ArmorItems:[{},{id:"minecraft:leather_leggings",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:2s}]}},{},{id:"minecraft:leather_helmet",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:2s}]}}]},SpawnPotentials:[{Weight:1,Entity:{id:"minecraft:zombie",DeathLootTable:"aresondungeons:d1/entities/zombie_p1",HandItems:[{id:"minecraft:stone_sword",Count:1b,tag:{Enchantments:[{id:"minecraft:sharpness",lvl:2s}]}},{}],ArmorItems:[{},{id:"minecraft:leather_leggings",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:2s}]}},{},{id:"minecraft:leather_helmet",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:2s}]}}]}},{Weight:1,Entity:{id:"minecraft:zombie",DeathLootTable:"aresondungeons:d1/entities/zombie_p1",HandItems:[{id:"minecraft:stone_sword",Count:1b,tag:{Enchantments:[{id:"minecraft:sharpness",lvl:2s}]}},{}],ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:2s}]}},{},{id:"minecraft:leather_chestplate",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:2s}]}},{}]}},{Weight:1,Entity:{id:"minecraft:skeleton",DeathLootTable:"aresondungeons:d1/entities/skeleton_p1",HandItems:[{id:"minecraft:bow",Count:1b,tag:{Enchantments:[{id:"minecraft:power",lvl:2s}]}},{}],ArmorItems:[{},{id:"minecraft:leather_leggings",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:2s}]}},{},{id:"minecraft:leather_helmet",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:2s}]}}]}},{Weight:1,Entity:{id:"minecraft:skeleton",DeathLootTable:"aresondungeons:d1/entities/skeleton_p1",HandItems:[{id:"minecraft:bow",Count:1b,tag:{Enchantments:[{id:"minecraft:power",lvl:2s}]}},{}],ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:2s}]}},{},{id:"minecraft:leather_chestplate",Count:1b,tag:{Enchantments:[{id:"minecraft:protection",lvl:2s}]}},{}]}}]}} 64
```
3. Try to place the given spawner

**Expected behavior:**  
As in a server without essentials I expect a skeleton spawner.

**Console stack trace:**  
When i place the spawner
```
[22:50:02 WARN]: Skipping BlockEntity with id
```

### PR DESCRIPTION
**Pull request by JRoy**
Marks all spawners made by EssentialsX with a special PDC tag that denotes if we should run "spawnerconvert" operations on it.

Tested on 1.8.8 & 1.16.5

Fixes #3811

### CODE REVIEW

**Review by pop4959 — DISMISSED** [review]
I've tested this code and (quite shockingly) this breaks the spawner convert feature. There's definitely a better way to go about fixing this.

I can explain this feature briefly since you're unfamiliar with it. In essence, it converts spawners being placed to their intended types when using Essentials commands to create them. It's probably easiest if I just give some example commands to reproduce the expected behavior.

If you run `/i zombiespawner` you get a "zombie Spawner" (not sure why the z is lower case, that's probably a separate bug as in older versions it was upper). Upon placement, the spawner is "converted" to a zombie spawner. With this code nuked, that no longer works properly and you get left with a pig spawner.

This worked properly in older versions of Minecraft, but from brief testing this clearly doesn't work well with vanilla spawners. If you use the vanilla equivalent command, `/minecraft:give @p minecraft:spawner{BlockEntityTag:{SpawnData:{id:"minecraft:zombie"},SpawnPotentials:[{Entity:{id:"minecraft:zombie"},Weight:1}]}} 64`, and place the spawner, you get a pig spawner because Essentials overreaches and tries to convert this instead of leaving it alone. PS: for the above command you will also need to be OP and in creative mode due to [MC-105216](https://bugs.mojang.com/browse/MC-105216).

Clearly this feature still needs an overhaul because it's not OK for it to do that. Ideally spawners made in Essentials should be the only ones touched by spawner conversion, and vanilla ones are left alone. This could probably be done by attaching a custom tag to the item stack on creation and checking for that before setting the spawned type (and of course, ignoring any that do not have the tag).

**Comment by JRoy** [comment]
@pop4959 am now using an enchantment as a way to differentiate between EssX spawners and normal ones. This is the best solution due to PersistentDataContainer being a 1.14 thing

**Comment by pop4959** [comment]
To be honest that's a solution I'd not have thought of, but I still have some worries about using enchantments here, given that they're not really intended for storing data. On top of that, it seems likely to me that there can easily be some unnecessary plugin conflicts created by this, since quite a few plugins touch enchantments.

The best solution in my opinion would be to leave the existing legacy handler as-is, and use PDC on the versions that support it. Of course that means that older versions would not receive the improvement, but these versions are not a priority and should not force us to use workarounds that create further maintenance burden.

**Comment by JRoy** [comment]
> On top of that, it seems likely to me that there can easily be some unnecessary plugin conflicts created by this, since quite a few plugins touch enchantments.

The only possible plugin conflicts would be extremely rare and only in 1.8-1.12 as starting with 1.13 it uses a plugin namespaced key.

> The best solution in my opinion would be to leave the existing legacy handler as-is, and use PDC on the versions that support it. Of course that means that older versions would not receive the improvement, but these versions are not a priority and should not force us to use workarounds that create further maintenance burden.

I apply the same logic to the reason in favor of this fix

**Comment by pop4959** [comment]
Just was concerned because I'm not familiar with any other plugins handling metadata that way. If we're absolutely sure this won't cause problems or have any other side effects, then it might be OK. I'll try to take a closer look later this week.

**Comment by JRoy** [comment]
> Just was concerned because I'm not familiar with any other plugins handling metadata that way. If we're absolutely sure this won't cause problems or have any other side effects, then it might be OK. I'll try to take a closer look later this week.

Yeah no problem. Basically the only way this can conflict is with the id based enchantment registration which only occurs on 1.8 thru 1.12. I picked an offset which is good enough and no other plugins should occupy considering that barely any plugins register enchantments in the first place, I'd say we're fine. As for side effects there are none I can find.

**Comment by JRoy** [comment]
Marking as draft as this pends providers from #4143

**Comment by mdcfe** [comment]
#4143 has now been merged - will review when marked ready

**Review by mdcfe — APPROVED** [review]

**Pull request merged**
