### PR TITLE
Add book page serialization

### LINKED ISSUE #31: Createkit command does not save book metadata
Hello,

I've tested your /createkit command and I've been wanting this as a plugin for ages and now it's in a fork of Essentials, that's a plus. Good work!

Works on almost everything except for books and I'm not sure if this is something you can fix.

After creating a book with same text and adding it as kit. It saves the title and author just fine. However the books says.
- Invalid book tag *

I know there are plugins that can read books and convert them to text, so I'm pretty sure this could be possible using the books feature in Essentials.

### PR DESCRIPTION
**Pull request by JRoy**
Closes #31

### CODE REVIEW

**Comment by pop4959** [comment]
Not all too familiar with this; how is it intended to be used?

**Comment by JRoy** [comment]
> Not all too familiar with this; how is it intended to be used?

createkit uses AbstractItemDb to serialize data, MetaItemStack parses that data.

**Comment by pop4959** [comment]
> > Not all too familiar with this; how is it intended to be used?
> 
> createkit uses AbstractItemDb to serialize data, MetaItemStack parses that data.

I understand that bit, what I meant was how this actually works. From the code it looks like it's adding a new item meta syntax for `page<#>:<content>` and dumps everything in there. It might be better if we used the method already used by `book` to save and load data.

**Comment by JRoy** [comment]
> > > Not all too familiar with this; how is it intended to be used?
> > 
> > 
> > createkit uses AbstractItemDb to serialize data, MetaItemStack parses that data.
> 
> I understand that bit, what I meant was how this actually works. From the code it looks like it's adding a new item meta syntax for `page<#>:<content>` and dumps everything in there. It might be better if we used the method already used by `book` to save and load data.

from what I understand, that was made for making the content of a book match that of a text file on disk, `book.txt`. If I used that, it would break backwards compatibility :/

**Comment by pop4959** [comment]
Ah yeah good point, we'd also need to write into that too and I don't think anything does that currently (also ew, txt). I feel like there's probably still a better way than to literally dump the text wholesale into YML and generate a bunch of messy keys. If we're going into that direction then #3248 is a better solution.

**Review by mdcfe — DISMISSED** [review]

**Comment by mdcfe** [comment]
Do we want to consider serializing book and quills? If they use `BookMeta` too, I see no reason why we couldn't allow for this.

It also currently preserves newlines:
image

**Review by mdcfe — APPROVED** [review]

**Pull request merged**
