### PR TITLE
Implement per player locale (Implements #2029)

### LINKED ISSUE #2029: Essentials localization based on player client language
My server will have two groups of players: Russian speaking and English speaking. I won't create new servers. Instead I want to show Essentials messages on language that select in player's client settings.

API which will help realise that:

1st. https://www.spigotmc.org/resources/api-languages.22305/
(also has ability to select certain language by command)

2nd. https://www.spigotmc.org/resources/1-7-x-1-12-language-utils.8859/

### PR DESCRIPTION
**Pull request by Phoenix616**
This implements a per-player locale system like requested in #2029 which uses the client's language setting by default and adds a command to allow players to change their own locale on the server without changing the client language. The original `locale` config setting now acts as the default language when no locale is available for the player's locale or, if `change-locale` is disabled in the config behaves exactly like before using the same locale for all players (should be default with an old config).

This change goes along with moving all translations that get send from the static I18n.tl method to one provided by the User/CommandSource to get translations depending on the selected locale and also a convenience method sendTl to directly send translations.

Edit: Forgot to mention it: This also includes a provider for getting the client's locale on older versions that didn't include the locale API to keep this functionality backwards compatible.

Closes #2029

### CODE REVIEW

**Comment by mdcfe** [comment]
Thanks for the PR!

However, due to incoming changes to how messaging works (#2391) in 2.18.x and our current schedule, this likely will not be merged into 2.x until after 2.17.0.

**Comment by Phoenix616** [comment]
Is there any place where the schedule is laid out? Or is that just an internal thing?

Also this might be a good base for some of the ideas laid out regarding messaging changes, especially for the PlaceholderAPI support as it switches the messaging system from a global translator to a per-user translator which could the handle the PlaceholderAPI integration.

**Comment by mdcfe** [comment]
You can see loosely what the plans are for versions at the [milestones](https://github.com/EssentialsX/Essentials/milestones?direction=asc&sort=due_date).

This PR could definitely serve as a base to build on for any changes in #2391.

**Comment by JRoy** [comment]
Closed in favor of #4717

**Pull request closed without merging**
