### PR TITLE
Speedimprovement

### PR DESCRIPTION
**Pull request by Samistine**

### CODE REVIEW

**Comment by drtshock** [comment]
Tabs :(

**Comment by Samistine** [comment]
OMG NETBEANS IS GOING TO BE THE DEATH OF ME

**Comment by drtshock** [comment]
Can you explain and justify your PR please.

**Comment by Samistine** [comment]
The same permission is being checked twice

**Comment by vemacs** [comment]
Permissions checks are very, very fast...

They are done via a map lookup, not by querying plugins.

**Pull request closed without merging**
