### PR TITLE
Fix invalid configuration section for world aliases

### LINKED ISSUE #3999: Chat world aliases don't work
**Type of bug**

Other unexpected behaviour

**`/ess version` output**

19:49:02 [INFO] Server version: 1.16.5-R0.1-SNAPSHOT 3013-Spigot-73fb609-0cd8f19 (MC: 1.16.5)
19:49:02 [INFO] EssentialsX version: 2.19.0-dev+80-81571fc
19:49:02 [INFO] LuckPerms version: 5.2.76
19:49:02 [INFO] Vault version: 1.7.3-b131
19:49:02 [INFO] EssentialsXChat version: 2.19.0-dev+80-81571fc
19:49:02 [INFO] EssentialsXGeoIP version: 2.19.0-dev+80-81571fc
19:49:02 [INFO] EssentialsXSpawn version: 2.19.0-dev+80-81571fc

**Server startup log**

https://paste.gg/p/anonymous/dabc90f3cd264e2c8798351afe56e1a2

**EssentialsX config files**

https://paste.gg/p/anonymous/6b259bdab2514901ba047070d484dd2c

**Error log (if applicable)**

_No response_

**Bug description**

The new chat world aliases feature doesn't work. The chat is showing the regular world name instead of the alias defined in the config.

I'll cut to the chase - If you look at https://github.com/EssentialsX/Essentials/blob/81571fc014b973f7edaa5395d127b8362855159d/Essentials/src/main/java/com/earth2me/essentials/Settings.java#L553 you'll see it reads all the top-level keys from the config file (yes, the entire config file!) instead of reading chat.world-aliases. So it never gets the defined aliases.

**Steps to reproduce**

Define aliases, use WORLDNAME in the chat format, type a chat message.

**Expected behaviour**

The alias should be used in place of WORLDNAME.

**Actual behaviour**

The regular world name is used instead of the alias.

If you look at https://github.com/EssentialsX/Essentials/blob/81571fc014b973f7edaa5395d127b8362855159d/Essentials/src/main/java/com/earth2me/essentials/Settings.java#L553 you'll see it reads all the top-level keys from the config file (yes, the entire config file) instead of reading chat.world-aliases. So it never gets the defined aliases.

### PR DESCRIPTION
**Pull request by JRoy**
must have changed something between my testing build and the build I committed as it even worked fine on the jar i have locally. oops.

Fixes #3999

### CODE REVIEW

**Comment by Bobcat00** [comment]
Did you even test it?  Just use my PR.

**Comment by JRoy** [comment]
> Did you even test it? Just use my PR.

It does work, and I have tested it, just like I do all my PRs.

**Comment by Bobcat00** [comment]
Really? Looks like the original wasn't tested.

This is unfair.  I do all the work for this fix, do all the testing, fill out the template with multiple screenshots and everything (which you didn't do), then you go and take the credit while I'm busy dealing with all the project's red tape.

**Comment by JRoy** [comment]
> Really? Looks like the original wasn't tested.

Did you read the PR description? And last I checked, this is PR #4000 while yours is #4001?

**Comment by Bobcat00** [comment]
Yeah, because I took the time to fill out all the required documentation, including screenshots and Java version information, just like you require.  But you didn't do any of that.

_"Failure to fill out this template properly may result in your PR being delayed or ignored without warning."_

**Comment by Draycia** [comment]
> _"**may result** in your PR being delayed or ignored without warning."_

expressing possibility.
"that may be true"

**Comment by Bobcat00** [comment]
So next time I SHOULDN'T fill out the template?  This is the second time I attempted to make a contribution, and the second time you guys pulled the rug out from under me.  I'm out of here.

**Comment by JRoy** [comment]
> Yeah, because I took the time to fill out all the required documentation

Issues aren't required to submit a PR, I don't understand why you didn't just submit a PR for this when you clearly took the time to see what the problem was. 

> including screenshots and Java version information, just like you require. But you didn't do any of that.

The template is made for maintainers to understand proposed changes from people who aren't necessarily familiar with the EssX codebase. I don't need to fill out the template because I can understand my own changes. Any questions other maintainers have (which is rare) can be handled in private or throughout the normal code review process.

> So next time I SHOULDN'T fill out the template? 

No, you should fill out the template, I appreciate you taking the time to fill it out.

> This is the second time I attempted to make a contribution, and the second time you guys pulled the rug out from under me

Nobody has pulled the rug out in front of you. In this case, you submitted an issue instead of a PR at first, and I fixed it. The other times you committed faulty code and needlessly verbose comment to the config.

**Comment by Bobcat00** [comment]
"Fill out the template in full. This includes providing screenshots and a link to the original bug report. If there isn't an existing bug report, **we recommend opening a new detailed bug report BEFORE opening your PR to fix it, else your PR may be delayed or rejected without warning.**"

I'm done wasting my time with you guys.

**Review by pop4959 — APPROVED** [review]

**Pull request merged**
