### PR TITLE
Parse /pay modifiers more strictly

### LINKED ISSUE #5495: Toggle /pay modifiers in config
### Feature description

I am suggesting adding a config line to enable/disable the `/pay` modifiers for 1 thousand, 1 million, 1 billion, and 1 trillion.
I already have this tested and ready to pr, but I read that this feature had to be requested first.

### How the feature is useful

This would, in my case, prevent players from scamming each other by convincing them that you can pay another currency to a player by adding the currency name afterwards.
For example. Our second currency is gems, so when a player runs `/pay 1gem` then they would pay the player 1,000,000 because the pay command checks for the last character and compares it with the available modifiers.
My PR would also fix this by checking for the first char after the number instead of the last.

### PR DESCRIPTION
**Pull request by AjMaacc**
### Information

This PR fixes #5495. 

### Details

**Proposed fix:**    

This PR fixes half of the issue presented. 
It is also more simplistic and a much better approach compared to my previous PR

Instead of checking for the last character in the string -> `Character.toLowerCase(ogStr.charAt(ogStr.length() - 1))`, 
check for the exact modified being use via removing the amount from the string -> `ogStr.replace(sanitizedString, "")`
If the result of  `ogStr.replace(sanitizedString, "")` is not *exactly* one of the modifiers, throw an exception (unless an empty string is returned due to a modifier not being present).

**Environments tested:**    

OS: Linux 5.15.0-79-generic

Java version:  java 19.0.1 

- [x] Most recent Paper version (1.20.4, git-Paper-408)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**

### CODE REVIEW

**Comment by AjMaacc** [comment]
Yea this is never getting merged

**Comment by mbax** [comment]
A two month wait on a large project with busy maintainers? That's nothing to complain about.

**Comment by AjMaacc** [comment]
> A two month wait on a large project with busy maintainers? That's nothing to complain about.

🤷‍♂️

**Comment by pop4959** [comment]
Is there any specific reason you decided to close this? It looks like this fixes a valid issue.

**Comment by AjMaacc** [comment]
> Is there any specific reason you decided to close this? It looks like this fixes a valid issue.

Well, the longevity of the pr being open. If my pr was still being considered, was overlooked, or any other reason, then I can re-open it.

**Comment by pop4959** [comment]
Sorry for the delays, most of us have been very busy recently and the bulk of our focus has been on the adventure update (and all of the fallout / bugs following from that, trying to get us into a better place to lean towards a release).

We appreciate your dedication to keeping this up to date, although for the most part unless there are conflicts it should merge cleanly. If there are we'll generally let you know and/or do it ourselves before merging, so please don't worry too much about it especially until we find time to properly review this. Thanks for remaining patient.

**Review by JRoy — APPROVED** [review]

**Comment by JRoy** [comment]
Thanks for the contribution :)

**Pull request merged**
