### PR TITLE
Fix AbstractItemDb#getMatching improper block filtering

### LINKED ISSUE #3690: worth/sell blocks does entire inventory instead of just blocks
https://github.com/EssentialsX/Essentials/blob/5d61a43fe181f0f8fb43d1e445fd3d8b5ae45a54/Essentials/src/com/earth2me/essentials/items/AbstractItemDb.java#L152
It's an exact copy of inventory

### PR DESCRIPTION
**Pull request by goosewoman**
fixes https://github.com/EssentialsX/Essentials/issues/3690

### CODE REVIEW

**Comment by montlikadani** [comment]
I would rather make a list into config and adding material names/or at least keywords, which is more reliable than exluding every of materials from the list to be removed from the inventory.
Example
```yml
excluded-material-keys:
- blocks # This means that it collects all of known blocks
- diamond_sword # Only excludes this item
```

EDIT: For keywords like `blocks`, shouldn't collect into list, just check if the player inventory does contain any of blocks and ignoring that.

**Comment by goosewoman** [comment]
> 
> 
> I would rather make a list into config and adding material names/or at least keywords, which is more reliable than exluding every of materials from the list to be removed from the inventory.
> Example
> 
> ```yaml
> excluded-material-keys:
> - blocks # This means that it collects all of known blocks
> - diamond_sword # Only excludes this item
> ```

That sounds more like a different issue. This PR is purely for fixing an existing feature that doesn't work right.

**Review by Octol1ttle — DISMISSED** [review]

**Comment by JRoy** [comment]
Hello, can you please rebase this pull request so we can merge it! Thanks!

**Review by JRoy — APPROVED** [review]

**Review by JRoy — APPROVED** [review]
Appears as if this was overlooked during the rewriting of the ItemDB code, getMatching should return only placeable blocks and not just filter out air.

**Pull request merged**
