### PR TITLE
Allow color-only nickname changes.

### LINKED ISSUE #125: /Nick suggestions
On my server, my donators can use /nick freely. I had these amazing ideas:
1. Either add a permission node to only allow people using /nick to colour their name, such as "/nick &cHunter&6G&ePlays" (even though that isn't my IGN you get the point)
2. Number 2 wasn't a good idea

### PR DESCRIPTION
**Pull request by minecrafter**
Resolves #125.

The permission is `essentials.nick.changecolors` (or `essentials.nick.changecolours`). I can't test as EssentialsX won't compile.

### CODE REVIEW

**Comment by drtshock** [comment]
It already does this when it calls this method in the /nick command class
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/utils/FormatUtil.java#L66

See http://wiki.ess3.net/wiki/Command_Reference/Perm
`General    nick    essentials.nick Allow access to the /nick command.`
`General    nick    essentials.nick.color   This allows you to color your nickname using color codes.`
`General    nick    essentials.nick.format  This allows you to format your nickname using format codes.`
`General    nick    essentials.nick.magic   This allows you to use the matrix/magic color in your nickname.`
`General    nick    essentials.nick.others  Gives you permission to give other players a nick name`

**Comment by minecrafter** [comment]
That covers being able to use colors in nicknames. This allows changing your nickname only if the changes are color codes being added or removed (the nickname itself is the player's name). Of course, this has zero effect without `essentials.nick.color` and friends.

**Comment by Terrobility** [comment]
Wouldn't it be more efficient to give a perm for changing name, instead of a completely separate perm that lets you use /nick for changing formatting?
e.g. If you wanted to change displayname you would need essentials.nick and essentials.nick.changename
But if you only wanted to use it to colour your name, you would require essentials.nick and essentials.nick.color

**Comment by minecrafter** [comment]
@HunterGPlays: This is consistent with Essentials's permission scheme.

**Comment by drtshock** [comment]
Merged, thank you :) https://github.com/drtshock/Essentials/compare/2d3691107dd5...a6691631963f

**Pull request closed without merging**
