### PR TITLE
Remove outdated permission plugin handlers, minor test fixes

### PR DESCRIPTION
**Pull request by DoNotSpamPls**
All these 4 plugins are unmaintained anymore, so there is no need for them to exist in the code anymore (just like with the payment providers). Also in this PR are some test fixes, 2 tests were upgraded from JUnit3 to JUnit4.

### CODE REVIEW

**Comment by mdcfe** [comment]
It's technically possible that someone is using EssentialsX AntiBuild with the `build` property in PEX, but this PR will break that.

**Comment by DoNotSpamPls** [comment]
Yeah, I suppose it's a bit too early to remove PEX. Will resolve.

**Review by mdcfe — DISMISSED** [review]

**Comment by DoNotSpamPls** [comment]
Update: This PR now includes async teleportation, which should resolve #2326 and #2193

**Comment by mdcfe** [comment]
I'd prefer if the PaperLib changes were cherry-picked into a separate PR, since they are significant changes themselves and require more review than the other misc cleanup changes.

**Review by mdcfe — APPROVED** [review]

**Pull request merged**
