### PR TITLE
Implement 1.13 items support (incomplete)

### LINKED ISSUE #2209: /itemdb on birch logs registers as oak logs
**EssentialsX:** 2.15.0.52 (AntiBuild, XChat, XGeoIP, XProtect & XSPawn)
**Paper Spigot:** 1.13.1 (Build 355)
**Waterfall:** b227

**/itemdb** OR **/essentials:itemdb** with _Birch log_ held in hand returns **oak log**
image
**/itemdb birchlogs** returns the correct entry of **LOG - 17:2 and right short names.**
Item identifier above the block when holding is correct:
image

**These links are set to never expire.** 
The log attached shows without TreeAssist being loaded in case it conflicted.  Same results both ways.
items.csv: https://pastebin.com/nBRkR8FR
config.yml: https://pastebin.com/1myA2s7m
Plugins:  https://pastebin.com/hUDAfwFq
Startup Log: https://pastebin.com/t9BUkNqi

Thanks - Steve

### PR DESCRIPTION
**Pull request by mdcfe**
Reopening this so we can track progress on 1.13 items support.

Current issues:
- [ ] Implement limited backwards-compatibility through `items.json`
- [ ] Ensure kits work properly
- [ ] Ensure blacklist works properly
- [x] Make permissions nodes rely on primary names not item IDs
- [x] Remove item ID support from Worth
- [x] Fix `/itemdb` (closes #2209)
- [ ] Adapt all non-core modules to use primary names instead of item IDs

Note that this no longer uses providers, and will not use `items.csv`.

### CODE REVIEW

**Comment by mibby** [comment]
@md678685 Compiled this PR as of commit https://github.com/EssentialsX/Essentials/pull/2204/commits/1218c3e22646235c220e4c80f44bd41e408932ba for testing. Noticed I can't spawn in anything with /i or /give. It always outputs that legacy IDs aren't supported on this version despite using the material name.

**Comment by mdcfe** [comment]
@mibby Thanks for spotting this - I'm about to push a fix.

**Comment by mibby** [comment]
Another issue I noticed is the player tag variable is not working in the give command. i.e. ```/give mibby PLAYER_HEAD 1 player:md678685```

**Comment by mibby** [comment]
@md678685 Specifically what happens is it just gives players a normal yellow head. Not textured with the skin.

**Comment by mibby** [comment]
Leather armor property spawning with give seems broken too. i.e. 
```
/give {player} 298 1 unbreaking:10 respiration:3 aquaaffinity:1 color:255|0|0 name:&r&b&k||&r_&4&o&lMystical_Red_Cap&r&b_&k|| lore:Said_to_contain_magical_powers.

**Comment by mdcfe** [comment]
@mibby I've pushed 1206178eca98cba05ae6c96efc891bd6482885ed which updates MetaItemStack and should fix specifying metadata for player heads, leather armour, fireworks, potions, banners and shields - could you update to the latest [experimental build](https://ci.ender.zone/job/EssentialsX-Experimental/) and see if you're still running into issues with these?

**Pull request merged**
