### PR TITLE
Add worldborder check in jump command

### LINKED ISSUE #2512: /jump goes through vanilla world border
This is a bug report/feature request.

The /jump command can currently teleport you right through the vanilla world border. Maybe make a detection and/or togglable option for that?

Thanks.

### PR DESCRIPTION
**Pull request by JRoy**
Closes #2512

### CODE REVIEW

**Comment by pop4959** [comment]
Code looks fine to me, but is this still necessary now that the world border is checked in teleportation safety?

**Comment by JRoy** [comment]
> Code looks fine to me, but is this still necessary now that the world border is checked in teleportation safety?

That would be overreaching as there could still be uses to teleport users out of the worldborder.

**Comment by pop4959** [comment]
> > Code looks fine to me, but is this still necessary now that the world border is checked in teleportation safety?
> 
> That would be overreaching as there could still be uses to teleport users out of the worldborder.

Well, of course normal rules apply, such as being in creative, god mode, etc. That's probably enough for the very few cases someone needs to go past the world border, I imagine. Probably best for a separate discussion if you disagree.

I was mainly asking because I wasn't sure if this PR was redundant, since there wouldn't be much of a purpose for this if it's already being checked on most player teleports.

**Comment by JRoy** [comment]
> Well, of course normal rules apply, such as being in creative, god mode, etc. That's probably enough for the very few cases someone needs to go past the world border, I imagine. Probably best for a separate discussion if you disagree.
> 
> I was mainly asking because I wasn't sure if this PR was redundant, since there wouldn't be much of a purpose for this if it's already being checked on most player teleports.

There isn't really any other way to teleport out the border other than this command so I'd rather no place it into the safety code for one use and have is possibly break people using our Teleport APIs.

**Comment by pop4959** [comment]
> > Well, of course normal rules apply, such as being in creative, god mode, etc. That's probably enough for the very few cases someone needs to go past the world border, I imagine. Probably best for a separate discussion if you disagree.
> > I was mainly asking because I wasn't sure if this PR was redundant, since there wouldn't be much of a purpose for this if it's already being checked on most player teleports.
> 
> There isn't really any other way to teleport out the border other than this command so I'd rather no place it into the safety code for one use and have is possibly break people using our Teleport APIs.

Is there actually any reason to actually teleport past the border though? My thought are this would almost always be an accident, as someone jumping would teleport past the border and instantly kill themselves, requiring then that an admin intervenes to retrieve their stuff. This is at least my experience with running a server.

The above reason is also why it was placed right into the safety code, because players that *will* die when teleporting past the border were not being caught and this was causing issues for example with /tppos, /tpr, and the like -- not just /jump. I would hope the teleport APIs are taking safety into account though, because otherwise irrespective of world border safety, there might be some issues.

**Comment by JRoy** [comment]
just checked the code, it already does this LUL

**Pull request closed without merging**
