### PR TITLE
Fix conversion issues between Legacy and MiniMessage

### LINKED ISSUE #5652: Prefix formatting bleeds into display name
### Type of bug

Performance issue or memory leak

### `/ess dump all` output

https://essentialsx.net/dump.html?id=2a7e713c0a5c48d1b5ca90e0a49a40f6

### Error log (if applicable)

_No response_

### Bug description

The bold from our prefixes is carrying over into our usernames when we /afk or un-/afk, and switching game modes, and in the /list of players online, even though our prefixes are specifically defined to reset the bold at the end of the prefix:
bold

### Steps to reproduce

1. Update to the latest dev build of EssentialsX
2. /afk or /gm or /list

### Expected behaviour

Prefix is bolded and username is not.

### Actual behaviour

Both prefix and username are in bold.

### PR DESCRIPTION
**Pull request by pop4959**
Fixes #5652 (and probably numerous other issues...)

image

### CODE REVIEW

**Comment by Bobcat00** [comment]
Good news and bad news: It fixes the obfuscated formatting in the player's prefix, but broke the rest of the /whois output (God mode and below).

Testing with Paper version git-Paper-435 (MC: 1.20.4)

Before PR (using latest dev build Essentials v2.21.0-dev+56-1929d41):

image

After PR (using Essentials v2.21.0-dev+57-a81725b):

image

**Comment by mdcfe** [comment]
Fixing specific incorrect formatting in `/whois` is probably more sensible to have as a separate PR after this is merged.

**Review by mdcfe — DISMISSED** [review]

**Comment by pop4959** [comment]
fixed the parsed placeholder bug (this was caused by going through the ser/deser process which escapes the output - this is already injection proof so we just need to make sure not to do this for parsed placeholders

new before/after:
566c81ef-6658-40ae-bb65-569b5d3d09f1
a3627ddd-bf61-47ac-9530-142c8edce0cb

**Comment by Bobcat00** [comment]
This looks OK to me. Tested with Paper version git-Paper-435 (MC: 1.20.4) and Essentials v2.21.0-dev+62-5216246. Tested commands /list, /whois, /seen, /msg, and /me.

**Review by JRoy — APPROVED** [review]

**Pull request merged**
