### PR TITLE
Update README regarding Minecraft version support

### PR DESCRIPTION
**Pull request by mdcfe**
#988

### CODE REVIEW

**Comment by Kakifrucht** [comment]
Side question, are all backwards dependencies removed on the latest builds? Can you compile it with only the latest 1.11 .jar or do you still need to compile the old ones aswell?

**Comment by mdcfe** [comment]
You still need 1.8 and 1.8.3 due to the providers.

Edit: if EssentialsX is going to be 1.11+ only from now onwards, the legacy providers could probably be removed now.

**Comment by SupaHam** [comment]
@vemacs @drtshock Thoughts on moving forward with deleting providers?

**Comment by vemacs** [comment]
I'd rather we refactor the 1.11-dependent code to a new provider

**Comment by SupaHam** [comment]
It will be a big mess if we do, no? API is being changed completely with the migration from entity attributes to separate entities. For example `Zombie#setVillager(boolean)`, although present in API, throws unsupported exception on call.

**Comment by mdcfe** [comment]
@vemacs @SupaHam Alternatively, refactor the 1.11-deprecated 1.7-1.10 code to a new provider, which would retain backwards-compatibility while continuing to support future versions. It might be messy, but it's better than just dropping support for four major versions (one of which isn't that old) in one go.

**Comment by vemacs** [comment]
Providers work by implementing support for all the versions, so everything would need to be refactored into one. Not altogether difficult, but it's not selective.

**Comment by vemacs** [comment]
New provider isn't necessary, we can just stick everything in InventoryWorkaround because it's still a thing.

**Comment by mdcfe** [comment]
The changes to entity types are an issue, though; lots of entities which previously had attributes (Zombies/Zombie Villagers, Horses/Mules/etc.) are now separate entities. We'd need some way of accommodating for both 1.11 and pre-1.11 entities.

**Comment by mdcfe** [comment]
Not needed any more

**Pull request closed without merging**
