### PR TITLE
Fix a few GER translation issues

### PR DESCRIPTION
**Pull request by Sataniel98**
This PR resolves a few mistakes and applies a few other improvements to the German translation.
Credits @Malfrador

### CODE REVIEW

**Comment by SupaHam** [comment]
Please get back regarding @Kakifrucht's concern for us the process this PR. :)

**Comment by Sataniel98** [comment]
Sorry, it seems I missed the notification ^^

Because several translated strings sound awkward to a native speaker and some others are plain wrong.

1. "bannen" instead of "verbannen": Both is technically correct but nobody would actually say "verbannen" in a gaming environment.

2. corruptNodeInConfig, homes, ...: Anglicisms are commonly used in these cases.

3. "Teleportierung" and "Spieler Namen" are plain wrong

4. playerKicked: The message states the player who kicked the other one was kicked by the one who was actually kicked and the sentence is grammatically so incorrect that it's hardly a sentence at all.

**Comment by Kakifrucht** [comment]
Yes, I was only concerned with the translation for homes. You are right, most people call and reference them as homes themselves and I do, too. However while that counts for most, it might not for everybody. Afterall it's not difficult to add a command alias like */heime* and in that case, it would simply look like not translated and somebody else might tag along and translate it back to "Heime". I opt to keep it technically correct, as I do not believe it is us who should decide the common slang and it causes less confusion leaving it correctly. 

The rest is completely fine by me.

**Comment by Sataniel98** [comment]
If you add an alias to change it, you are also competent enough to change the translation. By default, command and translation should be constant and equal.

**Comment by SupaHam** [comment]
I need others to confirm on `homes` before I merge that change. If we can't come to a conclusion, I'll merge all but the `homes` change.

**Comment by Sataniel98** [comment]
An anglicism is, by the way, already used for "warps". It's also a question of consistency.

**Comment by Kakifrucht** [comment]
Warps is used as is in German aswell: https://de.wikipedia.org/wiki/Warp_(Galaxie)
Users who know how to add an alias can also manually change it back, thats true. That would require them to update manually whenever translation changes occur though.

**Comment by Sataniel98** [comment]
Indeed. As I already said, using anglicisms instead of German words where they are commonly used is what I'm asking for :)

**Comment by SupaHam** [comment]
Thank you very much.

**Pull request merged**
