### PR TITLE
Don't broadcast AFK messages if event is cancelled

### LINKED ISSUE #3485: Afk message is sent despite AfkStatusChangeEvent being cancelled
I noticed that after cancelling the event (with ACTIVITY cause), the you are AFK message is being sent depiste me being not AFK.

image

A good way to fix this could be by making setAfk method to return a boolean instead of void, so if it returns true it means that it could set the player, if its false, its because the event was cancelled. (https://github.com/EssentialsX/Essentials/blob/8046b8594a092ffa6657d654e4b9dc94327c7e65/Essentials/src/com/earth2me/essentials/User.java#L526 )

So for example, you could check here what it returns and depending on that to send the message: https://github.com/EssentialsX/Essentials/blob/8046b8594a092ffa6657d654e4b9dc94327c7e65/Essentials/src/com/earth2me/essentials/User.java#L686

(Im using latest released Essentials version 2.18.0.0)

Wish I was clear! Thank you!

### PR DESCRIPTION
**Pull request by kmecpp**
Closes #3485

### CODE REVIEW

**Review by JRoy — CHANGES_REQUESTED** [review]
I'm pretty sure changing the method like that would cause ABI breakage to anyone who was using that API beforehand. I think a better solution would be to add another `!isAfk()` (on line 610) rather than this.

**Comment by kmecpp** [comment]
Updated

**Review by JRoy — APPROVED** [review]

**Review by triagonal — CHANGES_REQUESTED** [review]
Was this PR tested? 

While this seems to work for automatic AFK checks (interact, movement, chat, etc.), the current implementation has a strange effect on manual toggling using the /afk command.

image

In the above example, the player **is AFK**. At each arrow the player attempts to use the /afk command to exit AFK mode, the event is cancelled, and a message is displayed.

image

In the above example the player **is not AFK**. At each arrow there is an attempt to enter AFK mode using /afk, the event is cancelled, and a message is displayed.

It also appears that AFK messages as a result of the auto afk timer have not been properly stopped either.

image

In the above example the player **is not AFK**. At each arrow the auto AFK timer is triggered, the event is cancelled, and the "Player is now AFK" message is repeatedly broadcasted as the plugin attempts to set their AFK state.

**Comment by pop4959** [comment]
Closing due to author inactivity. Can re-open if there are signs of life, especially addressing any concerns that have been mentioned.

**Pull request closed without merging**
