### PR TITLE
Implement Discord integration module

### LINKED ISSUE #3129: EssentialsXMPP but with Discord
### Feature request

**Feature description**
A new EssentialsXMPP-like addon, but with Discord, maybe using DiscordSRV* API, that allows:
- Players who use Discord service are able to set their Discord ID ingame, which allows for other players to message them when they are not connected to minecraft.
- If you enable Discord spy for a user, that player will get a copy of ingame messages sent to their Discord account, as if they were connected and ingame.

**How the feature is useful**
Most servers now-a-day use Discord, I still use XMPP but I think it's something most users don't use nor admins. It would be a different direction of EssentialsX moving to Discord instead of keeping locked to XMPP.

*https://www.spigotmc.org/resources/discordsrv.18494/

### PR DESCRIPTION
**Pull request by Ichbinjoe**
I want to put this in a PR so we track it better than we do currently - development seems to have stalled on this module.

Closes #3129

### CODE REVIEW

**Comment by montlikadani** [comment]
Please remove message string from AfkStatusChangeEvent. We are able to create a message string when a player afk so it is not needed.

**Comment by Ichbinjoe** [comment]
@montlikadani You can pull request against the feature/discord-module if you want to make changes!

**Comment by mdcfe** [comment]
@montlikadani The message is to allow plugins to access the AFK reason from the AfkStatusChangeEvent. The reason isn't part of the event yet, but it will be added soon.

**Comment by montlikadani** [comment]
@md678685
Ok, but if someone use the VanishStatusChangeEvent and wants to be able to get the message, then this not possible.

**Comment by mdcfe** [comment]
@montlikadani You can't include a message when you do `/v` - there isn't a `/v [reason]`, so there isn't a message to include in `VanishStatusChangeEvent`. However, you *can* include a message when you do `/afk`, which is why there is a message in `AfkStatusChangeEvent`.

**Comment by mdcfe** [comment]
Closing in favour of #3283.

**Pull request closed without merging**
