### PR TITLE
Fixed typo in Dutch (NL) translation

### PR DESCRIPTION
**Pull request by Muspah**

### CODE REVIEW

**Comment by Xeyame** [comment]
Shouldnt this be done on crowdin?

**Comment by Muspah** [comment]
Whoops, Crowdin? Do you have a link for it?

**Comment by Xeyame** [comment]
https://crowdin.com/project/essentialsx-official

**Comment by Muspah** [comment]
Thanks! Only read the README in the repo here, which talks about PR'ing language changes :)

"If so, we always welcome pull requests to our language files."

**Comment by Xeyame** [comment]
Yep no problem :D, that is a bit outdated i think.

**Pull request closed without merging**
