### PR TITLE
Added missing translations

### PR DESCRIPTION
**Pull request by leonardo-dgs**

### CODE REVIEW

**Comment by mdcfe** [comment]
Thanks for the contribution, but I don't see the purpose of adding the missing messages to a translated file unless they are translated to the target language?

**Comment by leonardo-dgs** [comment]
@md678685 I don't know these languages, so I can't translate it, but I've added the missing strings for more order, so will be easier to translate

**Comment by leonardo-dgs** [comment]
@md678685 I've finished, you can merge the pull request, please can you merge even the PR #1656?

**Comment by Leomixer17** [comment]
#1380

**Comment by leonardo-dgs** [comment]
I've also fixed the double "=" of socialSpyMutedPrefix

**Review by mdcfe — APPROVED** [review]

**Comment by leonardo-dgs** [comment]
@md678685 Please, can you merge this PR, because it may easily create conflicts with the base branch, I also reordered the strings

**Comment by mdcfe** [comment]
Thanks for fixing the merge conflicts - since commits that add messages usually add them to all messages files anyway, this may as well be merged for consistency's sake. Thanks for your contribution!

**Pull request merged**
