### PR TITLE
2.x fixed - Offline Users

### PR DESCRIPTION
**Pull request by mickare**
Many commands like seen didn't work properly on users that are Offline and had not joined the server since the last restart.
This should fix the problem and automatically reimports all users from their files into the usermap.

_Additionally fixed some multiple config saves, while a player joins/quits_

### CODE REVIEW

**Comment by mickare** [comment]
The branch has some more commits to fix the lastlogout time.

**Comment by vemacs** [comment]
Merged, thanks. I don't mean to be unfriendly, but can you use your IDE's autoformatter and Oracle Java whitespace conventions for future PRs?

**Comment by mickare** [comment]
You mean that convention from 1999?

**Comment by vemacs** [comment]
Still better than your made up one with inconsistent spacing..

**Comment by mickare** [comment]
Hello, you forgot to merge some ESSENTIAL commits to fix the problem!

https://github.com/mickare/Essentials/commit/3e22f86addc626311bd36c8b59956a71aaa4c782
https://github.com/mickare/Essentials/commit/57de6e48b5f7ebf27a39457eb885b38f85cd18e6

The current state still has sometimes a data loss.
It happens when there is a write and read simultaniously (Race-condition)!

**Comment by vemacs** [comment]
That breaks the unit tests very badly. EconomyTest in particular.

**Comment by mickare** [comment]
Okay... then just look at it.

You could try to fix it yourself if you get the idea. I don't have the time for it, especially since the whole project pom dependencies is all messed up. (Who in the right mind includes dependency jars into the git repo, start using maven repositories.)

##UUIDMap.java## 
1.) Move createNewFile into synchronized block. (https://github.com/mickare/Essentials/commit/3e22f86addc626311bd36c8b59956a71aaa4c782#diff-352c99678d482f480aeeb122c00a3807R32)
 `if (!userList.exists()) {
  userList.createNewFile();
}`

2.) Introduce loaded boolean. (https://github.com/mickare/Essentials/commit/3e22f86addc626311bd36c8b59956a71aaa4c782#diff-352c99678d482f480aeeb122c00a3807R70)
 `private boolean loaded = false;`

3.) Load before saving (https://github.com/mickare/Essentials/commit/3e22f86addc626311bd36c8b59956a71aaa4c782#diff-352c99678d482f480aeeb122c00a3807R101)
`synchronized (pendingDiskWrites) {
  if(!loaded) {
    loadAllUsers(ess.getUserMap().getNames(), ess.getUserMap().getHistory());
  }
}`

4.) Don't clear contents before reloading! It is a cache and we don't want to forget anything. (https://github.com/mickare/Essentials/commit/57de6e48b5f7ebf27a39457eb885b38f85cd18e6#diff-352c99678d482f480aeeb122c00a3807R40)

```
names.clear();
history.clear();
```

Greetings

**Comment by vemacs** [comment]
The original Essentials team aren't very well known for their packaging skills. I don't feel like disk I/O operations are slow enough and that user relogs are fast enough to make this an issue.

**Comment by mickare** [comment]
So, why is it still happening?
Recently we put the newest version onto the server and immediatly the UUIDMap was empty.
My "hacked" version did not have any of this problem since October.

Therefore this is an issue.

You could also redesign the whole UUIDMap File loading/saving. I'm sure there are some possible improvements.

**Comment by vemacs** [comment]
Don't know, never had it happen for me (300+ concurrent player instances). I get the "niceness" of having a lock, but I've never heard of anybody else having this issue.

**Comment by mickare** [comment]
Oh really? ^^
"AshourAziz referenced this pull request on 17 Oct"
https://github.com/drtshock/Essentials/issues/226

Just do it. I and many more would be happy if seen actually would work again. ;)

**Comment by vemacs** [comment]
The relevant code for /seen was already pulled: https://github.com/drtshock/Essentials/commit/a844e8b5adb7cee8fe9a28846a6ae875165e10f2

Specifically in EssentialsPlayerListener.

I'd be glad to pull those changes in if you could make them pass the unit tests. Last seen data is not stored in usermap.csv.

**Comment by vemacs** [comment]
Furthermore, there already is upstream code to deal with the synchronization issue you mentioned: https://github.com/essentials/Essentials/commit/8964d38c3e1bddfa1ae9f76b889cfce37409d24b

Anything more than your EssentialsPlayerListener changes are unnecessary.

**Comment by mickare** [comment]
Nope, that is not the relevant code.

The commit missed the changes to the UUIDMap.

The commit contained:
1. Some formating issues 
2. Missing user transactions
3. Repair the broken UUIDMap from User files.

The relevant code was commited also with:
https://github.com/mickare/Essentials/commit/3e22f86addc626311bd36c8b59956a71aaa4c782
https://github.com/mickare/Essentials/commit/57de6e48b5f7ebf27a39457eb885b38f85cd18e6

"When writing UUID-Map, first load if not already loaded. Else it could be that there is a data loss."

And the data loss is the main part why the seen command is not working anymore.
The UUIDMap is empty, because of a raise condition.

I know it is a little confusing with those multiple commits. But they belong all together...

I get the feeling you just don't want to see the issue. If it's like that there is no helping. I flagged the issue, now it's your turn.

---

@ Last Comment, ~~that commit is the problem! Gosh!~~ Or at least it was not thought through to the end.

**Comment by vemacs** [comment]
The UUIDMap changes failed testEconomy: https://ci.drtshock.net/job/EssentialsX/205/net.ess3$EssentialsX/testReport/

Regardless of whether or not the changes to it are necessary, if you wish to see it implemented, explain why your usermap.csv synchronization code is "better" than upstream's and fix the test passing. The /seen modifications were already pulled. 

> And the data loss is the main part why the seen command is not working anymore.

usermap.csv/UUIDMap does not handle last seen data. Open it up yourself. The /seen command works perfectly fine with solely the transaction improvements, which have been pulled.

**Comment by mickare** [comment]
Do you remove the usermap file before you do the test?
Could it be that it still exists from the last test?

**Comment by vemacs** [comment]
No, because it's not run on an actual Bukkit server. Just run mvn clean install, please.

Again, **usermap.csv/UUIDMap has nothing to do with last logout data**.

**Comment by mickare** [comment]
I can't because the project setup is broken. (39 Errors) Mostly "Missing artifact" and "Failed to read descriptor for ... craftbukkit".... and i'm not in the mood fixing it.

Okay, I came to an conclusion!

Facts:
1. There is definitly an issue that the UUIDMap is cleared.
2. The unit test is failing with the fixes that the UUIDMap is not cleared.
3. The unit test asserts false that the npc does not exists.

=> The NPC exists when the unit test is starting.

Conclusion (either): 
1. Either the unit test is broken.
2. Or my fixes are broken.
3. Or the testing file is not cleared and because I fixed an issue the unit test now fails since the fixed code does work correctly now and the unit test setup fails to clear the created file.
4. Another unit test or part in the FakeServer creates the npc.

I think it's 3.
Did you test it?

**Comment by vemacs** [comment]
Read the readme (specifically the BuildTools section). We do use NMS to support older Spigot 1.8.x versions.

The unit test doesn't write any files based on what I've seen, so it's not 3).

**Comment by mickare** [comment]
### EVERYTHING has to do with the UUIDMap!

**The UUIDMap is used to lookup the UUID for the name of a player.**

```
/seen < name >
```

queries the UUIDMap for the **< UUID > of < name >**

If UUIDMap is empty, **NO UUID IS FOUND**!!!
Ergo no user data file is found.
Ergo no last logout data.
Ergo no last seen.

Gosh! Come on!!!! I'm getting annoyed. :(

**Comment by vemacs** [comment]
That falls back to Bukkit.getOfflinePlayer(). UUIDMap is not the only source for finding name  -> UUID mappings.

Actually, I lied (that was for Unban commands). I'll add that to /seen. Still a better solution than the magic usermap synchronization stuff.

**Comment by mickare** [comment]
That is not working.

### Essentials.java

`public User getOfflineUser(final String name)`

calls

### UserMap.java

`public User getUser(final String name)`

https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/UserMap.java#L67

If the **String name** was not found in the usermap. (not found in our case here)
Then it is searched for the userdata file with **the name as filename**.

## And it definitly does NOT exist at that point. Since the file is saved under UUID!

Only if the file exists, then getOfflineUser is called... or something.
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/UserMap.java#L78

So let me recap.
Get User with **String name**, will return **null**, because:
1. UserMap is empty
2. userdata file is saved as **< UUID >.yml**

**Comment by mickare** [comment]
The UUIDMap is used to identify the correct userdata file for the user's name. ^^

**Comment by vemacs** [comment]
Yeah, that's why I said that I'm falling back to Bukkit.getOfflinePlayer() to retrieve the UUID.

**Comment by mickare** [comment]
No, this is a **misconception** on your side!

Bukkit.getOfflinePlayer() is only called if the userdata file called "< playername >.yml" exists!

Look at this code... https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/UserMap.java#L75

And tell me what happenes here in line 75 and 76 if the userdata file is not named "mickare.yml" but was already transferred to UUID style "ad91d5ea-56bd-488f-ba3f-633d504f33e9.yml".

**Comment by vemacs** [comment]
Yeah, that's what I'm implementing. If a user isn't in the usermap, we fall back to a Mojang UUID lookup.

I talked to some other users, and literally nobody has experienced usermap.csv being deleted. What _exactly_ is wrong with @KHobbits synchronization approach?

**Comment by mickare** [comment]
Example...

userFile - does not exist!

```
if(userFile.exists())
```

returns false!

ERGO... you can guess? The inner part of the If condition is NOT executed!
**AT NO POINT Bukkit.getOfflinePlayer() is called!**

**Comment by vemacs** [comment]
What drugs are you on? I admitted that I was wrong... 4 posts ago. That's why I'm implementing a fallback.

Anyways, can you contest the fact that nobody else has reported a usermap.csv deletion, and that the upstream synchronization approach works fine?

**Comment by mickare** [comment]
Sorry... nope, you didn't... oO

**Comment by vemacs** [comment]
> Actually, I lied (that was for Unban commands). I'll add that to /seen. Still a better solution than the magic usermap synchronization stuff.

Again, what is wrong with the current synchronization approach? Do you have any evidence that the other bug report you mentioned was a result of a usermap.csv deletion? Do you have any other documentation of any usermap.csv deletions occurring outside of your own experience?

**Comment by mickare** [comment]
If you are at it... then remove the UUIDMap saving to disk. If you do it that way it is obsolete.

**Comment by vemacs** [comment]
Don't blame me. That's upstream. Can you explain why it's "obsolete"? Your changes are breaking tests.

**Comment by mickare** [comment]
If you query Mojang and the UUIDMap is broken (since it is empty after a restart) then just only query Mojang. The UUIDMap is then useless.

**Comment by vemacs** [comment]
1. It's not empty after a restart for anybody except you. I just restarted 2 of my actual production servers with hundreds of concurrent players, and started a test server. Cannot replicate.
2. Mojang queries block the main thread.

**Comment by mickare** [comment]
It is empty for me and him https://github.com/drtshock/Essentials/issues/226
Server has SSD and a lot of power.

LOL we are at the start again....

**Comment by vemacs** [comment]
#226 never mentioned usermap deletion. It could have been the logout time being improperly written.

**Comment by mickare** [comment]
Omg that stuff you are taking, I want it!

**Comment by vemacs** [comment]
Show me a usermap deletion example with the latest EssX build. Then I'll start taking you seriously.

**Comment by mickare** [comment]
Sry, what do you want me to show you? An empty file, when there should be more than 120.000 lines? oO

Could you please talk to the other collaborators? Is there a chance that one of them can take care of it?

**Comment by mickare** [comment]
Repaired usermap.csv file has 128771 lines.
That are 6MB. -> File size is not an issue.

**Comment by vemacs** [comment]
Yeah, I did in IRC. Nobody thinks this is an issue.

> Sry, what do you want me to show you? An empty file, when there should be more than 120.000 lines? oO

A screen recording of you listing the directory contents when the file is not empty and the server is running, you restarting the server, and the empty file being shown.

Here's some numbers from servers running EssX/Ess/upstream synchronization code that have survived thousands of restarts:

```
cat usermap.csv | wc -l
166964 

cat usermap.csv | wc -l
92754

cat usermap.csv | wc -l
54913
```

Never once have I seen the repair operation being run more than the first time. Never once has it been empty.

**Comment by mickare** [comment]
This is a racecondition. You are kidding to ask me to do a recording.

Okay... I did it somehow... I reproduced the error.

While restarting the server I spammed /seen <a player> commands and usermap.csv got empty.

Before restart and spamming...

```
cat usermap.csv | wc -l
128771
```

After restart...

```
cat usermap.csv | wc -l
1
```

**Comment by vemacs** [comment]
I implemented a fallback to Mojang/usercache lookup for if that actually happens, and will consider your proposed usermap changes if you can provide concrete evidence (screen recording, logs of any sort) that it's actually an issue. 

Edit: didn't see your response. Will try to reproduce that. Apologies for the confusion.

**Comment by vemacs** [comment]
Just to clarify, are you spamming the /seen command during the shutdown process?

**Comment by mickare** [comment]
I was using build https://ci.drtshock.net/job/EssentialsX/228/

http://i.imgur.com/YJiitpE.gif
Image from console checking after each restart.
The last is where is previously spammed the seen command.

**Comment by mickare** [comment]
Yes, I spammed while and just before the restart.

But again: It could be just luck. Typically a race condition.

**Comment by vemacs** [comment]
I understand your point now. It looks like any changes to actually fix the condition will end up breaking tests of some form, so I'm wondering if solely saving the map on shutdown would be a valid solution.

**Comment by mickare** [comment]
What if the server does crash?

For me the best part would be to synchronize the file creation and removing the names.clear() call.
Also always load the map if you save it.

By the way... that's the way Bukkit load/saves configuration files.
If you save it, it'll first load it (if not already).

**Comment by vemacs** [comment]
Actually, it looks like my fallback change breaks the test. So it's not your changes in particular.

Edit: or not. Just simple nullcheck + try-catch fixed it.

**Comment by mickare** [comment]
An hour ago:

"3. Or the testing file is not cleared and because I fixed an issue the unit test now fails since the fixed code does work correctly now and the unit test setup fails to clear the created file."

xP

http://cdn1.theodysseyonline.com/files/2015/10/12/635802159520115831-439254519_failed-you-have.jpg

**Comment by SupaHam** [comment]
@mickare Please go on your server, type /ess reload, and give me the version information

**Comment by mbax** [comment]
I'm just gonna step in here to say:

It's great when somebody identifies a problem in a plugin and attempts to fix it. It is **not great**, however, when that person gets needlessly aggressive. Hug it out, everybody.

**Comment by mickare** [comment]
Tested with 2.0.1-b228
on CraftBukkit version git-Spigot-76236cb-62a2169 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

@mbax Needlessly? I beg for pardon. I don't like to be treated as a joke: "Then I'll start taking you seriously."
It needed huge effort to convince that there is an issue that should have been fixed a month ago. 

I hope you guys can handle some citicism and taunt. ;)

**Comment by vemacs** [comment]
I apologize for that comment, but you were being needlessly aggravating beforehand.

> You could try to fix it yourself if you get the idea. I don't have the time for it

As you can imagine, we don't like accepting pull requests that breaking existing functionality in non-obvious ways.

Either way, thanks for giving reproduction instructions for the issues.

**Comment by mickare** [comment]
I literally don't have time to do it myself. I have another project and work to do due tomorrow. ^^'
I hoped the pull request just worked, but it didn't. :S

**Comment by drtshock** [comment]
We also have lives outside of contributing to this fork of essentials in our free time. Suggesting contributors are on drugs and acting like you're too good to do the work yourself isn't ok. We appreciate the dedication and reporting of issues; please try to do so in a more positive manner next time :)

**Comment by SupaHam** [comment]
Regarding the 4a0507a, the duration of copying on the main thread is about ~40ms with about 100k entries. These sync writes only happen when an admin is present, since they only happen during upgrades and reloads/restarts.

**Comment by mickare** [comment]
@drtshock
Yes, I went a little bit overboard. But plz excuse that, but I felt like treated as a fool.
Instead listening to my attempts to find the problem mere references to other commits or the readme was made. vemacs turned a deaf ear to me and did not even try to understand the issue. I tried to point at the UUIDMap, not at the seen command.
Oh and fun fact. I did not **start** with suggesting anyone is on drugs. Please talk in that regards to vemacs.

If I read now the comment history, it seems now like I'm the bad person here. :unamused:

I'm sorry for that misunderstanding, I'm German and sometimes my English is bad. I never meant to say "I'm too good to do the work". I just already did a commit a month ago and yesterday found out that half was missing. The thing is I have a lot other stuff to do at the moment, that is what I wanted to say.
It takes time for me to import Essentials and fix the pom settings so it works correctly in eclipse. My eclipse/maven installation has problems with finding libraries in the work directory...

It is a difficult race condition. And I understand it is hard to find. But please, next time, don't treat issue reporter like fools.

Anyway big thanks to vemacs taking your time to work out this issue. Even though it got a little rough at the end. ^^

**Comment by vemacs** [comment]
I apologize for the personal attack, it got out of hand. Anyways, can you replicate the spamming /seen issue while the server is restarting with this change? I tried it three times, but just wanted to confirm.

**Comment by mickare** [comment]
One moment please, I try it.

**Comment by mickare** [comment]
It worked 3 times like a charm.
**The usermap is still cleared.**

Again I spammed the seen command on restart.
But this time I looked at it in my ftp client and looked at the console output.
The usermap.csv was cleared now not at shutdown. But it was cleared at startup.

I'll try to replicate this a second time.

**Comment by mickare** [comment]
Now one time only ~10% remained in the file. 16.468 lines, but it should be 128.793 lines.

**Comment by mickare** [comment]
Build Version 2.0.1-b233

**Comment by mickare** [comment]
I tried now 10 times spamming in both terminal and ingame seen commands while restarting.
Automatically pasting 7000 seen commands into terminal while manually spamming seen in minecraft client.

**Comment by vemacs** [comment]
So, the issue still occurs even with that. Does the Mojang fallback temporarily band-aid the problem for /seen, however?

**Comment by mickare** [comment]
It happened again. The file is empty.
I restarted the server. While the server started I (op) joined (into that join queue).

**Comment by mickare** [comment]
> vemacs:
> ... Does the Mojang fallback temporarily band-aid the problem for /seen, however?

Yes it does help! <3

**Comment by SupaHam** [comment]
Could you please http://pastebin.com your log of a session that clears usermap.csv during shutdown.

**Comment by mickare** [comment]
Sry can't do. Too much private information in the log file.
But I can copy all Essential log output. There are no exceptions.

This was the one time the file got delete while startup.
http://pastebin.com/f6iNzivJ

The one while shutdown is hard to identify. All those look the same.
... Essentials enabled ... Stopping server ... Essentials disabled.

**Comment by SupaHam** [comment]
Then you'll have to censor out any private information, if you give me half the log of what you think is relevant, I won't be able to help you without further information.

**Comment by mickare** [comment]
Plz believe when I say, that there is nothing special to see.
Or is there anything you are already thinking of?

I still believe the race-condition is not fixed.
In your last commit you added `names = new HashMap<>(names);` but that part is not synchronized with `names.clear()`!

Take a look (https://github.com/drtshock/Essentials/pull/293)

**Comment by mickare** [comment]
Offtopic: Is it normal for two tests to fail?
I'm trying to create a revision of the UUIDMap. :innocent:
https://github.com/mickare/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/UUIDMap.java

The unmodified version has the same unit test failures as my modified version. Did I miss anything?

**Pull request closed without merging**
