### PR TITLE
Implement configurable currency formatting.

### LINKED ISSUE #432: Add toggle to disable number format
Currently the currency number format is in American style, which shouldn't be forced upon users. Either make it configurable or add a toggle.

Commit: https://github.com/drtshock/Essentials/commit/419d2d828245dafa8bb55abd0d179fee45422015

### PR DESCRIPTION
**Pull request by SupaHam**
This commit enables users of different countries around the world to configure currency formatting displayed to users in a familiar manner.

Prior to this commit US formatting (symbols) was forced upon users. This is now configurable via locale values e.g. en-US, de, fr-ch.

This commit adds two new configurations:
- currency-format
- currency-symbol-format-locale

One method ISettings#getCurrencyFormat()

This resolves #432 and #504.

### CODE REVIEW

**Comment by Kakifrucht** [comment]
Finally! Thank you.

**Comment by Kakifrucht** [comment]
Can this be merged?

**Comment by SupaHam** [comment]
@drtshock @vemacs pls

**Comment by vemacs** [comment]
I really don't see anything wrong

**Comment by drtshock** [comment]
done ty <3

**Comment by Kakifrucht** [comment]
<3

**Pull request merged**
