### PR TITLE
[i18n] Fix zh_CN translation of balancetop

### PR DESCRIPTION
**Pull request by SerinaNya**
### Information

This PR fixes nothing.

### Details

**Proposed fix:**    

Changed `balanceTopLine={0}。{1}，{2}` to `balanceTopLine={0}. {1}, {2}`. It makes the translation more compatible with the typing habits of Simplified Chinese users. The origin format was too strange!!!

**Environments tested:**    

OS: Windows Server 2016

Java version:  16.0.1

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [x] CraftBukkit/Spigot/Paper 1.12.2
- [x] CraftBukkit 1.8.8

**Demonstration:**

### CODE REVIEW

**Comment by triagonal** [comment]
Thank you for your contribution! Updates to language files should be submitted on our [Crowdin project](https://crowdin.com/project/essentialsx-official). If you'd like to discuss changes with other translators and proofreaders, you can join the [development discord](https://discord.gg/CUN7qVb).

**Comment by SerinaNya** [comment]
The translation was updated. Could you apply the changes in the next dev version? thx

**Comment by pop4959** [comment]
It'll get updated as soon as #4281 is reviewed and merged. Thank you for your contribution!

**Comment by SerinaNya** [comment]
GOOD 😄. Thanks a lot!

**Pull request closed without merging**
