### PR TITLE
Add restart note to respawn listener priority option

### PR DESCRIPTION
**Pull request by JasonHorkles**

### CODE REVIEW

**Comment by JRoy** [comment]
should add for `spawn-join-listener-priority` too

**Comment by JasonHorkles** [comment]
Should it be copy and pasted or just add that it also applies to spawn-join-listener-priority?

**Comment by JRoy** [comment]
copy-paste

**Review by JRoy — APPROVED** [review]
good for merge after gradle refactor

**Review by mdcfe — APPROVED** [review]

**Comment by JRoy** [comment]
Hello, can you please rebase this pull request so we can merge it! Thanks!

**Comment by JasonHorkles** [comment]
> Hello, can you please rebase this pull request so we can merge it! Thanks!

do i need to do that cuz if so i have no idea how lol

edit: ah that's why
image

**Review by pop4959 — APPROVED** [review]

**Pull request merged**
