### PR TITLE
fix spawners

### PR DESCRIPTION
**Pull request by PhanaticD**

### CODE REVIEW

**Comment by Kakifrucht** [comment]
Nice, thanks!

*can't confirm if it works*

**Comment by PhanaticD** [comment]
i can confirm it work ;)

**Comment by mdcfe** [comment]
Thanks for implementing the fix [suggested](https://github.com/drtshock/Essentials/issues/1525#issuecomment-325506258) in #1525 - we'll merge it once we've tested that this fixes the issue.

**Review by LaxWasHere — APPROVED** [review]

**Review by Kakifrucht — APPROVED** [review]

**Comment by Kakifrucht** [comment]
Can somebody please merge this? What are we waiting for?

**Comment by Kakifrucht** [comment]
Thanks :)

**Pull request merged**
