### PR TITLE
Implement confirmation dialogue for `/pay`.

### PR DESCRIPTION
**Pull request by SupaHam**
This PR implements a new confirmation dialogue to the `/pay` command to prevent international language issues with monetary formatting.

This PR primarily aims to combat issues of unintentional payment amounts as discussed in #977. Some countries use `,` as a decimal separator and other characters as thousands separator. In the US and GB and many other countries `,` is used as thousands separator and `.` as the decimal separator. As each server is different from others, especially nation and language wise, this can introduce issues with currency formatting, where decimal and thousands separator are used reversely causing different amounts to be parsed by EssentialsX.

This PR not only resolves that worldwide ambiguity, it is also an additional layer of security for anyone else who uses `/pay` command.

### CODE REVIEW

**Comment by SupaHam** [comment]
@drtshock @vemacs

**Comment by Kakifrucht** [comment]
Looks good, why did you decide to use a map instead of something like a pair?

**Comment by SupaHam** [comment]
Because you can send money to multiple people at the same time, see `updatePlayer` in `Commandpay`.

**Comment by mibby** [comment]
@SupaHam Would it be possible to add a config toggle to disable the pay confirmation? Getting quite a few complaints from my community that they do not like having to re-type the command.

**Comment by Kakifrucht** [comment]
@mibby up+enter too much for them?

**Comment by CheatSupport** [comment]
can we g et this for /clear too? @SupaHam

**Pull request merged**
