### PR TITLE
Disable kits file creation when it is in the list

### PR DESCRIPTION
**Pull request by montlikadani**

### CODE REVIEW

**Comment by mdcfe** [comment]
This breaks the kit API for other plugins, which may still want to use EssentialsX's kit code even when `/kit` is disabled.

**Comment by montlikadani** [comment]
@md678685 Then try to search for the kit class registration method in the Main class and write the code for it?

**Comment by mdcfe** [comment]
@montlikadani I'm not sure what you mean?

**Comment by montlikadani** [comment]
I mean looking for the Kits.class registration in Essentials.class and matching `essentials.getSettings().isCommandDisabled("kit")`

**Comment by mdcfe** [comment]
I don't see how that fixes other plugins that will try and use the `Kit` and `Kits` classes?

**Comment by montlikadani** [comment]
If want to use it, must remove the `/kit` command from the list and reload the server. So it will load and the kit will work. I recommend to the developer who created compatibility with the EssentialsX plugin to remove that command from the list.

**Comment by mdcfe** [comment]
I don't see how this is useful though. This is just a breaking change for the sake of breaking things. There are lots of plugins out there that work with Essentials' old API, and if we change this they might stop working for no real reason.

**Comment by montlikadani** [comment]
This commit fixes the break. Also included in the title is that it only prevents the creation of a file when the 
`kit` command has in the list. This prevents unnecessary file creation when disabled.

**Comment by mdcfe** [comment]
If a plugin tries to use the kit API when `/kit` is disabled, it will still throw a NullPointerException.

I still don't understand why this change is needed. This does not solve any problems and doesn't improve anything.

**Comment by montlikadani** [comment]
Okay, I'll close this PR. This PR was about not creating a `kits.yml` file when **there is a kit command in the list**, so fewer files are created at server startup.

**Pull request closed without merging**
