### PR TITLE
Updated respawn at home/bed

### PR DESCRIPTION
**Pull request by ghost**
### Information

This feature makes the respawning after death at home/bed more logical.

### Details

**This feature making this:**
If config options ``respawn-at-home`` and ``respawn-at-home-bed`` are both enabled and player has no home point then he will be spawned at bed location else he will be spawned at spawn or home location.

- [x] [Latest](https://papermc.io/downloads) Paper Version (any OS, any Java 8+ version)
- [x] CraftBukkit/Spigot/Paper 1.12.2 (any OS, any Java 8+ version)
- [x] CraftBukkit 1.8.8 (any OS, any Java 8+ version)

**Demonstration:**    
No demonstration, sorry. You can download artifacts of build and test yourself. Works fine.

### CODE REVIEW

**Comment by ghost** [comment]
So what?

**Review by pop4959 — CHANGES_REQUESTED** [review]
Not convinced that this code is correct, as if the user has the respawn at bed option enabled, they will not be sent to their bed location unless they don't have a home, which is very unintuitive.

Also, please do not change random whitespace or nuke important comments left in the code.

**Comment by seema84** [comment]
actually not a bad idea which offers more possibilities for the respawn
with priorities this could already be logically comprehensible

**Comment by pop4959** [comment]
Closing this since the author's account is deleted. If someone does care for improving the respawn system, please make a new PR.

**Pull request closed without merging**
