### PR TITLE
Only enable fly on join if user is allowed to fly

### LINKED ISSUE #1547: No permissions check for essentials.fly.safelogin
EssentialsX version (`/essentials`): 
2.0.1
Server software (`/version`): 
Spigot-1.12
EssentialsX config (if applicable): 
Not applicable

If players have the `essentials.fly.safelogin` permission they get fly on connect regardless if they have `essentials.fly`, this violates the "permissions non-inclusive" style of Essentials.

### PR DESCRIPTION
**Pull request by mdcfe**
Fixes #1547 and closes #1548.

### CODE REVIEW

**Comment by SupaHam** [comment]
Why is this better than #1548?

**Comment by mdcfe** [comment]
This allows server owners to set `essentials.fly.safelogin` without `essentials.fly`. Currently this means it will reset the player's fall distance without enabling flight, but could be extended to move them to a safe login location if desired.

**Comment by SupaHam** [comment]
I think that should be implemented separately. Following a convention of permission node sections being parent to the following section (if present), a `essentials.fly.safelogin` should only become usable if `essentials.fly` is present.

**Comment by mdcfe** [comment]
Just noticed that the [Essentials documentation](http://wiki.mc-ess.net/wiki/Command_Reference/Perm) states:
```
Players with this command (sic) will automatically switch to fly mode if they login whilst floating in the air.
```

Based on this, I think we should implement a separate `essentials.safelogin` permission that will behave like `essentials.fly.safelogin` if the user has `essentials.fly`, otherwise teleport them to the nearest safe location. This would fix the actual problem in #1547; if flight was enabled for the user by an admin but the user doesn't have `essentials.fly` when they log in, they won't fall to their death, but they also won't get free flight by jumping off a cliff and relogging.

(`essentials.fly.safelogin` would then be an alias of `essentials.safelogin`.)

**Comment by SupaHam** [comment]
I'm against aliasing as I said before. `essentials.safelogin` can be added and `essentials.fly.safelogin` be the permission that enables flying on login. To clarify, this might be a breaking change for some who explictly permit `essentials.fly.safelogin`, requiring them to permit `essentials.safelogin`. Inconvenient for the moment, but convenient in the long run.

**Comment by mdcfe** [comment]
I'm against sudden changes to existing behaviour - if I'm understanding this correctly, this means that the functionality of `essentials.fly.safelogin` would then require three separate permissions, including retaining an existing permission but with a breaking change to its purpose and behaviour. This doesn't seem any more convenient in the long run than temporarily aliasing the perms.

As an alternative to both, `essentials.fly.safelogin` could be replaced altogether with `essentials.safelogin` which either:
* teleports the user to a safe location, or
* enables flight if they have `essentials.fly`.
If needed, there could also be a config option which allows server owners to disable automatically enabling flight.

Either way, all things considered I don't think any of these approaches nor #1548 are good solutions to the problem in #1547, since the current behaviour is intended according to the Essentials wiki, and [the fact the perm's behaviour hasn't changed in nearly 5 years](https://github.com/drtshock/Essentials/commit/c6dd921f0c91006e360067abf6fe349da031eca4) suggests that it doesn't need changing. The best solution to actually solve #1547 would be just to remove or negate the `essentials.fly.safelogin` permission from users as needed; this doesn't require any changes to EssentialsX at all, and so won't interfere with existing permissions setups.

**Pull request closed without merging**
