### PR TITLE
Expand /exp command

### LINKED ISSUE #1899: Expanding the /exp command
So currently the EXP command is not the equivalent of the eco command. 

## **A+ arg example:**
The eco command has the following args. These args are extremely useful
- Give - Add [amount] to [player]'s balance
- Take - Takes [amount] from [player]'s balance
- Set - Sets [player]'s balance to [amount]
- Reset - Set [player]'s balance to 0

## **What we currently have**:
The exp command only has these args. 
- Show - Returns how much EXP [player] has
- Set - Sets [player]'s EXP to [amount]
- Give - Adds [amount] to [player]'s EXP

## **What we need:**
This suggestion will make the EXP command have the following args:
- Give - Adds [amount] to [player]'s EXP
- Take - Takes [amount] from [player]'s EXP
- Set - Sets [player]'s EXP to [amount]
- Reset - Set [player]'s EXP to 0
- Show - Returns how much EXP [player] has

### PR DESCRIPTION
**Pull request by Xeyame**
closes #1899

### CODE REVIEW

**Comment by caojohnny** [comment]
I'm not sure why this is necessary, even if it's not following the same format as `eco`. You could just add a negative value or set to 0.

**Comment by Flavourized** [comment]
@AgentTroll it's a QoL feature and keeps it consistent. 

I have used essentials for a long while and didn't know you could use negative values. My reasoning is that my eco doesn't allow negative balances, and paying someone a negative amount just gives the positive amount.

Ex. Pay someone -56 and they receive 56. So I assumed the same thing worked for EXP. 

It doesn't hurt to have and makes things clearer/easier to understand

**Review by Ichbinjoe — APPROVED** [review]
Ugh this command is ugly but I think for what it is this is the best change that makes the smallest diff.

**Comment by Ichbinjoe** [comment]
I'll test this & merge

**Pull request merged**
