### PR TITLE
javadoc metaspec 

### PR DESCRIPTION
**Pull request by loopyd**
This commit adds javadoc meta tags to every class in the project for auto-generation of java-doc project documentation for code analysis and project organization tasks conducted by EssentialsX team and for easy reference by plugin developers wishing for a clearly indexable graphical document format .  

Please NOTE:  Future commits will be required to edit the original javadoc commit contributors name (LoopyD) out of the documentation's @author tags where applicable.  javadoc-fix was able to provide some, but not all of this information, and so inserted the default.  Please insert yourself as Author where prompted in the source code in future commits to this fork.

This commit passes javadoc unit tests.  It reports 0 errors and 0 warnings on a maven javadoc goal.

Apache dependencies where added to pom.xml in this commit to support the building of javadoc documentation.  No other changes to the code base have been made other than meta in classes, properties, and method comment meta.

JetBrains IntelliJ IDEA was used to auto-generate this information project-wide.

### CODE REVIEW

**Comment by mdcfe** [comment]
Adding boilerplate javadocs comments everywhere is useless if not detrimental:
* It fills up files with meaningless comment blocks
* It doesn't provide any useful information
* It obscures methods and classes that are *actually* missing proper documentation
* It takes absolutely no effort to `Alt-Enter -> Add Javadoc... ` when we're actually ready to document a method or class

In addition, we don't currently have the infrastructure in place to host Javadocs, so there's not much use in merging in the Maven changes until this is available.

---

While I appreciate the intention of this PR, I don't see any substantial benefit to merging it in its current form. However, feel free to open a PR to add proper documentation to methods.

**Comment by mbax** [comment]
Note sure you noticed, but you also set yourself as author of every file. Whoops!

**Comment by loopyd** [comment]
> If you don't have the infrastructure than I won't bother.

> It did have a good intent, mainly to boiler plate out and format everything correctly so that authors of set functionality could add their two cents into each class as the project progresses, so would the documentation, that was the intent of this commit.

> It was not a simple alt+enter -> Add Javadoc...  There where 3187 Javadoc errors issued by that action that had to be manually corrected.  This was not a 'minimal effort' commit, it was near around 24 hours of fixing Java-doc comments to fit the specification.  Perform the same action yourself on the base repository, then try to compile the docs, and you will see the aforementioned warnings that prevent you from compiling.

**Comment by loopyd** [comment]
Re:  mbax -> Not enough information was provided in the base repository itself to fill that information, if you'd have had a look over the commit message, that error is mentioned, and addressed as a notice for developers to replace it with their own information.  This was a proper boilerplate commit to insert the functionality, and certainly was not minimal effort.

**Comment by garbagemule** [comment]
@loopyd I don't think it's constructive to split hairs about the semantics of what is or isn't "minimal effort", but you seem to be focusing much more on time spent and effort invested than on value provided. Value is not in any way, shape, or form directly proportional to time spent and effort invested, and while honest, hard work should never be brushed off as trivial or pointless, the fruits of that labor may still be just that.

To be clear, whatever method you have used to arrive at the current state of your pull request, the result is still the same: unwarranted and downright wrong `@author` tags and nonsense `@version` tags on all classes, as well as boilerplate JavaDoc comments that provide _zero_ additional information aside from what can already be derived directly from the method signatures (that's how auto-generated documentation works - no surprise there). It doesn't matter that there was additional work after auto-generating everything - that work did not provide _any_ value on top of the value of zero that came from the auto-generated boilerplate. The net sum of value is still zero. In fact, unless you personally gained something from spending all that time on all that nothing, it is entirely fair to consider it a complete and utter waste of time (and that's coming from someone who believes that time is never wasted).

Documentation is an important part of any software project, but _bad_ documentation is almost always worse than _no_ documentation. This little stunt of yours makes the documentation state of the project _worse_ than it currently is, simply because the documentation that exists with your pull request _is a lie_.

To be sure, consider the immediate reaction to an undocumented method vs. that of a documented method. An undocumented class or method will spark no hope of finding additional information in the JavaDocs, but a documented one will. How many methods documented with just auto-generated boilerplate do you think you'd have to run into before you to stop looking at the documentation of methods altogether? The boilerplate creates a smokescreen around the entire project, forcing consumers of the API to adapt a new filter for "no documentation" that can weed through your alleged "high effort" documentation. And I don't know anyone who's that patient.

But yeah, this pull request _is_ minimal effort. It's a massive horizontal sweep of the entire code base that doesn't provide any value whatsoever. Not even the intent behind the pull request can be considered anything but minimal effort - "I can Alt+Enter for people, but they'll have to do the rest themselves." To make matters worse, your commit message places a direct burden on other contributors by "requiring" them to replace your auto-generated nonsense `@author` tags with their own names. Now it's garbage documentation that has to be maintained by other people "just because"? It's negatives all the way down...

To be fair, spending more than 24 hours properly formatting useless auto-generated boilerplate documentation isn't really minimal effort - it's just a weird choice of pastime.

Happy hacking!

---

PS: I'd like to note that horizontal sweeps aren't inherently bad. Typically, though, they revolve around code style cleanup, variable names, etc. These types of sweeps provide consistency, which is a valuable trait in any code base. Vertical sweeps are generally preferable to horizontal sweeps. By definition, they are narrower in scope, which makes them easier to do, review, integrate, and communicate. A solid iteration and room for feedback before tackling the next vertical slice. Perhaps the next pull request can be made from a mindset like this one: "I will properly document this specific part of the API."

**Pull request closed without merging**
