### PR TITLE
Remove offset on certain potion strength values

### LINKED ISSUE #3589: Cannot get potions with health boost power 4
### Information

**Full output of `/ess version`**:

```
Server version: 1.16.1-R0.1-SNAPSHOT git-Paper-135 (MC: 1.16.1)
EssentialsX version: 2.18.0.8
PlaceholderAPI version: 2.10.8
PermissionsEx version: 1.23.4
Vault version: 1.7.3-b131
```

**Server log**: https://gist.github.com/ElectricEzo/251c1e3d404466a6b548e07da09eb113

**EssentialsX config**: https://gist.github.com/ElectricEzo/2c727f4b203632273b28a11c9947cf7c

### Details

**Description**  
When using /potion or having potions in kits, potions with health boost power 4 have power 5 and potions with health boost power 5 have power 6. This means that potions cannot have health boost power 4 on them.

**Steps to reproduce**  
1. Get a water bottle.
2. Do /potion effect:healthboost power:4 duration:100 (any duration works)
3. Notice that the potion has Health Boost V, not Health Boost IV
4. (Extra) Do /potion effect:healthboost power:5 duration:100
5. (Extra) Notice that the potion has Health Boost VI, not Health Boost V

**Expected behavior**  
I expected to have gotten a potion with the appropriate health boost level.

**Screenshots**

### PR DESCRIPTION
**Pull request by uf0h**
fixes #3589

### CODE REVIEW

**Comment by pop4959** [comment]
Are you sure that check wasn't important for something else in the code?

**Comment by uf0h** [comment]
Have checked usage with power at crazier levels (+50) and it works as expected.

I'm of the opinion if any user opts to set potion power a to crazier amount it's their responsibility but let me know what you think about setting an upper limit; just this time higher than 4.

**Comment by pop4959** [comment]
Have you checked all the way back to Minecraft 1.8? Sometimes weird things like this result from incompatibilities in older versions. Although it could very well be that this check isn't needed anymore, just needs to be absolutely 100% confirmed so that we aren't reintroducing a bug or something.

**Comment by uf0h** [comment]
Shows working effects: [link](https://gyazo.com/dc0f56339ac81d8c18d808e22700972d)
Shows lore of potions: [link](https://gyazo.com/74b14db9174d3d90edb4e11b860f208e)

**Comment by pop4959** [comment]
Ah I see, maybe it would be smart to still add a potions.unsafe permission node + config similar to the enchantments stuff, for the levels that do not display properly in game.

**Review by VoltroXP — APPROVED** [review]
Looks good to me 👍

**Comment by mdcfe** [comment]
ce51a07bf18b01fa5b5816ea17b2347eeb89084f added this offset behaviour so that `power:<value>` meta tags would match the names that vanilla uses for each amplifier value - potion amplifier values are 1 less than the value displayed in the name, so `Strength I` actually has an amplifier value of `0`, `Strength III` has a value of `2` etc. For some reason, ce51a07bf18b01fa5b5816ea17b2347eeb89084f only applies this shift to inputs between 1 and 3 (my guess is IV/V/VI didn't have any vanilla usage at this point), but values over and including `4` are not adjusted.

To clarify: EssentialsX has never enforced an upper limit on potion strengths, and this PR doesn't remove such a limit. Instead, this PR removes the limit on the *values that get offset* by `-1`, so that all positive values are adjusted.

Changing this check will change the power applied for all potions in kits, `/give`, `/item` and `/potion`. It's not infeasible for servers to *intentionally* use levels above 4 with custom language files (or even just vanilla for IV/V/VI), and for that reason I'm not sure that breaking this is the best way to give people access to level IV potions.

I'd prefer we added an alternative syntax that *doesn't* attempt to offset potion effect strength, as this would avoid breaking existing kits/potions. I've opened #3614 with an implementation of this, which allows you to replace `power:<value>` with `amplifier:<value>` to use untranslated amplifier values instead of partially-translated ones.

**Pull request closed without merging**
