### PR TITLE
Fixes https://github.com/EssentialsX/Essentials/issues/1755

### PR DESCRIPTION
**Pull request by DrewAMitchell**
Issue was a NullPointerException due to senderUser not being null-checked. I opted to place the couple of lines of code into the sender.isPlayer() check as opposed to null-checking.

### CODE REVIEW

**Comment by drtshock** [comment]
Are those values null checked later on now that they're only set in that statement?
  
EDIT:
Back on computer and yeah looks like that should be fine.

**Review by drtshock — APPROVED** [review]

**Comment by drtshock** [comment]
Lets see if we can get someone else to approve before we pull :)

**Comment by DrewAMitchell** [comment]
@drtshock Just making sure, though, there's no way that ess.getUser(Player) can return null if the user is an online player, right?

**Comment by drtshock** [comment]
Not sure, you could just check :)

**Comment by SupaHam** [comment]
@Drkmaster83 Correct.

**Review by SupaHam — COMMENTED** [review]
Thank you :)

**Pull request merged**
