### PR TITLE
Change {PLAYER} to {USERNAME} in kits.yml comment

### PR DESCRIPTION
**Pull request by JasonHorkles**
Also added a special give command to show that you can give books with the vanilla command if you surround it with `'`

### CODE REVIEW

**Comment by pop4959** [comment]
It's a nice thought but I'm not personally convinced that this is a necessary addition.

**Comment by JasonHorkles** [comment]
It's mainly the {USERNAME} thing that I want changed as using {PLAYER} with give commands and anything else like that won't work if the player has a nickname or prefix/suffix with essentialschat installed

**Comment by pop4959** [comment]
Can you possibly make that as a separate PR from this one?

**Comment by triagonal** [comment]
Using `{player}` as a placeholder will use the player's username (but only if the kit item is a command), and using `{PLAYER}` uses the displayname, which doesn't make a lot of sense. If this PR is accepted, perhaps the [wiki's improvements section](https://essentialsx.cf/wiki/Improvements.html) and all linked copies should advise usage of `{USERNAME}` instead.

**Comment by Ichbinjoe** [comment]
This is a stupid system.

Is this the actual behavior right now?

**Review by mdcfe — APPROVED** [review]

**Pull request merged**
