### PR TITLE
Update to Minecraft 1.21

### PR DESCRIPTION
**Pull request by JRoy**
really only waiting on item aliases and maybe easter eggs

### CODE REVIEW

**Review by CyberFlameGO — CHANGES_REQUESTED** [review]
Enchantments described in output aren't correct (though are applied correctly) - in my opinion should be a blocker to merging

Tested on `2.21.0-dev+99-07f97cf`

Tested on Purpur build 2246 as well as Paper:
```
This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
```
image
image
Ignore riptide that was just testing

image

**Comment by Evidentsinger14** [comment]
image
https://essentialsx.net/dump.html?id=07510f47d29740c49790040ead07e6c6 - Confirmed, this is on a 100% default server.

**Comment by JRoy** [comment]
> Enchantments described in output aren't correct (though are applied correctly) - in my opinion should be a blocker to merging
> 
> Tested on `2.21.0-dev+99-07f97cf`
> 
> Tested on Purpur build 2246 as well as Paper:
> 
> ```
> This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
> You are running the latest version
> ```
> 
> image image Ignore riptide that was just testing image

Should be fixed as of latest commit, was a CraftBukkit bug/change that causes Enchantment#getName to return the wrong name for enchantments. So for example, currently Enchantment.SHARPNESS will return RIPTIDE. Switched to using namespaced keys for 1.13+.

**Comment by CyberFlameGO** [comment]
Seems good to me - looks like the update check for feature branches doesn't work too well (didn't seem to recognise the new commit) but that is probably unrelated/out of scope for the PR

**Review by CyberFlameGO — APPROVED** [review]

**Comment by Tsaitou7361** [comment]
> Enchantments described in output aren't correct (though are applied correctly) - in my opinion should be a blocker to merging
> 
> Tested on `2.21.0-dev+99-07f97cf`
> 
> Tested on Purpur build 2246 as well as Paper:
> 
> ```
> This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
> You are running the latest version
> ```
> 
> image image Ignore riptide that was just testing image

I know this, when I enchanting breach, it shows Projectile Protect...

**Review by mdcfe — APPROVED** [review]

**Pull request merged**
