### PR TITLE
[Fix] Fixes drtshock/Essentials#232, adds splash potion persistence w…

### PR DESCRIPTION
**Pull request by sainttx**
…hen serializing and expanding items

### CODE REVIEW

**Comment by drtshock** [comment]
You should create a new branch for each PR.

**Comment by vemacs** [comment]
Have you tested if this breaks previously serialized items?

**Comment by sainttx** [comment]
@vemacs Haven't ran into any issues with serialized potions lacking "splash" value on local builds

**Comment by SupaHam** [comment]
For the sake of convenience, I would advise serializing `splash` only if it is a splash potion.

**Pull request closed without merging**
