### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by drtshock**
Enjoy!

### CODE REVIEW

**Comment by Madis0** [comment]
Perhaps you could give @md678685 the rights to manage the Crowdin project from now on, as discussed in #1836?
Also, not all translations currently made in Crowdin are better than the ones improved here, so every language that has been updated here should not be pulled directly from Crowdin IMO. (discussed in #317)

**Comment by Madis0** [comment]
Nevermind my previous comment, misunderstood this PR completely 😁 
~@drtshock If you do manage the Essentials 2 project, however, you should mark it as abandoned and link to the new project to help translators find the right one.~
Nevermind, I thought he was a part of the original team.
Relevant issues: https://github.com/EssentialsX/Essentials/issues/1836 https://github.com/EssentialsX/Essentials/issues/317

**Comment by mdcfe** [comment]
@Madis0 As I said, that's managed by the original Essentials, not us. They *could* still actively merge those upstream if they wanted.


@khobbits Would we be able to merge in some of the translations from the [Essentials Crowdin page](https://crowdin.com/project/essentials-2/)? While the languages we currently have translations for are likely already up-to-date, the Essentials 2 project has a few languages that I only just realised we don't have any translations for yet.

**Comment by khobbits** [comment]
@md678685 I don't see how you would have languages I don't.... As this project was started after development ceased on the old essentials.

It is worth noting that the translations are only peer reviewed, so it's possible for nonsense to slip in, if you don't check.

If you sign up on this URL:
http://translate2.ess3.net/project/essentials-2/invite

I can set you as a manager to manage and download the files anytime you want.

Edit:
I've uploaded what I think is your current messages file, to allow translations of the newer keys.

**Comment by mdcfe** [comment]
@khobbits I think there are languages that were never completed and merged into the upstream GitHub repo but are still on the Essentials Crowdin site - I think this applies to Basque, Bosnian, Greek, Norwegian and possibly a few more?

Would you be happy for us to use the old translations from the Essentials Crowdin site as a basis for the missing translations such as the ones above?

**Comment by khobbits** [comment]
@md678685 you're now a manager on the page.
@drtshock if you sign up, give me a shout and i'll add you too.

The translations are all showing as 'incomplete' now, as we've just added a decent number of new keys.
If you have translations for your newer keys, I'd recommend adding them yourself if you want to continue using crowdin.  It is a nice solution.  On the plus side there are something like 900 contributors to the Ess Crowdin project somehow...

**Comment by montlikadani** [comment]
I think we are deleting this whole Crowdin translation because every language file already has a UTF-8 change so all accented characters are already UTF-8. Or, at least, make the entire Crowdin erase (that is, only the files), and then try to put the current one down so that the current one remains. You can see that Crowdin still uses the accented (ANSI) characters, but it is no longer appropriate. I recommend that you don't have to have translation on Crowdin, but who wants to translate it, do it by opening a Pull Request and merging an Essentials developer, but the compiler should use UTF-8 encoding to avoid being spoofed the word is meaningless.

**Comment by mdcfe** [comment]
@montlikadani The problems with UTF-8 are why we haven't started officially using Crowdin yet. We will probably have to remove the GitHub integration and copy the files over manually instead.

**Pull request closed without merging**
