### PR TITLE
Fix NullPointerExceptions

### PR DESCRIPTION
**Pull request by montlikadani**

### CODE REVIEW

**Comment by mdcfe** [comment]
Thanks for the PR, but this only makes the code marginally more readable. This doesn't fix anything except IDE suggestions, so I don't see that this is a necessary change.

**Comment by montlikadani** [comment]
This is necessary as this will come up once because my friend has recently tested one of the plugins and that was in it. I did it and sent it to work properly. This error occurs in Java 8-9 or higher.

**Comment by mdcfe** [comment]
The changes in this PR do not affect the plugin whatsoever. They *only* change how the code looks and cannot fix any bugs.

**Comment by drtshock** [comment]
Thanks for the contribution but please ask before making a PR adjusting code style, as well as don't claim style affects performance :)

**Pull request closed without merging**
