### PR TITLE
A teleport command useful for staffing.

### PR DESCRIPTION
**Pull request by Destitution-SC**
It will teleport you to a random non-vanished player and will check if there's actually a player online.

### CODE REVIEW

**Comment by pop4959** [comment]
Can you explain the use case? This sounds like something that would probably be better off in a custom plugin, rather than in Essentials. I'm not sure that there are many people looking to do something like this.

**Comment by Destitution-SC** [comment]
You may be right. But just wanted to share it. It can be used in staffing where you can find random hackers for other ways I don't really know a use for it. 👍

**Comment by JRoy** [comment]
Your code isn't even in a proper java file which makes my doubt you tested this code. Additionally, this is not essential. You can just hold down tab for a random amount of time (to select a player) in order to achieve the same effect.

**Comment by Destitution-SC** [comment]
I did test my code, why would i post a code that isn't tested. So negative.

**Comment by Ichbinjoe** [comment]
This was obviously created on the Github web UI (which hey, is okay when its a simple change). @JRoy properly pointed out that your java file doesn't even end in *.java: https://i.imgur.com/ws9X9FL.png You might have tested this locally, but you certainly didn't test _this code_ locally.

This changeset also includes a random change to plugin.yml for the /economy command. Why??? Even if its right, this should be in a separate changeset.

As @pop4959 pointed out, this changeset appears to be pretty specific in nature and should probably live in a separate plugin. EssentialsX aims to contain 'essential' commands and utilities for servers, and this just seems too far off the trail to be merged. This should likely live in a separate plugin.

Due to all of these reasons, I don't think EssentialsX is interested in this submission. Feel free to submit a new PR that is constrained to a single feature & has code which has been tested.

**Comment by Destitution-SC** [comment]
I made it first in Intellij IDEA and then pasted here so the screenshot was a typo. But thanks for your explanation.

**Comment by pop4959** [comment]
Thanks for the PR, anyways! It's always cool for people to share things they make upstream (even though, in this particular case, it's a change which is a bit niche). Also as a tip, try making a PR through a branch on your fork pushed through git. If you do it that way, you'll avoid having any typos in the future, since copy/paste can be error prone as you might have discovered.

**Pull request closed without merging**
