### PR TITLE
Improve config.yml comments and structure

### PR DESCRIPTION
**Pull request by mdcfe**
This PR fixes some issues with the config.yml:
* Adds links to the EssentialsX docs where appropriate
* Moves a couple of settings into their correct locations
* Changes headers to remove the weird implications of modularity (EssentialsHelp isn't a module, it's *one* command)
* Updates support link at top
* Minor grammar nitpicks

### CODE REVIEW

**Review by pop4959 — APPROVED** [review]
Carefully read through the changes and I don't see any glaring issues. If you're done with this, just merge it!

**Review by triagonal — APPROVED** [review]
Looks good to me.

**Comment by darbyjack** [comment]
Am glare. Can confirm. Don't see issues.

**Review by Ichbinjoe — APPROVED** [review]
Yeah quite a few things are in confusing places.

**Pull request merged**
