### PR TITLE
Fix an issue with payments

### PR DESCRIPTION
**Pull request by ArtelGG**
Fixes an issue with players being able to send what appears as nothing (zero dollars, zero cents) to others.

### CODE REVIEW

**Comment by mdcfe** [comment]
Could you elaborate on why this change needs to be in the default config?

**Comment by ArtelGG** [comment]
If you send any amount between 0.001-0.009 with the default configuration it will go through, and the formatting will display it as `$0`, players tend to spam this frequently as jokes because it displays as zero dollars, this fixes that.

**Review by mdcfe — APPROVED** [review]
There's nothing wrong with this per se, but I'm not sure why we can't just instruct admins to change either this or the currency format themselves to show the same decimal points as the minimum value.

**Comment by ArtelGG** [comment]
I see this as a much easier and more viable choice rather than somehow finding a way to message every admin and telling them to change their configurations, I just don't see that working effectively at all...

**Comment by mdcfe** [comment]
...through the wiki, the one place where we have instructions for server owners setting up the plugin?

I don't think this is the most pressing concern for all server owners, and if it's on the wiki they can find it or we can point them to it. This PR also doesn't change the default for any configs that don't have this option (mostly legacy Essentials configs), nor does it change the configs that already have this setting set to `0.001`.

**Comment by mdcfe** [comment]
Closing as this is an unnecessary change.

**Pull request closed without merging**
