### PR TITLE
fix wording on `disabled-commands`.

### LINKED ISSUE #5344: Make the configuration less misleading with respect to command conflicts
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

N/A

### Error log (if applicable)

N/A

### Bug description

I was uncertain whether to file this issue as a bug or a feature request. Because it is unexpected behavior, of a sort, rather than some superfluous feature, I decided to file a bug.

--------------------------------------------------------------------------------------------------------------------

Essentials is a large plugin with hordes of features, including dozens of commands. Unsurprisingly, this means Essentials' numerous commands sometimes conflict with other plugins that provide similar features. Many times, server owners operate Essentials alongside these more precise plugins when they desire finer granularity in a certain area. Command conflicts are therefore common.

Essentials, seemingly recognizing this, has long offered a feature that attempts to grant commands to the other plugin in the case of a conflict.

https://github.com/EssentialsX/Essentials/blob/1a4f63915f9797c5ec2f79554f75355a02a281ed/Essentials/src/main/resources/config.yml#L158

The above line in the configuration is the subject of this issue. It is misleading, however, for several reasons. Ultimately, this feature causes so much annoyance, that it should either be removed, or properly documented for its myriad failings.

Firstly, the conflict resolution feature is unreliable: it requires other plugins to implement `PluginIdentifiableCommand`. In the case of dynamic command registration via the command map, implementing `PluginIdentifiableCommand` is not a strict necessity. It is not enforced by Bukkit, only mentioned in the javadoc as relating to index generation. One might argue that plugin commands ought to implement this interface; however, in reality, the specification is vague, and in practice, plugins have no requirement to do this.

Secondly, it is inaccurate, because tab completion is not properly redirected in all situations. Only commands extending `PluginCommand` support tab completion redirection. This incompleteness means that commands appear to work: execution succeeds, while tab completion is missing. The result, for users and developers, is confusion and debugging.

Lastly, it is imprecise. Even if everything seemingly goes well, the command is nevertheless registered according to Bukkit under the plugin Essentials. This results in improper usage messages (https://github.com/EssentialsX/Essentials/pull/3904), curious stacktraces, and incorrect API information. An exception in another plugin can be reported as occuring while executing an Essentials command because only `Exception` is caught [here](https://github.com/EssentialsX/Essentials/blob/1a4f63915f9797c5ec2f79554f75355a02a281ed/Essentials/src/main/java/com/earth2me/essentials/Essentials.java#L738). Even were all exceptions caught, the presence of Essentials in the resulting stacktrace would only raise eyes. Besides funny-looking exceptions, Essentials' command redirection disorients uses of the API that require identifying command ownership, such as administrative utility and help plugins.

Because of the latter two reasons, it is very understandable for authors of plugins with conflicting commands to not want Essentials to redirect commands. Consider the support burden perspective. Users might claim tab completion does not work, causing authors to dig through their own code while frustrated at the lack of reproducibility. Guiding users in solving command conflicts is difficult enough without having to explain that Essentials -- the Essentials they know as a popular, reliable plugin -- was responsible for breaking another plugin's tab completion. If I knew implementing `PluginIdentifiableCommand` would generate such problems, I probably would avoid implementing it. Wouldn't you?

### Steps to reproduce

Read the configuration. Debug and test with other plugins that provide conflicting commands.

### Expected behaviour

To remedy the quagmire, the Essentials plugin should do one of the following:
- Remove this broken feature
- Stop misleading users; update the configuration comment to detail all the caveats of relying on it
- Properly support disabling commands via https://github.com/EssentialsX/Essentials/issues/3809

### Actual behaviour

Annoyance at Essentials for providing a feature so detrimental to users and unfriendly to other plugins in the ecosystem.

### PR DESCRIPTION
**Pull request by Evidentsinger14**
### Information

This PR fixes #5344 

### Details

**Proposed fix:**    

Adjusted comment in config to be a more accurate description of the current functionality of `disabled-commands`

**Environments tested:**    

OS: Windows 10

Java version:  Java 17

- [x] Most recent Paper version (1.19.4, git-Paper-527)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**    

Not really needed - just a comment adjustment.

### CODE REVIEW

**Review by pop4959 — COMMENTED** [review]
I feel like the old text here is still not that bad, which part(s) are inaccurate?
Also linking to aliases is not a bad idea to keep IMO.

**Comment by Evidentsinger14** [comment]
> which part(s) are inaccurate?

I wouldn't say it's entirely inaccurate, however slightly misleading for how the current system works. it used to show the "x command is disabled" message, but now it just completely unregisters. I can add the comment back about aliases, but it seems pointless, as it being unregistered should mean you don't have to make an alias for it.

**Comment by mdcfe** [comment]
I agree the existing wording here isn't particularly accurate. The wording is a holdover from when Essentials simply refused to do anything when a command listed here was called, but since 2.19.0 (#4026, #4108, #4399) EssentialsX has removed mappings of these aliases from the server's command map entirely.

However, the current implementation has always been a band-aid over much larger issues around usability and documentation. The following post is long but covers a lot of the use cases for `disabled-commands`, the issues of using `disabled-commands` to solve them and how both EssentialsX and server platforms could offer more effective solutions to these issues.

<details>
<summary><i>essay enclosed</i></summary>

### Incorrect assumptions around performance and permissions 

`disabled-commands` is regularly misused by server owners who don't understand how to set up permissions properly, believe it is the only way to remove commands from tab completion (usually due to other plugins or server impls breaking our perm checks), or believe it might improve performance.

In EssentialsX, unregistering commands has no meaningful performance benefit - classes are not loaded until they are needed and the presence of aliases has minimal memory impact either. Removing commands and aliases that players expect to exist can cause player confusion, as it suppresses proper feedback about permissions.

### Non-intuitive implementation 

EssentialsX still initially registers disabled commands on startup through `plugin.yml`, as this was traditionally the most reliable way to make command handover work. It also doesn't re-enable commands until restart, and doesn't actually guarantee anything about alternative commands being able to take over after our commands have been registered once.

This is something that is unlikely we can change right now, as any change to registration order could break long-standing configurations that rely on `overridden-commands` to force the EssentialsX version of commands.

### Vanilla syntax in command blocks and datapacks

Some server owners want to disable our commands as they override vanilla commands that are used extensively in command blocks and datapacks. Spigot has *always* supported routing commands back to vanilla for command blocks and datapacks through the `command-block-overrides` option in `commands.yml` - users should be pointed towards this setting, not towards interfering with command registration.

### Users replacing EssentialsX commands with vanilla implementations

Some users would rather use vanilla commands like `/give` and `/tp` in chat, not just command blocks and datapacks.

Essentials' original implementations were intended to complement and extend vanilla commands with new functionality, such as named shorthand aliases for item types and metadata. In the past, Essentials and EssentialsX's alternatives were fully compatible with vanilla syntax, but as vanilla has improved its own commands (ie inline NBT), it's clear that users want to use these versions instead of the dated syntaxes EssentialsX still offers. 

There is still value in offering our own versions of these commands, item type/metadata shorthands are useful and many users are still familiar with our syntax. Updating these commands to offer a more modern vanilla-like syntax that still maintains some enhancements would allow us to continue meeting the goals of the original project (and is frankly quite a minimal task - `/give` only needs to detect the presence of a `{` in an item name, for example).

### Alternative commands from other plugins

EssentialsX provides many commands with the same name as commands from other plugins. However, Essentials has always been pitched as a baseline for a server owner to build from, adding more specific plugins if they need more specific functionality.

To facilitate users getting their commands to be run by other plugins without any effective platform-level solution, EssentialsX actively checks the command map at runtime to find plugin commands with the same name as our aliases. If the server has decided to execute EssentialsX's command handler when another plugin has registered a command with the same name, our command handler can pass over execution to another plugin.

With this system, no plugins should have issues overriding EssentialsX commands. If they do, they haven't registered their commands properly and shouldn't expect Spigot or Paper to continue executing them in any case.

However, EssentialsX's command handover system is a band-aid. Interoperability between plugins is the goal of plugin platforms like Bukkit, and I would argue that resolving the command to execute in case of conflicts is also a concern for the server platform.

Unfortunately, Bukkit has never provided a particularly effective way for plugin developers or server owners to specify who should have priority over the handling of a command. Plugin developers have to rely on load/command registration order, while the only option built-in for server owners is the `aliases` section of `commands.yml`, which doesn't seem to have a clear goal as it serves as both a remapping system and a primitive macro/scripting system, and mostly fails at both of those tasks due to poor tab completion and very limited script facilities. Since it mostly seems to be tooled towards simple command macros, it has never routed tab completions to plugins, meaning users often reach to disable commands instead of actually rerouting them properly.

I would welcome a system like Sponge's command mapping config. On Sponge, users are able to configure which plugin command is invoked, routing both command execution and tab completion to the selected plugin. This could be adapted to Spigot/Paper without making huge changes - an extra map in `commands.yml` similar to Sponge, or a special case for single-command aliases, which would solve issues around tab completion and could even allow commands to be routed back to vanilla if users aren't satisfied by plugin implementations.

</details>

---

I'm still wary of actively recommending this option, and would honestly be in favour of removing `disabled-commands` entirely, but I recognise that this is pretty much a necessity as long as these issues are still unsolved.

In the meantime, we should advise users about platform-level options like `command-block-overrides` in addition to clarifying the current behaviour.

**Comment by A248** [comment]
I would like to suggest a minor point regarding the _essay_ above. While I don't want to derail the discussion of this PR, I believe it's nevertheless pertinent to mention.

> With this system, no plugins should have issues overriding EssentialsX commands. If they do, they haven't registered their commands properly and shouldn't expect Spigot or Paper to continue executing them in any case.

This isn't true. I maintain a punishment plugin, known as LibertyBans, which registers `/ban` and `/kick`. However, I consistently have users report conflicts with EssentialsX commands. In fact, it has become the number one reason that users ask for support. The command conflicts happen despite that the LibertyBans plugin registers commands in an entirely supported fashion. 

 Of course, I have to agree that a better solution coming from the server API is desirable. The commands.yml is entirely lackluster, and the presence of command conflicts creates arbitrary behavior. Having the chosen command depend upon arbitrary plugin load order is terrible for system stability.

**Pull request closed without merging**
