### PR TITLE
Exempt offline players in /baltop

### LINKED ISSUE #3100: Exempt players from balancetop, even if offline
### Feature request

**Feature description**
Add an entry in the UUID.yml userdata file to show if a player is exempt from the balancetop, such as `baltopexempt: true`. Example data file: https://gist.github.com/untuned/7051f673825dc61de9ae6f4c0444ba9e

**How the feature is useful**
If server owners don't want to show specific players having exorbitant amounts of economy, they can be hidden from the balancetop.

Based on issue #3004

### LINKED ISSUE #3540: essentials.balancetop.exclude doesn't work when the player is offline
### Information

**Full output of `/ess version`**:

```
26.07 05:56:19 [Server] INFO Server wersja: 1.15.2-R0.1-SNAPSHOT git-Paper-380 (MC: 1.15.2)
26.07 05:56:19 [Server] INFO EssentialsX wersja: 2.18.0.0
26.07 05:56:19 [Server] INFO PlaceholderAPI wersja: 2.10.6
26.07 05:56:19 [Server] INFO LuckPerms wersja: 5.1.26
26.07 05:56:19 [Server] INFO Vault wersja: 1.7.3-b131
26.07 05:56:19 [Server] INFO EssentialsXChat wersja: 2.18.0.0
26.07 05:56:19 [Server] INFO EssentialsXSpawn wersja: 2.18.0.0
```

**Server log**: 
Not relevant

**EssentialsX config**: 
https://pastebin.com/X4WEinAU

### Details

**Description**  
Although a user has essentials.balancetop.exclude, is still visible in /baltop view. I think that it tries to check the permission of offline player and can't get it. If this player is online sometimes is not visible and visible if offline.
--

**Steps to reproduce**  
Add essentials.balancetop.exclude and go offline with this user.

**Expected behavior**  
User should never be visible on baltop view. Maybe some config option instead of permission if it is not available offline.

**Screenshots**

### PR DESCRIPTION
**Pull request by ghost**
Just as the title implies, it allows the /baltop command to exclude offline players with the `essentials.balancetop.exclude` perm node. Because permission managers are finicky (at best) with offline access, a new field has been added in the `user.yml`: `balTopExempt` which stores a boolean indicating if the exemption node is held by the offline player or not. This value is updated everytime a user logs in.

Closes #3100
Closes #3540

### CODE REVIEW

**Comment by pop4959** [comment]
Looks good to me.

I believe we're also still planning to look into whether the offline permission checks can be improved, as LuckPerms supposedly supports it, however Essentials' permission system doesn't seem to be leveraging it correctly if that's the case.

Have you looked into that at all? It would be far more ideal to fix the root issue, as there are plenty of other areas where offline mode permission checks could be used. Baltop is just the most notorious.

I think we should investigate still to make sure no better solution exists before merging.

**Comment by ghost** [comment]
> Looks good to me.
> 
> I believe we're also still planning to look into whether the offline permission checks can be improved, as LuckPerms supposedly supports it, however Essentials' permission system doesn't seem to be leveraging it correctly if that's the case.
> 
> Have you looked into that at all? It would be far more ideal to fix the root issue, as there are plenty of other areas where offline mode permission checks could be used. Baltop is just the most notorious.
> 
> I think we should investigate still to make sure no better solution exists before merging.

Hi,

Yes you're correct LuckPerms does support offline perm fetching. Regarding other perms plugins, (like GroupManager) they aren't guaranteed to support offline perms. So one way to address this problem is create a future-proof way of checking for this discrepancy. I'm thinking I can modify the PR to make changes to the parent perms handler interface:`IPermissionHandler`, I can add a method called `supportsOfflineFetching()` that returns a boolean if the provider perms implementation can do the offline fetching. It can then be modified for each implementation in the future if any of the perms implementations change. That way we can make dynamic runtime decisions in the essentials-centric code on what to do if perms provider supports offline perms and what to do if it doesn't.

Example:

```java
// User.java
 private boolean isAuthorizedCheck(final String node) {
        if (base instanceof OfflinePlayer && ess.getPermissionsHandler().supportsOfflineFetching()) {
            // Do fetching like normal.
        } else {
           // Doesn't support offline perm fetching, use a fallback
        }
      ...
 }
```

Thoughts?

**Comment by ghost** [comment]
I pushed a preliminary implementation of offline LP perm support and it seems to be working as expected. So I'm probably going to expand on that.

**Comment by pop4959** [comment]
Can you do this in a separate branch/PR since it is an independent addition from the baltop exemption config?

**Comment by Bloodlex** [comment]
Have you been able to solve this issue? :)

**Comment by ghost** [comment]
> Have you been able to solve this issue? :)

A PR wouldn’t be open if I couldn’t solve it :P

**Comment by pop4959** [comment]
By the way, sorry for the long wait. We will get around to reviewing and merging PRs sometime, but it seems like most people (including myself) have been a bit busy lately. It'll happen soon enough (and this is an issue that has been present for years, so what does it matter if it takes a little longer 😛).

**Review by Octol1ttle — APPROVED** [review]

**Comment by Chew** [comment]
Author is gone. Unmergable PR.

**Pull request closed without merging**
