### PR TITLE
Fix home tab completions

### LINKED ISSUE #1337: [Suggestion] Allow tab-completion of home points also for players with 'essentials.home.others'
I don't know if this is intended or not, but on my server (using EssentialsX 2.0.1-b491), a player can't tab-complete his home points as soon as he is granted the 'essentials.home.others' permission, and the server will suggest player names instead.

I get that this might be helpful when using the `/home <player>:<home>` syntax, but I would find it more useful to still tab-complete home points instead of player names (or maybe do both as a compromise), since players with 'essentials.home.others' will still most frequently use the /home command to target their own home points.

### PR DESCRIPTION
**Pull request by pop4959**
Fixes #1337 😎 

This PR fixes tab completions for all of the home commands in Essentials. Prior to this PR, the behavior is approximately as follows:

- `/sethome` has no implementation for completions, and so it provides player names, which isn't very useful, and in my opinion can cause more harm than good by confusing users.
- `/home` and `/delhome` fail to provide valid completions when a user has the `essentials.home.others` permission. The argument syntax is `[player:]<name>` but it tries to complete it as `<player> <name>`. Not only does it not show you suggestions for your own homes, but it proceeds to show you invalid suggestions!

This PR provides completions that accurately reflect the syntax and real behavior of the command, including suggesting homes for player names that are partially matched. It will provide suggestions for all of your own homes, as well as providing suggestions based on how far along you are in the command (players if you haven't specified `:` yet, otherwise a specific player's homes).

Below are some tests to show the new suggestions working.

User without the `others` and `bed` permissions:

image
image
image

User with both mentioned permissions:

image
image
image
image
image
image

### CODE REVIEW

**Comment by ghost** [comment]
This is something Essentials has been needing for a while. Nice to see it implemented :^)

**Review by JRoy — APPROVED** [review]
This has annoyed me for so damn long, glad to see someone finally taking the time to it fixed.

Looked over the code and looks good!

**Review by darbyjack — APPROVED** [review]
I will be able to benefit from this too. It's been a pain and glad to see it's been worked on.

**Review by triagonal — APPROVED** [review]
**extremely** cute

**Review by mdcfe — APPROVED** [review]
10/10 would complete `/home` again

**Pull request merged**
