### PR TITLE
Add discord roles blacklist and aliases for chat format

### PR DESCRIPTION
**Pull request by x86-39**
### Information

This PR partially closes https://github.com/EssentialsX/Essentials/discussions/5155
### Details

**Proposed feature:**  
Add options to only select certain Discord roles and to add aliases for roles.

This is parallel to the `DiscordChatChannelRoleAliases` and `DiscordChatChannelRolesSelection` options in DiscordSRV.

This can be used to ignore certain roles, by only selecting roles relating to Minecraft to be processed by the plugin. 

The aliases allow for mapping names in Discord to in Minecraft. For example "Admins" can be mapped to "Admin". This can also be used to hardcode which colour a role should be in Minecraft by setting the alias to include a colour code for example: "§9Admin"

**Environments tested:**    

OS: Fedora 36

Java version:  `17.0.5`

- [ ] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [x] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8
Don't see how this could differ on other server versions.

**Demonstration:**  

```yaml
# List of roles which are used for the top role placeholders. If this is empty, all roles will be allowed.
discord-roles-selection:
  - "Admins"
  - "Members"

# Aliases for Discord roles before they are sent to Minecraft.
discord-roles-aliases:
  Admins: "§9Admin"
  Members: "Member"
```
The `Founder` role gets ignored and the `Admins` role gets translated to `§9Admin`
image
image

### CODE REVIEW

**Review by JRoy — CHANGES_REQUESTED** [review]
Both these features are fine, just a few things;

* `discord-roles-selection` should be made into a blacklist rather than a whitelist, be renamed to `discord-role-blacklist`, and the config should have the examples commented out (like how `world-aliases` are in the main essentials config).

* `discord-roles-aliases` should support both discord role names and ids and have their examples commented out as well.

**Comment by x86-39** [comment]
I feel like it being a whitelist is still desired in many cases, perhaps an option to turn the whitelist into a blacklist? This is how DiscordSRV does it too.

Will add it to support IDs and comment it out in the config tomorrow

**Comment by JRoy** [comment]
> I feel like it being a whitelist is still desired in many cases, perhaps an option to turn the whitelist into a blacklist? This is how DiscordSRV does it too.

I think a majority of users will only have a couple of roles they don't want used as top role, such as a default role, rather than a bunch of unwanted top roles

**Comment by x86-39** [comment]
Maybe a blacklist by default (renaming it to blacklist too) with an option for it to be a whitelist?

**Comment by JRoy** [comment]
> Maybe a blacklist by default (renaming it to blacklist too) with an option for it to be a whitelist?

I think that would become confusing, do you have an example of a common use case for a whitelist would be better over a blacklist?

**Comment by x86-39** [comment]
We have staff ranks inside Minecraft which are roles present in Discord, but the Discord has more roles than that. When messages go to the Minecraft server, we only care about those staff roles going to Minecraft. Having a whitelist of just the few staff ranks is a lot easier then.

**Comment by x86-39** [comment]
@JRoy Any input on this? If you agree with the whitelist suggestion I can implement it and finalise this PR

**Comment by JRoy** [comment]
> @JRoy Any input on this? If you agree with the whitelist suggestion I can implement it and finalise this PR

Sorry, though I had replied, still convinced that a blacklist would be more useful by default. You can add a boolean config option `invert-discord-role-blacklist` which is not in the config by default (and has false as its default value) in order to satisfy your usecase.

**Comment by x86-39** [comment]
Yeah a blacklist by default is fine, I'll add a boolean thank you. Will modify the PR when I have the chance

**Comment by x86-39** [comment]
Hey @JRoy, apologies I completely forgot about this pull request.

I just made the requested changes and updated the branch. 

I also updated the other pull requests I have open:
  https://github.com/EssentialsX/Essentials/pull/5159
  https://github.com/EssentialsX/Essentials/pull/5158

**Review by JRoy — DISMISSED** [review]

**Review by JRoy — APPROVED** [review]

**Pull request merged**
