### PR TITLE
Catch UnsupportedOperationException on server list ping (fixes #857)

### LINKED ISSUE #857: Problem with ServerListPingEvent
Hi, i'm having this problem since the essentialsx has been updated to hide the players from the ping panel, i'm using bungeecord with the latest version of spigot and bungee, here its my error:

http://pastebin.com/9vUMTgZG

### PR DESCRIPTION
**Pull request by mdcfe**
Catch the UnsupportedOperationException on a server list ping, in case the server software doesn't correctly implement ServerListPingEvent#iterator(). This should fix #857.

### CODE REVIEW

**Comment by SupaHam** [comment]
Long story short, UnsupportedOperationException catch is implemented because some server software writers are incompetent, possibly even including whoever made the ServerListPingEvent in the first place. See [Thermos](https://github.com/CyberdyneCC/Thermos/blob/master/patches/net/minecraft/server/network/NetHandlerStatusServer.java.patch#L52).

**Comment by mdcfe** [comment]
I almost feel like closing this without having the PR merged so that other plugin/server software devs will notice that they haven't used/implemented the API properly.

**Comment by drtshock** [comment]
Why not print out an annoying error still then and say that it's the fault of the server implementation instead of silently catching?

**Comment by mdcfe** [comment]
@drtshock It could either be the fault of a server implementation _or_ a plugin. I may try scanning the stack trace though, that may help.

**Comment by mdcfe** [comment]
I've added a check for whether the server is running a version of Cauldron (Cauldron, KCauldron, Thermos etc.).

**Comment by mdcfe** [comment]
I'm not sure how feasible it would be to detect plugins which call events from the stack traces - would it be worth keeping a list of plugins with known issues instead?

**Comment by drtshock** [comment]
No, that's just tedious. At this point, I don't really see anything else holding this back?

**Comment by mdcfe** [comment]
I haven't been able to look into this yet, but I'm not sure whether the event call appears in the stack trace from the exception.

**Comment by mdcfe** [comment]
I don't think that it would be possible to detect the event caller from the stack trace, since the event caller is not part of the UnsupportedOperationException's stack trace. The only way to even show a stack trace with the event caller relies on exceptions not being caught and Bukkit throwing an EventException.

**Comment by Time6628** [comment]
As far as I know, Cauldron/KCauldron/Thermos has never fully implemented ServerListPingEvent. I am not sure why, but I could probably fix this in Thermos when I get a chance.

**Comment by mdcfe** [comment]
@Time6628 To be fair, Bukkit doesn't provide an implementation and CraftBukkit didn't implement it until Spigot 1.8.

Edit: that isn't to say that Thermos _shouldn't_ implement the iterator; I'll look into a way to detect if the server is running Minecraft 1.7.x or earlier.

**Comment by vemacs** [comment]
I'm going to do the try/catch later today, but pls fix the Thermos implementation @robotia

**Comment by sameer** [comment]
That's the plan for this Thursday

**Comment by vemacs** [comment]
https://github.com/drtshock/Essentials/commit/e0a578d06ce8189d3c06a5de290caf23589f8f4d

Thought that logging once would be a better idea.

**Comment by mdcfe** [comment]
@vemacs The problem is that logging once is easy to miss, and ideally we want people to notice the message and follow the advice (even if that does spam their logs). Also, this currently doesn't account for the fact that non-Thermos Bukkit 1.7 implementations probably won't support the `iterator` either.

**Pull request closed without merging**
