### PR TITLE
Update messages.properties

### PR DESCRIPTION
**Pull request by leonardo-dgs**

### CODE REVIEW

**Comment by mdcfe** [comment]
To delete the mails read?

**Comment by leonardo-dgs** [comment]
I had seen that the string was "mailClear" that does not mark mail as read, but delete it, furthermore
 the string is duplicated

**Comment by mdcfe** [comment]
"To clear your mail..." would be much clearer than "to delete your mails read".

**Review by mdcfe — APPROVED** [review]

**Comment by SupaHam** [comment]
Thank you for your contribution! :)

**Pull request merged**
