### PR TITLE
Add toggle for keepinv permission

### LINKED ISSUE #2692: Toggle Keepinv
### Feature request

**Feature description**
A command to toggle keepinv for players who have the essentials.keepinv perm.

**How the feature is useful**
It allows players who have the essentials.keepinv perm to remove curse of binding items.

### PR DESCRIPTION
**Pull request by ghost**
Closes https://github.com/EssentialsX/Essentials/issues/2692

### CODE REVIEW

**Review by JRoy — CHANGES_REQUESTED** [review]
Not a fan of this. There's no way I can see to keep current behavior and add a toggle at the same time. 

Maybe you could default keep inventory to on for people with essentials.keepinv (Have the userdata option be true by default). Then you could have a `/togglekeepinv` command which toggles the userdata option. In `UserData#isKeepInvEnabled` you would check against both the `essentials.keepinv` permission and the userdata option.

**Comment by ghost** [comment]
> Not a fan of this. There's no way I can see to keep current behavior and add a toggle at the same time.
> 
> Maybe you could default keep inventory to on for people with essentials.keepinv (Have the userdata option be true by default). Then you could have a `/togglekeepinv` command which toggles the userdata option. In `UserData#isKeepInvEnabled` you would check against both the `essentials.keepinv` permission and the userdata option.

My original train of thought was that the current behavior was a little strange because you would want / not want this functionality on, though your suggestion seems like a good idea and I'll check it in.

**Comment by latiku** [comment]
Latest two pushes implement @Jroy's suggested functionality

**Review by ghost — COMMENTED** [review]
latest three commits implement @JRoy's suggested functionality, video: https://streamable.com/5l8h33

**Review by JRoy — APPROVED** [review]

**Comment by pop4959** [comment]
Is there a way to turn off keep inventory for all users? For example, when server admins may have allowed players to toggle it, but want to take it away.

**Comment by ghost** [comment]
> Is there a way to turn off keep inventory for all users? For example, when server admins may have allowed players to toggle it, but want to take it away.

no

**Comment by mdcfe** [comment]
This no longer addresses #2692 - if you have `essentials.keepinv`, you can't toggle keepinventory off, which is what was requested.

I'm not a fan of trying to work this behaviour into EssentialsX around the existing `essentials.keepinv` permission as it's not predictable for end users. Users won't expect the behaviour of the permission to change, but they'll also expect the toggle command to always take precedence, which makes keeping the current keepinv permission and adding a toggle mutually incompatible.

You can already achieve the effect of a toggle in a separate plugin either by using a permission attachment to enable `essentials.keepinv` or by handling the death event directly. For now, that's a preferable solution as servers can implement this in whatever fashion they want, without having two parallel conflicting states controlling the same behaviour.

**Comment by pop4959** [comment]
Wasn't keepinv policies already added for this as well?

**Comment by Chew** [comment]
Author is gone. Unmergable PR.

**Pull request closed without merging**
