### PR TITLE
Make {player} referencing powertools activate only when the user has powertools enabled

### PR DESCRIPTION
**Pull request by ghost**
Previously powertools that include a reference to {player} would still activate when the user had powertools disabled. This PR fixes that.

### CODE REVIEW

**Review by LaxWasHere — APPROVED** [review]

**Comment by SupaHam** [comment]
Would it not be more fit if this check was placed before the forloop and just terminate there?

**Comment by ghost** [comment]
Thought that was what I had in the first place. Must have had a giant brainfart and didn't realize since this still works as expected.

**Comment by SupaHam** [comment]
Would it be wiser to place the check inside the method itself in case it is called from other areas due to other forms of PVP?

**Comment by ghost** [comment]
It is never called anywhere else.

**Comment by SupaHam** [comment]
I meant in the future. I say this because of the recent 13fbd3112

**Comment by ghost** [comment]
{player} is meant to reference the player you are looking at and click on. It would be useless in my opinion to make it work for the player you shoot.

**Comment by SupaHam** [comment]
Fair enough. Thanks for your contribution! <3 :)

**Pull request merged**
