### PR TITLE
Add ability to use texture url in /skull

### LINKED ISSUE #3804: /skull with custom skin
### Feature request

**Feature description:**  
Ability to provide a custom skin when using /skull.
When you want a skull with a custom skin (for instance [here](https://minecraft-heads.com/custom-heads/decoration/33561-presents)), you have to be op to execute the provided commands, since these commands are too long to be typed in chat. Since the provided give command is full of stuff that are common for all skull, it would be great to have a shorter way to do it like `/skull 6f5c433908732b512f68461c14ef020bb2f55d96a61cd1d45ea1e7ea899f1a6b` (would give the skull at the link provided above)

*Possible inputs*:
* The argument value I suggested above represent the end part of the skin URL (64 char long), hosted on textures.minecraft.net. This is the only thing that vary between custom skulls.
* Another argument value what would be possible is the base64 (180 char long) value that contains the URL in some JSON stuff. Some skull repository may not provide the base URL, but only the base64, thus the suggestion to also accept it.

**How the feature is useful:** 
It would be useful for players/owners/map makers to have an easy way to add custom skulls in their decoration (or whatever reason) in an easier way the full `/give` commands. This would reduce the need to ask operators for the give of the skull, like the current `/skull <player>` command already does for player skulls.
The improved `/skull` command can be a light and fast solution compared to the plugin advertised on Minecraft Heads website.

### PR DESCRIPTION
**Pull request by TheLukeGuy**
### Information

This PR closes #3804.

### Details

**Proposed feature:**

This lets users provide custom skins when using the `/skull` command by specifying a skin identifier instead of a username. This feature is only available on specific versions of Spigot 1.18.1 and above because it uses the [new player profile API](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/04c7e13cf0fb199cce3db3ada646b4bd61a57580). On older versions, only a username can be used.

The `/skull` command now supports the following values in the first argument:

- A username, like before
- The 64-character-long identifier of a custom skin (the last part of the skin URL)
- The 180-character-long base64 value of a custom skin

The first 7 characters of the skin identifier will be used for the skull's display name and the success message. An error message will be sent if a base64 value isn't a valid skin object.

**Environments tested:**

OS: Windows 11

Java version: openjdk version "17.0.1" 2021-10-19

- [x] Most recent Paper version (1.19.2, git-Paper-189)
- [ ] ~~CraftBukkit/Spigot/Paper 1.12.2~~
- [ ] ~~CraftBukkit 1.8.8~~

**Demonstration:**

I used [this head](https://minecraft-heads.com/custom-heads/plants/50465-pumpkin) as an example. The screenshot below was taken immediately after running the following commands (and switching my hotbar slot in between):

```
/skull 1c1df3b095e6a774e26852901db234003979c7a75ce35d8d269bb3651e09cfa2
/skull eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWMxZGYzYjA5NWU2YTc3NGUyNjg1MjkwMWRiMjM0MDAzOTc5YzdhNzVjZTM1ZDhkMjY5YmIzNjUxZTA5Y2ZhMiJ9fX0=
```

Demonstration

### CODE REVIEW

**Review by mdcfe — COMMENTED** [review]
Thanks for the PR! Overall this looks good, but it would be great if you could add an additional command usage message to indicate that texture URL hashes are accepted.

**Comment by TheLukeGuy** [comment]
Sounds good! Does this look alright? I'm not sure I like the wording of it too much, but I can't think of any better way to describe it.

/skull help message

**Review by mdcfe — DISMISSED** [review]
Apologies for the delay in re-reviewing this! The new usage message looks good.

This PR will need updating and conflicts resolving before it can be merged. If you get a chance to do this, it would be great, but if not we can resolve this before we merge it.

**Comment by TheLukeGuy** [comment]
All good, sure! I'll get the conflicts resolved as soon as possible.

**Review by JRoy — APPROVED** [review]

**Review by JRoy — APPROVED** [review]

**Pull request merged**
