### PR TITLE
[Feature] Added new property 'socialSpyFormat' (re-submission)

### PR DESCRIPTION
**Pull request by Azewilous**
This feature allows the user to alter the format in which a 'social Spy' messages is seen.

### CODE REVIEW

**Review by LaxWasHere — APPROVED** [review]

**Comment by mibby** [comment]
@Azewilous Would it be possible to also allow formatting mail output in socialspy? As mail messages displayed in socialspy are sent white and can't be changed as far as I can tell.

**Comment by Azewilous** [comment]
@mibby I will look into it next week.

**Comment by mibby** [comment]
Bump. ^^

**Comment by SupaHam** [comment]
Merged. Thank you. :)

**Pull request closed without merging**
