### PR TITLE
Less lag

### PR DESCRIPTION
**Pull request by pisaiah**
Less aliases = Less lag

removed some aliases that start with an e (example: /ekick)

### CODE REVIEW

**Comment by Kakifrucht** [comment]
Erm, why?
Firstly I really don't think that aliases cause lag, secondly the reason they exist in the first place is to access essentials commands even if overriden.

**Comment by pisaiah** [comment]
More commands = More lag.

And you can still access essentials commands by prefixing them with /essentials: (example: /essentials:kick)

The aliases do cause lag because they increase the CommandMap (hashmap) size

**Comment by FlippantCactus** [comment]
Wat.

**Comment by konsolas** [comment]
IsaiahPatton what the ovh are you talking about.

**Comment by AshourAziz** [comment]
Less lag I heard? Please merge...

**Comment by AshourAziz** [comment]
:thumbsup:

**Comment by Kakifrucht** [comment]
Please paste the source that tells you that registering more commands "causes lag".
Commands are in a map, putting more in there doesn't cause more iterations.

While you are right that you can prefix the commands with /essentials: instead of just e, there is still compatibility with other plugins that may access essentials commands this way.

I don't think that there is any reason to merge this.

-1

**Comment by FlippantCactus** [comment]
@Kakifrucht we'll find out. Such lag so might as well remove it here: https://github.com/IsaiahPatton/Essentials/pull/1

**Comment by vemacs** [comment]
Computers are fast

**Pull request closed without merging**
