### PR TITLE
[Fix] General refactoring

### PR DESCRIPTION
**Pull request by ShadowRanger**
Performed some refactoring to the source code. Considering the plugin is compiled under Java 7, there were a few changes that could be made such as using the diamond operator when instantiating collections. Additionally, I made a few minor changes to simply some return statements and expressions as well as removed redundant field initialization. Let me know if there are any problems with any of the changes I have made or if you do not agree with any of them as I would be happy to modify the pull request.

### CODE REVIEW

**Comment by ShadowRanger** [comment]
Any updates on this?

**Comment by SupaHam** [comment]
Regardless of the fact this branch needs updating. I personally don't think this commit is necessary, as it provides no additional functionality. You can update java 6 code as you go.

**Comment by ShadowRanger** [comment]
I just thought that it would help to update the code to take advantage of Java 7 and to help keep the code clean and up-to-date with the latest Java conventions. I spoke to drtshock a few weeks ago and he seemed happy with it. It was late at the time and he said he would properly have a look at the pull request the next day.

**Comment by drtshock** [comment]
I don't see the point to this commit, and it isn't updated.

**Pull request closed without merging**
