### PR TITLE
Fix tablist name getting reset after AFK status change

### LINKED ISSUE #3606: When player backed from AFK mode,Essentials don't displayer player's display name in TAB list.
### Information

**Full output of `/ess version`**:

```
[20:32:15] [Server thread/INFO]: Server 版本: 1.16.2-R0.1-SNAPSHOT git-Spigot-379750e-2e178b0 (MC: 1.16.2)
[20:32:15] [Server thread/INFO]: EssentialsX 版本n: 2.18.0.0
[20:32:15] [Server thread/INFO]: LuckPerms 版本n: 5.1.93
[20:32:15] [Server thread/INFO]: PlaceholderAPI 版本n: 2.10.9
[20:32:15] [Server thread/INFO]: Vault 版本n: 1.7.3-b131
[20:32:15] [Server thread/INFO]: EssentialsXProtect 版本n: 2.18.0.0
[20:32:15] [Server thread/INFO]: EssentialsXChat 版本n: 2.18.0.0
[20:32:15] [Server thread/INFO]: EssentialsXAntiBuild 版本n: 2.18.0.0
[20:32:15] [Server thread/INFO]: EssentialsXSpawn 版本n: 2.18.0.0
```

**Server log**: no log

**EssentialsX config**: https://gist.github.com/Rothes/098091f21b93ffeb90f0bae3e4d020a0

### Details

**Description**  
When player backed from AFK mode,Essentials don't show player's display name in TAB list. It will show player's name. I'm using another else nick plugin.It setPlayerListName and displayname when player joined the game, or player run /nick command.

**Steps to reproduce**  
1.Let a player who already have displayname run /afk command or wait for auto-afk
2.Check the Tab list, you find it will display [AFK] + the displayname of player.
3.Let the player out of afk mode
4.Check the Tab list then you find it won't display the displayname of player.

**Expected behavior**  
display the displayname of player.

**Screenshots**

### PR DESCRIPTION
**Pull request by JRoy**
Fixes #3606

### CODE REVIEW

**Review by mdcfe — COMMENTED** [review]
are you serious

**Review by mdcfe — APPROVED** [review]

**Comment by JRoy** [comment]
yes smile

**Comment by pop4959** [comment]
@md678685 JRoy: master of randomly removing lines of code that we won't notice are missing while "refactoring" the code base 😆

**Review by pop4959 — APPROVED** [review]

**Comment by Chew** [comment]
Quite bigbrain actually, make a giant pr that introduces bugs, then make prs to fix them. ezpz

**Comment by JRoy** [comment]
Stats Padding EZ Clap

**Comment by Rothes** [comment]
is it fixed now?

**Comment by JRoy** [comment]
yes

**Comment by Rothes** [comment]
> yes

hmm but it still not work for my server now
version 2.18.1.31
should I repost a issue?

**Pull request merged**
