### PR TITLE
Add events for ban, ipban and extend mute event

### LINKED ISSUE #2100: Events API [question]
How can I make so my plugin can send an event to my data-base when an admin mutes/kicks or bans a player?Its it even possible to do something like that using essentials api?

### PR DESCRIPTION
**Pull request by js6pak**
Properly resolves #2100
I'm still very open to name suggestions _(i really don't know how to name these events)_

### CODE REVIEW

**Review by pop4959 — DISMISSED** [review]
Needs to resolve merge conflicts.

**Comment by pop4959** [comment]
In addition to the comment above, can you please make a PR for each of these individually? This will help reviewers evaluate each one without having to read through everything else.

**Comment by js6pak** [comment]
Somehow I forgot about this but I merged it now, can you reopen? And I don't think its needed to split this into multiple PRs, basically they all are about one thing.

**Comment by pop4959** [comment]
@js6pak Thanks. I understand that it is a bit of work for you to redo this at this point, so it's fine, but try to keep this in mind next time you make a PR. Smaller more concise diffs will help reviewers get through it faster. Also, a problem with one change in the PR will not block another change. As is, we're going to have to either accept or deny, merge or revert, all of the changes in this PR if one has a problem. Not that it's *necessarily* a big issue for this PR, due to how closely knit the changes are. Just a word of advice and something to consider.

**Comment by mdcfe** [comment]
Apologies for the slow response to this PR - been caught up in other stuff lately.

It's not entirely clear to me what the new tempmute and tempban events represent compared to the existing mute/ban events - could you elaborate on this (and ideally add a Javadoc comment on the classes)?

**Comment by js6pak** [comment]
> It's not entirely clear to me what the new tempmute and tempban events represent compared to the existing mute/ban events - could you elaborate on this (and ideally add a Javadoc comment on the classes)?

Currently there are no ban/ipban events (and mute event was missing something but I can't remember what exactly now). This PR just adds them.

**Comment by pop4959** [comment]
Closing because it seems this PR has gone stale. I also don't really see any comprehensive argument for adding them, since as MD mentioned in the other issue plugins can easily just be listening in to commands as well.

**Pull request closed without merging**
