### PR TITLE
Fixed honey bottle condense bug #3760

### LINKED ISSUE #3760: Condense on honey bottles doesn't let you keep the glass bottles
### Information

**Full output of `/ess version`:**
```
>.... [16:47:30 INFO]: Server version: 1.16.3-R0.1-SNAPSHOT git-Tuinity-"de1983b" (MC: 1.16.3)
>.... [16:47:30 INFO]: EssentialsX version: 2.18.1.32
>.... [16:47:30 INFO]: PlaceholderAPI version: 2.10.9
>.... [16:47:30 INFO]: LuckPerms version: 5.2.23
>.... [16:47:30 INFO]: Vault version: 1.7.3-b131
>.... [16:47:30 INFO]: EssentialsXChat version: 2.18.1.32
>.... [16:47:30 INFO]: EssentialsXSpawn version: 2.18.1.32
>.... [16:47:30 INFO]: You are running an unsupported server version!
```

### Details

**Description:**  
When using /condense on honey bottles to create honey blocks you get the honey blocks but it consumes the glass bottles which is different compared to vanilla behavior. Extremely minor, but a player made me aware of this so I figured I'd mention it (sorry)

**Steps to reproduce:**  
Have bottles in your hand and do /condense honey_bottle.

**Expected behavior:**  
You get the honey blocks but no bottles are kept.

### PR DESCRIPTION
**Pull request by justinmtech**
https://github.com/EssentialsX/Essentials/issues/3760

### Information

This PR fixes #3760. 

### Details

**Proposed fix:**    

 Checks if the result of the condensation is a honey block, and if it is, adds a glass bottle to their inventory based on the input amount. This is the easiest way to fix it to me, and it seems reasonable since this is the only recipe to my knowledge that functions like this.

**Environments tested:**    

OS: Windows 10

Java version:  17.0.1

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [x] Spigot 1.14.4
- [x] Spigot 1.12.2
- [x] CraftBukkit/Spigot 1.8.8

**Demonstration:**    

Screenshots (before/after command):
https://imgur.com/a/bgUHbF0

Plugin Download: [https://www.dropbox.com/s/yfow8l9m7b8ba3v/EssentialsX-2.19.3-dev%2B6-739600e-honey-bottle-fix.jar?dl=0](url)

### CODE REVIEW

**Comment by pop4959** [comment]
It's a workaround, but I think this might be the best way to fix this for now. Though I doubt that this code is safe on versions below 1.15, you should add a version check to the condition and test on < 1.15.

**Comment by justinmtech** [comment]
I tested on other versions and added the version check condition.

**Review by pop4959 — APPROVED** [review]
LGTM

**Review by JRoy — CHANGES_REQUESTED** [review]
Few things;

You cannot just add the items to the User's inventory, you need to make them part of the `Trade` output.

Also, I'd rather a separate method be made so future deviations can be added easier at another time.

**Comment by justinmtech** [comment]
> Few things;
> 
> You cannot just add the items to the User's inventory, you need to make them part of the `Trade` output.
> 
> Also, I'd rather a separate method be made so future deviations can be added easier at another time.

Will do! I'm new around here so I'm still figuring out the proper way to do stuff like that.

**Comment by mdcfe** [comment]
On Paper 1.18.2 (build 264), I can't condense honey bottles into blocks at all. This is likely due to a change in how the recipe API works on modern versions. In order for this to be merged, we would need to guarantee some sort of consistent behaviour across versions.

**Comment by dahbawz** [comment]
Status? Cause this is still not fixed.

**Comment by JRoy** [comment]
Closing as this has been abandoned, I may just do this myself later.

**Pull request closed without merging**
