### PR TITLE
Avoid using reflection for things SnakeYAML supports directly now

### LINKED ISSUE #1631: Latest changes in spigot (snakeyaml 1.19) break EssentialsX
Spigot: latest build Spigot-95dd097-c3047a5
EssentialsX: latest jenkins build #541

----------------------------------------------------------------------------------------

Alter last rebuild of spigot EssentialsX produces this exception:

> [11:02:48] [Craft Scheduler Thread - 1/WARN]: [Essentials] Plugin Essentials v2.0.1-bSNAPSHOT generated an exception while executing task 10
> org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for tag:yaml.org,2002:com.earth2me.essentials.settings.Spawns; exception=java.lang.NoSuchFieldException: typeDefinitions
>  in 'reader', line 1, column 1:
>     spawns:
>     ^
> 
>         at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:313) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at org.yaml.snakeyaml.Yaml.load(Yaml.java:467) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:41) ~[?:?]
>         at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:33) ~[?:?]
>         at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
> Caused by: org.yaml.snakeyaml.error.YAMLException: java.lang.NoSuchFieldException: typeDefinitions
>         at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.constructJavaBean2ndStep(BukkitConstructor.java:231) ~[?:?]
>         at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:217) ~[?:?]
>         at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         ... 13 more
> Caused by: java.lang.NoSuchFieldException: typeDefinitions
>         at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_152]
>         at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.constructJavaBean2ndStep(BukkitConstructor.java:224) ~[?:?]
>         at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:217) ~[?:?]
>         at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308) ~[spigot-1.12.2.jar:git-Spigot-95dd097-c3047a5]
>         ... 13 more

When i rollback to previous spigot build (Spigot-5695bca-53fccdf) everything works fine.

### PR DESCRIPTION
**Pull request by stephan-gh**
Fixes #1631 properly.

e7ebc94a9e29e3c4dca6a1d45647fbbde517f4ce added a workaround to the SnakeYAML constructor to avoid errors when unknown properties are used in the storage files. Back then, it was necessary to copy the method to catch the exception thrown when an unknown property was encountered.

However, SnakeYAML 1.12 (included in Spigot 1.6.2+) added a method to ignore missing properties without overriding parts of the SnakeYAML implementation.

Delete the old workaround and make use of `PropertyUtils.setSkipMissingProperties(true)` to achieve the same effect.

### CODE REVIEW

**Comment by mibby** [comment]
Edit: Nevermind, I'm an idiot and compiled the wrong branch. Confirmed working. :)

**Comment by Kakifrucht** [comment]
Unrelated to previous comment, how about backwards compatibility?
This pull wouldn't be compatible with previous versions would it?

**Comment by stephan-gh** [comment]
@Kakifrucht As explained in the commit/pull request description, the changes are compatible with Spigot 1.6.2+. If compatibility with even older versions is still needed, further changes would be necessary. I'm not sure if that's still worth it, though...

**Comment by mirolm** [comment]
In main page there is statement that 1.7.10 is no longer supported, so this should be no issue.

**Comment by SupaHam** [comment]
Thank you so very much @Minecrell and the rest!

**Pull request merged**
