### PR TITLE
Fix /book command not supporting multi-word title & author

### PR DESCRIPTION
**Pull request by DebugOk**
This allows people to add spaces to the title and author of an book by using _'s instead, which works the same as /give @p stick 1 name:Custom_Name

For example, `/book title Test_Title` would normally result in the book being titled "Test_Title", however with the changes in this pull request it would "Test Title"

My Java skills are a bit rusty, but the build worked locally without any errors and running it on an server seems to work fine

P.S, This is my first pull request so I'm sorry if I did it wrong

### CODE REVIEW

**Comment by DebugOk** [comment]
It would probably be better to use Commanditemname.java's `String name = FormatUtil.formatString(user, "essentials.itemname", getFinalArg(args, 0)).trim();`, however I don't know if I can change code after I made the merge request

**Comment by mdcfe** [comment]
Thanks for opening a pull request! However, I have concerns about how this is implemented - this would probably be better achieved by joining the remaining arguments (allowing players to run `/book title A Book`), rather than requiring users to substitute in underscores.

**Comment by DebugOk** [comment]
I'm working on that right now, I just finished the build and I'm running it on my test server now to see if it works. I'm using what I found in Commanditemname.java like I mentioned before, with some changes of course

**Comment by DebugOk** [comment]
I tried it and it works, I just have to figure out how to update a pull request now :/

**Comment by DebugOk** [comment]
It seems to have updated?

**Comment by DebugOk** [comment]
It seems my change has added several permissions for coloring the title and author

**Comment by DebugOk** [comment]
@mdcfe Apologies for mentioning you here, but are these changes that I made better?

**Review by JRoy — APPROVED** [review]

**Pull request merged**
