### PR TITLE
Fix permission checks

### LINKED ISSUE #1677: Vanish and SilentJoin bug [GroupManager]
**EssentialsX version (`/essentials`):** 
EssentialsX-2.0.1 (build #545)

**Server software (`/version`):** 
PaperSpigot-1.8.8-R0.1-SNAPSHOT

**Bug description**
When an opped player connect on the server, he isn't vanished and the silent join doesnt work.
It's very annying because players can see the staff 

I precise that I have silent join and quit on true on my config

### PR DESCRIPTION
**Pull request by ElgarL**
Looks like this is an 11 year old bug.

### Information

This PR fixes #1677.

### Details

**Proposed fix:**    

**Environments tested:**    

OS: 

Java version:  

- [ ] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ x] CraftBukkit/Spigot/Paper 1.19.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**

### CODE REVIEW

**Comment by ElgarL** [comment]
Your build fails so take this fix or don't I'm not bothered. Your permission checks are broken due to an 11 year old bug.

**Comment by ElgarL** [comment]
This should also fix #4762

**Comment by JRoy** [comment]
You've made these changes through the web editor and it fails to compile making me doubt you even tested this?

The check is there because permissions plugins have historically not been supported (or incur huge performance penalties) for offline players.

The fix I would accept here would have to have this logic abstracted to our permission abstraction layers, enabling offline lookups for plugins with known support for offline players (like LuckPerms for example in the LuckPermsHandler class).

**Comment by ElgarL** [comment]
Yes I edited it via the webUI as I'm no longer a dev on Essentials and haven't been in many years. Not since 1.8 dropped.

However, the check is there because snowleo added it 11 years ago, but it is now bugged due to your changes to the permission system which have exposed the issue. These are ONLINE player permission checks which are failing and that should never happen. Essentials is literally not even checking the permission.
GroupManager also supports offline player permission checks and always has.

**Comment by JRoy** [comment]
> Yes I edited it via the webUI as I'm no longer a dev on Essentials and haven't been in many years. Not since 1.8 dropped.

Still considering it doesn't compile (because the tests fail after you did your changes) doesn't bode well for this change actually fixing the problem nor you testing it.

> However, the check is there because snowleo added it 11 years ago, but it is now bugged due to your changes to the permission system which have exposed the issue. These are ONLINE player permission checks which are failing and that should never happen.

When a user is online, there base should never be an OfflinePlayer. If what you're saying is true, this would be a bigger issue which would likely already be solved in the `dev/2.20` branch due to the usermap refactor.

**Comment by ElgarL** [comment]
Seems a couple of tabs were inserted in the edit by the lovely webUI.

**Comment by mdcfe** [comment]
FYI, the `OfflinePlayer` we check for is Essentials' stub class, not the Bukkit `OfflinePlayer` interface - if it had checked for the interface, it could never have *ever* done permissions lookups for any player. Passing the stub class would break permission plugins as it doesn't implement most of the methods expected by other plugins.

The build failed because your changes entirely broke permissions checks, causing tests to fail. This would have been obvious if you had edited and tested within an IDE. There were no tabs in your changes.

**Comment by ElgarL** [comment]
I have found and fixed this issue. It turns out it was GroupManagers fault. A very specific issue (fixed in 3.0 pre-release).
GM performs a clean-up when the player logs out. This includes removing the Permission Attachment and as it turns out GM and Essentials operate the same event at HIGHEST. GM runs first so by the time Essentials gets the event the GM attachment has already been cleared. I have delayed the clean-up until the event has finish which fixes the issue. `essentials.silentquit` now works.

**Pull request closed without merging**
