### PR TITLE
Replace items.json with ItemDbGenerator version

### PR DESCRIPTION
**Pull request by mdcfe**
In 1.13.x, the `items.json` shipped with EssentialsX was generated using the [genItemsFlat script and data](https://github.com/md678685/essx-scripts). For 1.14 and 1.15, this was merged with the output of [ItemDbGenerator](https://github.com/EssentialsX/ItemDbGenerator), but this is an awkward and unreliable process involving three separate tools.

This PR replaces the current `items.json` file with one generated *solely* by ItemDbGenerator. It's still WIP as it's not quite on par with the previous script (see EssentialsX/ItemDbGenerator#1).

### CODE REVIEW

**Comment by Lusteroth** [comment]
Some 1.15 items are missing. For example `honey_bottle` or `honeycomb`

**Comment by pop4959** [comment]
Also an idea: perhaps include ItemDbGenerator within Essentials. Especially since it's written in Java now, there's not really any reason for not including it since it's critical to the plugin. Almost the same way that the vanilla MineCraft server will generate data files when you run a main class with certain flags.

**Comment by mdcfe** [comment]
@Lusteroth Both `honeycomb` and `honey_bottle` are included in this PR.

@pop4959 While we certainly *could* do that, I don't see much point in it - generating the file on startup would just add another few seconds to the server startup. Most users won't have any need to run the generator themselves manually, and those that do can find it on GitHub.

**Comment by pop4959** [comment]
Oh no, I think you misunderstood. The point was just to include the source with Essentials and allow it to be run manually (you would run the EssentialsX jar, possibly with flags, ***not*** the server jar). This would be specifically for developers and maybe power users. I completely agree that it would be unnecessary to run this in onEnable, and that was not the intention.

Keeping it in its own repo is valid. I just wanted to suggest the option in case you hadn't thought of it.

**Comment by mdcfe** [comment]
@pop4959 I see, I wasn't sure exactly what purpose you were suggesting to start with. At present, I think it would be unnecessary bulk toninclude the generator, since the generator is open source and can't be configured to produce different outputs. In the future, it might be worth making it more configurable to let users generate their own custom `items.json` to their own specification.

**Comment by SlimeDog** [comment]
Is a build of ItemDbGenerator available? I am (power) user, not developer.

**Comment by pop4959** [comment]
@SlimeDog No but that was the purpose of my previous suggestion. Right now you should be able to use custom-items.json to define items however.

**Comment by SlimeDog** [comment]
Thanks. I am patient, as always. :)

Note that it's **custom_items.yml** (not json) in the current dev release (and previous releases).

**Comment by mdcfe** [comment]
@SlimeDog The source code can be found [here](https://github.com/EssentialsX/ItemDbGenerator). We don't publicly list builds, as there currently isn't anything you can do with a pre-compiled build except run it and generate an `items.json` file that should be identical to the version on [Jenkins](https://ci.ender.zone/job/EssentialsX-ItemDbGenerator/). However, you can find a downloadable jar on the [Jenkins Maven repo](https://ci.ender.zone/job/EssentialsX-ItemDbGenerator/lastSuccessfulBuild/maven-repository/repository/io/github/essentialsx/ItemDbGenerator/0.0.1-SNAPSHOT/ItemDbGenerator-0.0.1-SNAPSHOT.jar).

**Comment by SlimeDog** [comment]
> ... except run it and generate an `items.json` file that should be identical to the version on [Jenkins](https://ci.ender.zone/job/EssentialsX-ItemDbGenerator/). 

That's useful, since the the version of items.json included in dev EssentialsX releases does not yet contains the 1.15 items, while the one on Jenkins does. Thanks.

UPDATE: But the two files are considerably different. The Jenkins file has fewer materials, and  fewer aliases. Is it safe to use it in place of the one included in EssentialsX.jar ?

**Pull request closed without merging**
