### PR TITLE
Fix compatibility with Mohist

### PR DESCRIPTION
**Pull request by Mgazul**

### CODE REVIEW

**Review by Octol1ttle — APPROVED** [review]

**Comment by pop4959** [comment]
Why should we care about this PR? You've given no description of why this is necessary, and it seems like the hat permissions work just fine on all supported server platforms. This is something that should probably be fixed in Mohist, not Essentials.

**Comment by SSKirillSS** [comment]
This simple null-check makes hats working with mods (hybrid-type servers), cuz rn it just throws an exception and doesn't work at all

**Comment by pop4959** [comment]
> This simple null-check makes hats working with mods (hybrid-type servers), cuz rn it just throws an exception and doesn't work at all

Yes, but clearly this is a bug with the hybrid server so a proper fix should be implemented there, so that instead of *every plugin* fixing this error, it's fixed server side. CraftBukkit / Spigot / Paper do not seem to have this issue.

**Comment by SSKirillSS** [comment]
Is support almost all forge-platforms via 1 additional line of code - big trouble? 🤔

Also result of test this PR (sorry about encoding):
image

**Review by SSKirillSS — APPROVED** [review]

**Comment by pop4959** [comment]
> Is support almost all forge-platforms via 1 additional line of code - big trouble? 🤔

That's completely beside my point. The thing is that there should not be a precedent set for random server forks breaking plugins, and then expecting said plugins to clean up after them.

This fix needs to be made in Mohist. I'm closing this issue until further notice.

**Comment by JRoy** [comment]
Agree with pop here. You're implementing the Bukkit API wrong. 

Essentials runs on Bukkit servers, if it doesn't: there's a problem with your implementation.

**Comment by l1ttleO** [comment]
I agree with both sides here, however more info on why this PR should be merged needs to be provided, and you need to see if the fork creators can implement a fix on their side.

**Comment by mdcfe** [comment]
Mohist's support for modded items creates duplicated `Material` entries, when in Java enum constants should be unique. As pointed out repeatedly to Mohist users and developers, this is a Mohist bug, and we will not be including a workaround in EssentialsX.

**Comment by webserfer** [comment]
How to run a malicious code on linux and what harm can it do? Why java-developers unaware that java code is easy to check and modify, even without the source code?
Tell us honestly that you are just too lazy to make your own workaround, and someone else's workaround affects your NIH syndrome.

**Comment by Outfit8TSB** [comment]
i agree with pop.
Bukkit API is intended for Vanilla, Not (Neo)forge. If The (Neo)Forge Mods the Game, Then you have to expect errors.
However, Sponge has rebuilded API from the first, so they can use (Neo)forge.

**Pull request closed without merging**
