### PR TITLE
don't restrict length of PlayerListName

### PR DESCRIPTION
**Pull request by RoboMWM**
Apparently the 16 char limit is no longer: https://hub.spigotmc.org/jira/browse/SPIGOT-1487

### CODE REVIEW

**Comment by drtshock** [comment]
Can you post a picture of this and prove that it works as you say it does

**Comment by RoboMWM** [comment]
https://github.com/MLG-Fortress/HotFix/commit/f939e1af3dd5efcc15db62f2dabbeaa244380f44

`/hotfix robomwm thisisaverylonglistnamethingyandyeahmkay`

**Comment by drtshock** [comment]
Which version of spigot / bukkit did this get introduced? I don't want to break backward compatibility.

**Comment by RoboMWM** [comment]
I'm not entirely sure - the javadocs still aren't updated apparently.

**Comment by SupaHam** [comment]
This was introduced in 1.8 when the player list got a major overhaul, though I think Spigot only supported it a while later after they launched their 1.8 version.

**Comment by SupaHam** [comment]
This has been fixed in 8d3d2eb. You can grab the fix from [build 375](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

**Pull request closed without merging**
