### PR TITLE
Update messages_it.properties

### PR DESCRIPTION
**Pull request by leonardo-dgs**
I've updated and significantly improved the translations.

### CODE REVIEW

**Comment by drtshock** [comment]
Can anyone verify this?

**Comment by leonardo-dgs** [comment]
I don't know if there is anybody willing to test it, but I assure you I did it very carefully

**Comment by rossovitale** [comment]
I seen the translation and it's good, the original translation is quite bad for some strings

**Comment by mdcfe** [comment]
Is there a chance you could add these? They can be found in the original `messages.properties` file (#1380)
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

**Comment by leonardo-dgs** [comment]
@md678685 Done ;)

**Comment by mdcfe** [comment]
Thanks - if someone can verify that these are accurate (@Lambo599 perhaps) then these can be merged.

**Comment by rossovitale** [comment]
@md678685 The translation is fine

**Review by mdcfe — APPROVED** [review]

**Comment by SupaHam** [comment]
Thank you very much for your contribution! <3

**Pull request merged**
