### PR TITLE
Added acacia and dark oak tree types

### PR DESCRIPTION
**Pull request by montlikadani**
So I've added + two tree types to provide more help.

### CODE REVIEW

**Review by mdcfe — CHANGES_REQUESTED** [review]
I think acacia trees belong in `/tree`, but I don't know what the average size of a dark oak tree is so that can probably stay.

**Comment by montlikadani** [comment]
Maybe dark oak does not have to be in, but does acacia do without it?

**Comment by mdcfe** [comment]
Acacia trees should be moved to the `/tree` command. Dark oak trees can stay in the `/bigtree` command in this PR as you've already done.

**Comment by montlikadani** [comment]
All right, i added.

**Review by mdcfe — APPROVED** [review]

**Comment by mdcfe** [comment]
This has been merged into the 1.13 branch and is now part of experimental builds.

**Pull request merged**
