### PR TITLE
WIP - Add a basic sync framework

### LINKED ISSUE #2019: Suggestion to fix #1946: BungeeCord Plugin
Hello,
As some of you might know, I left an issue a while back, specifically #1946 (which is about the inconsistency between BungeeCord servers).  I have a suggestion that can fix it:  A BungeeCord plugin.

I'm not 100% sure about Bungee plugins, but somehow each Essentials plugin takes commands from the BungeeCord plugin.  For instance, let's suppose there's a two-minute cooldown between using `/heal`.  Assuming servers had synced health, you could go to server 1, use /heal, go to server 2, and use /heal successfully again (despite there still being an active cooldown on server 1).  

Now, let's assume that the BungeeCord plugin was properly installed and configured.  Our player does /heal.  This makes Essentials on server 1 tell the Bungee server "Player foo used /heal; cooldown disables at <timestamp>" (but with UUIDs).  Then, the Bungee server remembers that.  Once foo joins another server, the Bungee server tells that server "Enable heal cooldown for foo until <timestamp>."

This would also make Essentials banning even better, as the server would just tell the Bungee server `Bar banned Foo because 'Demo ban'`, and then the Bungee server would worry about keeping Foo banned.  There might be a config option to send the ban to all servers (although, it shouldn't be necessary, since anyone running Bungee should be using iptables or some other mechanism to keep players from directly joining a server).

Servers could also be grouped, i.e. if you had two synced survival servers, you could preserve the cooldown between servers, but not have it transfer to a creative server.

Broadcast could also be sent to all servers; `/tpa` could work between servers, etc.

Now, as I said earlier, I have no idea how Bungee plugins work, so I don't know how possible this is.

### PR DESCRIPTION
**Pull request by mdcfe**
Adds a basic sync framework, allowing plugins to register themselves as sync providers and act when certain data changes are made. This PR does not include any actual mechanisms for syncing data; rather, it enables other plugins (or EssentialsX modules) to implement them on EssentialsX's behalf.

I've chosen to do this rather than rely on events, because:
* The current EssentialsX events may not sufficiently cover data changes that we'd want to sync.
* Syncing user data happen at the UserData level for consistency, whereas events are usually fired at the command level.

Current implemented hooks (list not finalised):
- [x] Nickname
- [ ] Ignored players
  - [ ] Add player
  - [ ] Remove player
- [x] Teleport toggle
- [x] Mail
  - [x] Receiving mail
  - [x] Clearing mail
- [ ] Jail status + timeout
- [x] Mute status + timeout
- [ ] Bans
- [ ] Economy balance (not sure whether this is a good idea)
- [ ] Cooldowns
  - [ ] Teleport
  - [ ] Heal
  - [ ] General commands
  - [ ] Kits
- [ ] Confirmations
  - [ ] `/clear`
  - [ ] `/pay`
- [ ] Powertools
  - [ ] Bind powertool
  - [ ] Unbind powertool
  - [ ] Enable powertools
  - [ ] Disable powertools

This PR doesn't currently cover providing data from other servers, but in the future the system could include:
* Homes
* Warps
* Jail locations

Any criticism is very much welcome, both regarding the concept and the implementation.

A model implementation can be found at [md678685/RedisSync-EssX](https://github.com/md678685/RedisSync-EssX).

GitHub meta: fixes #2019, related #1946

### CODE REVIEW

**Comment by mdcfe** [comment]
I have no idea what's with all the format changes, VS Code seems *very* trigger happy to reformat things.

**Comment by Notarin** [comment]
It's very unfortunate that this was closed, is there a specific reason?

**Comment by mdcfe** [comment]
@Notarin The feature was never finished and I wasn't happy with the design of this API. This would be better implemented by listening to events for data changes, rather than making add-ons register a service to listen for them. I might revisit this in the future but it's not a high priority right now.

**Comment by Notarin** [comment]
@mdcfe I appreciate the insight.

**Pull request closed without merging**
