### PR TITLE
Replace mcstats with bStats

### PR DESCRIPTION
**Pull request by mdcfe**
Won't show up on the bStats website, until @drtshock or someone else signs up and creates a Bukkit plugin named "EssentialsX" on the bStats website. If you want to test, you can change `pluginName` to `"EssXmdtest"`, or any other value as desired.

### CODE REVIEW

**Comment by mdcfe** [comment]
Any progress on merging this?

**Comment by SupaHam** [comment]
Merged! Thank you very much for your contributions! <3

**Comment by mdcfe** [comment]
You're welcome! Did anyone create an account?

**Comment by SupaHam** [comment]
I created the account on bstats.

**Pull request closed without merging**
