### PR TITLE
Add role placeholder to Discord message format

### PR DESCRIPTION
**Pull request by pop4959**
Just wanted to be able to show the Discord role in-game. Turns out JDA makes this implementation very easy as the roles for the member are always returned in order from highest -> lowest.

### CODE REVIEW

**Review by JRoy — CHANGES_REQUESTED** [review]
Can you possibly add a {rolecolor} placeholder too which gets the color of their topmost role? Otherwise looks good!

**Comment by Octol1ttle** [comment]
> Can you possibly add a {rolecolor} placeholder too which gets the color of their topmost role? Otherwise looks good!

Isn't `{color}` exactly what you want?

**Comment by JRoy** [comment]
> > Can you possibly add a {rolecolor} placeholder too which gets the color of their topmost role? Otherwise looks good!
> 
> Isn't `{color}` exactly what you want?

Technically no, that gives the first role color which is not default.

**Comment by JRoy** [comment]
Realized that the only time this would be different is when the role color is white, therefore useless.

**Review by JRoy — APPROVED** [review]

**Review by JRoy — APPROVED** [review]

**Pull request merged**
