### PR TITLE
Properly detect enchantments with improper names

### PR DESCRIPTION
**Pull request by vk2gpz**
Avoid assuming registered names are in UPPER cases.

### CODE REVIEW

**Review by JRoy — CHANGES_REQUESTED** [review]
I'd rather have the `toLowerCase` check after the `toUpperCase` check as the enchantment we're after will be uppercase more cases than not

**Comment by vk2gpz** [comment]
> I'd rather have the `toLowerCase` check after the `toUpperCase` check as the enchantment we're after will be uppercase more cases than not

I've changed the order to Uppercase -> Lowercase -> original string.

**Comment by JRoy** [comment]
Please fix the compile error but otherwise looks fine

**Comment by vk2gpz** [comment]
> Please fix the compile error but otherwise looks fine

? Did 4 lines of code I've added causes the compilation error?

**Comment by JRoy** [comment]
> > Please fix the compile error but otherwise looks fine
> 
> ? Did 4 lines of code I've added causes the compilation error?

You misspelled a variable name

**Review by JRoy — APPROVED** [review]

**Comment by vk2gpz** [comment]
> > > Please fix the compile error but otherwise looks fine
> > 
> > 
> > ? Did 4 lines of code I've added causes the compilation error?
> 
> You misspelled a variable name

my bad.  (I have a condition that I cannot tell the difference in order of letters and shape of letters, so I normally have to depend on spell checker but GitHub editor does not have such...). it should be ok now.

**Pull request merged**
