### PR TITLE
Added /petprotection command and feature (+ demo)

### PR DESCRIPTION
**Pull request by Nicholamsious**
### Information

This PR closes 4522. ([Feature Suggestion](https://github.com/EssentialsX/Essentials/discussions/4522))

### Details

**Proposed feature:**  
When a player has pet protection enabled, their pets cannot be harmed by players or others' pets while they (the owner of the pets) are online.

Additions:

+1 command
+1 config option in config.yml
+1 piece of code to the `EntityDamageByEntityEvent` handler in `EssentialsEntityListener.java`.

This code does not account for harmful potions or projectiles or mobs as it stands but those can easily be implemented if this is.

`essentials.petprotection.bypass` is the permission that can be used to allow a player to harm or kill a pet that is protected by this feature (ops automatically have this already).
This feature doesn't prevent pet owners from damaging their own pets. A config option could be added to configure this.

This system works for all pets:
`Horse, Cat, ChestedHorse, Donkey, Horse, Llama, Mule, Parrot, SkeletonHorse, TraderLlama, Wolf, ZombieHorse`

New config.yml option:
```
# Add worlds to this list, if you want to automatically disable pet protection from other players there.
no-pet-protection-in-worlds:
#  - world_nether
```

(Edit: This also protects pets in God mode.)

`/petprotection [player] [on|off]`
Aliases:
`[epetprotect,petprotection,epetprotection,epets,etpp,tpp,petpro,epetpro]`

**Environments tested:**    

OS: Windows 10 Home (x64)

Java version:  16.0.2

- [x] Most recent Paper version (1.17.1, git-Paper-263)
- [x] CraftBukkit/Spigot/Paper 1.12.2
- [x] CraftBukkit 1.8.8

**Demonstration:**  

Demonstration video: https://youtu.be/0R700Vpa0NI

Test plugin jar: https://github.com/nsgwick/Essentials/releases/tag/2.19.0

Test plugin source code: https://github.com/nsgwick/Essentials

### CODE REVIEW

**Comment by oskarkk** [comment]
Great addition! I think that there should be also a command to protect your pets from yourself, as it's surely a frequent thing that one accidentally hits a pet while building or mining. Then the syntax could be `/petprotection [owner|others] [on|off] [player]` (or maybe `self` instead of `owner`). `[player]` at the end, because that's the way it is in many other Essentials commands, e.g.: `/fly [walk|fly] <speed> [player]` or `/warp <destination> [player]`

**Comment by pop4959** [comment]
Appreciate the effort here, but I think most of this is out of scope for Essentials and better suited for a separate protection plugin. Though it may still be reasonable to add a permission to allow god mode to extend to a player's owned entities. This would also fully address the problem mentioned in the linked discussion.

**Comment by mdcfe** [comment]
Same as @pop4959, this is an interesting feature but I feel that this is out of scope for EssentialsX. EssentialsX doesn't really deal with protecting players' posessions, and I feel this would be better placed in a dedicated pets plugin.

**Comment by mdcfe** [comment]
I appreciate the effort that has gone into the development of this feature, but I remain unconvinced that this is something we would want to include in EssentialsX itself. Some of these ideas could work better as a standalone plugin. 

That said, I wouldn't be completely opposed to a config option to protect pets while in god mode. I would be willing to consider a PR with a smaller scope that covers god mode alone, as suggested in #4522.

As there hasn't been any response to this PR since @pop4959 and I raised our initial concerns, I'm going to close this for the time being.

**Pull request closed without merging**
