### PR TITLE
[Feature] Added new property "socialSpyFormat"

### PR DESCRIPTION
**Pull request by Azewilous**
This allows the modification of the format in which a socialSpy message will  appear to a socialSpy enabled user.

### CODE REVIEW

**Review by mdcfe — APPROVED** [review]

**Comment by mergu** [comment]
Hi - Before this is merged at some point, is there a chance we could have the option to use a player's actual name rather than their display name? Thanks

**Comment by Azewilous** [comment]
I am not sure if I can update my current commit after it has been approved for merging. @mergu

**Comment by mdcfe** [comment]
You can edit and commit on the PR branch on your fork even after the approval.

**Comment by Azewilous** [comment]
@md678685 thnx for letting me know this.

**Comment by Azewilous** [comment]
Apologies, my commit to fix the god/vanish issue above was suppose to be a separate PR, is it possible to remove this @md678685

**Comment by mdcfe** [comment]
It would probably be best to close this PR and cherry-pick each commit into its own branch, then open a new PR for each branch.

**Pull request closed without merging**
