### PR TITLE
Fix args order in GodStatusChangeEvent

### LINKED ISSUE #1107: Wrong args in GodStatusChangeEvent
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandgod.java#L33

Reversed controller and affected args.

### PR DESCRIPTION
**Pull request by mdcfe**
Fixes #1107.

### CODE REVIEW

**Comment by drtshock** [comment]
Sure

**Review by drtshock — APPROVED** [review]

**Comment by SupaHam** [comment]
@md678685 Create PRs from your fork not on main; it leaves branches lying around.

EDIT: This issue is also happening in another place I believe. I'll edit if I find it

**Comment by mdcfe** [comment]
@SupaHam At the time, I wasn't able to make the changes locally so I used the web editor, which doesn't make it particularly easy to create PRs from branches on forks when you have write access. Thanks for deleting the leftover branch.

**Comment by SupaHam** [comment]
@md678685 For future reference, if you have an existing fork that is not sync'd with our `2.x`, delete it and refork. I make PRs with web editor sometimes too.

**Pull request merged**
