### PR TITLE
Fix regression in permission based item spawning

### LINKED ISSUE #4099: Permission based item spawn doesn't actually check permissions
### Type of bug

Other unexpected behaviour

### `/ess version` output

```
[22:30:29] [Server thread/INFO]: CONSOLE issued server command: /ess version
[22:30:29] [Server thread/INFO]: Server version: 1.16.5-R0.1-SNAPSHOT 3029-Spigot-79d53c2-e9ad7cb (MC: 1.16.5)
[22:30:29] [Server thread/INFO]: EssentialsX version: 2.19.0-dev+100-d757877
[22:30:29] [Server thread/INFO]: LuckPerms version: 5.3.16
[22:30:29] [Server thread/INFO]: EssentialsXProtect version: 2.19.0-dev+100-d757877
[22:30:29] [Server thread/INFO]: Vault is not installed. Chat and permissions may not work.
[22:30:29] [Server thread/INFO]: You are running a server with limited API functionality. EssentialsX will still work, but certain features may be disabled.
[22:30:29] [Server thread/INFO]: Fetching version information...
[22:30:29] [Craft Scheduler Thread - 20/INFO]: You're running the latest EssentialsX dev build!
```

### Server startup log

Not necessary

### EssentialsX config files

Start from auto generated config and set `permission-based-item-spawn: true`

### Error log (if applicable)

Not necessary

### Bug description

It seems that [`User.canSpawnItem()`](https://github.com/EssentialsX/Essentials/blob/2.18.2/Essentials/src/com/earth2me/essentials/User.java#L259-L274) never returns `false` when `permission-based-item-spawn` is `true` and user has only `essentials.item` permission. 

### Steps to reproduce

1. Bootstrap a new server
2. Set `permission-based-item-spawn: true`
3. Add a user permission `essentials.item`
4. Log in with the user and execute the command: `/item glass 1`

### Expected behaviour

After step 4, I expected to see 'You don't have such permission' message.

### Actual behaviour

A glass is spawned.

It seems that [`User.canSpawnItem()`](https://github.com/EssentialsX/Essentials/blob/2.18.2/Essentials/src/com/earth2me/essentials/User.java#L259-L274) never returns `false` when `permission-based-item-spawn` is `true` and user has only `essentials.item` permission. 

The [documentation](https://github.com/EssentialsX/Essentials/blob/2.18.2/Essentials/src/config.yml#L118-L133) says when you set `permissino-based-item-spawn` to `true`, `item-spawn-blacklist` will be ignored.
> ```yml
> # Set this to true if you want permission based item spawn rules.
> # Note: The blacklist above will be ignored then.
> ```

A little change can correct this behavior.

```diff
  @Override
  public Boolean canSpawnItem(final Material material) {
      if (ess.getSettings().permissionBasedItemSpawn()) {
          final String name = material.toString().toLowerCase(Locale.ENGLISH).replace("_", "");

          if (isAuthorized("essentials.itemspawn.item-all") || isAuthorized("essentials.itemspawn.item-" + name))
              return true;

          if (VersionUtil.getServerBukkitVersion().isLowerThan(VersionUtil.v1_13_0_R01)) {
              final int id = material.getId();
              if (isAuthorized("essentials.itemspawn.item-" + id)) return true;
          }

+         return false
      }
      return isAuthorized("essentials.itemspawn.exempt") || !ess.getSettings().itemSpawnBlacklist().contains(material);
  }
```

It seems that the problem started from 3b1cef918e947b3d7b351693d2c3776864b1b309. [It used to separate both two cases with `else`(`:`)](https://github.com/EssentialsX/Essentials/commit/3b1cef918e947b3d7b351693d2c3776864b1b309#diff-dcc88c5e518bcbb4cf89596a95c4dcecba39022f00da0268a306a9bb7c2f13d5).
> ```java
> ess.getSettings().permissionBasedItemSpawn() ? (!user.isAuthorized("essentials.itemspawn.item-all") && !user.isAuthorized("essentials.itemspawn.item-" + itemname)) : (!user.isAuthorized("essentials.itemspawn.exempt")
> ```

### PR DESCRIPTION
**Pull request by devxoul**
Fix #4099

I'm not sure `2.x` is the correct target branch for this PR.

### CODE REVIEW

**Comment by devxoul** [comment]
I'm not sure why build fails :(

**Comment by Octol1ttle** [comment]
> I'm not sure why build fails :(

It fails because you forgot the semicolon at the end. In the future, read the check log to see why the build fails
Also, did you test this PR to see if it actually solves the issue?

**Comment by devxoul** [comment]
@l1ttleO Thanks! I didn't see any semicolon related error message from the log. I just fixed.

I haven't tested. I just saw the old code and found something was missing in the newer code.

**Comment by devxoul** [comment]
@l1ttleO, I just tested and it works 😉

Command: `/item stone 1`

* `essentials.item`
    Screen Shot 2021-04-04 at 12 21 28 AM
* `essentials.item` and `essentials.itemspawn.item-stone`
    Screen Shot 2021-04-04 at 12 22 01 AM

**Review by JRoy — APPROVED** [review]

**Comment by JRoy** [comment]
Thanks for this fix!

**Pull request merged**
