### PR TITLE
Fixes when there are no players in the server

### PR DESCRIPTION
**Pull request by montlikadani**
When the player entered the `/kickall` command and there was no one on the server, even sent a message that all players kicked from the server.

### CODE REVIEW

**Comment by drtshock** [comment]
You'd also need to add that message to every message file. Though I'm not sure this is worth adding?

**Comment by montlikadani** [comment]
I'll add it to other message files if this PR is accepted. If so, I'll add it to the rest.

**Comment by mdcfe** [comment]
@drtshock Is this still worth implementing?

**Comment by mdcfe** [comment]
Closing as this change doesn't seem necessary.

**Comment by montlikadani** [comment]
Why?

**Comment by mdcfe** [comment]
It doesn't make much sense, because the server owner could just as easily run `/list` to see if there's anyone on the server in the first place.

**Pull request closed without merging**
