### PR TITLE
Auto equip armor from kits

### LINKED ISSUE #347: Auto equip armor from kit
There should be an option to automatically equip armor from a kit. It could there could be a separate helmet, chestplate, pants, and boots node to put in an item.

### PR DESCRIPTION
**Pull request by Oogiya**
Hey, first pr here, looking to improve!
If there's anything to improve/change/add in these changes, please let me know, I'll gladly do what I can

Closes #347

### CODE REVIEW

**Review by JRoy — CHANGES_REQUESTED** [review]
Not a fan of this PR at all. Your imports are messed up, and there is a lot of code duplication which probably will increase the expand time for kits. You shouldn't be parsing everything manually. Find some other way to implement this. I'll look into a better one later too.

**Comment by Oogiya** [comment]
> Not a fan of this PR at all. Your imports are messed up, and there is a lot of code duplication which probably will increase the expand time for kits. You shouldn't be parsing everything manually. Find some other way to implement this. I'll look into a better one later too.

I will look into it, thank you :)

**Comment by pop4959** [comment]
On top of what Roy mentioned, I'd suggest finding a way to place the items into the appropriate armor slots at the point where it is filling the player's inventory. This would probably result in the least complicated code.

In addition, elaborating on the "messed up imports" - Essentials PRs should ideally have a clean diff in places that are not directly related to what you are trying to change. So, as an example, you should not be moving around or merging imports, adding/removing random lines, or changing other parts of the code that are unrelated to your change (you can do this in another PR). Clean diffs make the code more maintainable, should we need to refer back to your code in the future.

**Comment by Oogiya** [comment]
I rearranged the imports as they were before the first commit (Had to untick some auto import organize option in eclipse)
Also changed the code to be a bit more appealing and more "dynamic" so it doesn't parse manually according to JRoy's request.

Also made it so that if auto equip is false or the player currently has a specific equipment already equipped, the equipment from kit would be added to the inventory along with other kit items

Would love you feedback <3

**Comment by Oogiya** [comment]
Hey sorry for bumping but could I get a review? 
Would really appreciate!~ <3

**Review by JRoy — CHANGES_REQUESTED** [review]
Your current implementation creates new sections in the kit format rather than detecting armor items from the existing item loop.

My thoughts on how you should do this is on line 194, you check if the current itemstack is an armor piece, if it is, check if its respective slot is empty, if it is, set the slot with the armor piece, otherwise add the armor piece to the itemList list.

**Comment by Oogiya** [comment]
> 
> 
> Your current implementation creates new sections in the kit format rather than detecting armor items from the existing item loop.
> 
> My thoughts on how you should do this is on line 194, you check if the current itemstack is an armor piece, if it is, check if its respective slot is empty, if it is, set the slot with the armor piece, otherwise add the armor piece to the itemList list.

Sorry for the delayed reply, thanks for reviewing!~
I'll take my time and fix it asap.
How is my second approach compared to the first?

**Comment by JRoy** [comment]
Worse because it requires a new section, please see me requested changes

**Comment by Oogiya** [comment]
> 
> 
> Worse because it requires a new section, please see me requested changes

AH! I get what you're saying. 
I made a new section because that's whats been requested,
They mentioned that you'll equip the armor that has been stated in the section in the following format
helmet:
chestplate:
..

That's why I implemented it like that.. But since I've already added a boolean to configure wether it equips possible kit items, your thinking is way better imo. I'll commit an improvment tomorrow.
Thanks for helping out, really appreciated~

**Pull request closed without merging**
