### PR TITLE
Rewrote messaging structure for more abstractness.

### PR DESCRIPTION
**Pull request by SupaHam**
This commit adds a new boolean-configurable feature called last-message-reply-recipient, defaults to true, which states whether to use the new messaging functionality or not.
This commit deprecates Console#getCommandSender(Server) and provides Console#getInstance()#getCommandSender() for future usability.

This PR was created to prevent the horrors of replying to the wrong person.

Here's a formatted scenario of the new last-message-reply-recipient feature:

> **SupaHam: /msg Kakifrucht Hi**
> _SupaHam -> Kakifrucht: Hi_
> **Kakifrucht: /r Hi**
> _Kakifrucht -> SupaHam: Hi_
> **EvilOlaf: /msg Kakifrucht Hi**
> _EvilOlaf -> Kakifrucht: Hi_
> **Kakifrucht: /r Hi back to you!**
> _Kakifrucht -> SupaHam: Hi back to you!_

This PR removes the IReplyTo interface and replaces it with IMessageRecipient, which is extended by SimpleMessageRecipient. The removal of IReplyTo could lead to some breakages in essentials extensions, but there was no direct API support for it either, nor is it a big feature that could have been extended.

### CODE REVIEW

**Comment by Kakifrucht** [comment]
Oh wow, nice effort, is it not merged to discuss further?

**Comment by vemacs** [comment]
Default should be old behavior imo

**Comment by SupaHam** [comment]
I felt the need to enable this by default for new users of essentials. With it being disabled by default, I feel it won't have as much exposure. But, on the other hands users updating their versions would need to manually define the property. So, I've disabled the new functionality it by default.

**Comment by vemacs** [comment]
I think you should use false in getBoolean, but put it to true in the config. That way existing users won't have issues, while new ones will have the new behavior.

**Comment by SupaHam** [comment]
Oops, thanks.

**Comment by drtshock** [comment]
Looks good. Feel free to merge unless anyone else has any issues.

**Comment by vemacs** [comment]
Let me squash these commits

**Pull request closed without merging**
