### PR TITLE
Fix /kill and /suicide on latest Spigot/Paper

### PR DESCRIPTION
**Pull request by JRoy**
ahh

### CODE REVIEW

**Comment by resi23** [comment]
THX
👍works with the latest paper 1.20.4 build 423

**Comment by molor** [comment]
(if someone else is also tired of waiting for this PR to be merged, the issue has already been fixed in the latest Spigot/Paper)

**Comment by pop4959** [comment]
> (if someone else is also tired of waiting for this PR to be merged, the issue has already been fixed in the latest Spigot/Paper)

Thanks for mentioning here. Also mentioned in #5672 which as been closed. The purpose of this PR is no longer to fix the issue but to future proof (as it has been re-added for now, but planned for removal again later).

Definitely just update your server if you are still experiencing this.

**Comment by JRoy** [comment]
Manually merged in 0cd47639c28dfb0b3013c8b4fe7edd7e2a90e25a

**Pull request closed without merging**
