### PR TITLE
Converting ping-pong to player ping

### PR DESCRIPTION
**Pull request by montlikadani**
So, I think the ping-pong would be better and more useful to be able to watch the ping. If that does not exist, this ping command is unnecessary.

_This code is not properly prepared._

### CODE REVIEW

**Review by mdcfe — CHANGES_REQUESTED** [review]
`/ping` has existed for years as it is. I don't see why we should change this when other plugins can already override and replace this command.

**Comment by montlikadani** [comment]
Yes, I know they overwrite it. But this /ping command to _Essentials_ would be superfluous, because I think it's just the place.

**Comment by mdcfe** [comment]
@montlikadani I assume you meant the opposite of [*superfluous*](https://en.wiktionary.org/wiki/superfluous#Adjective).

The ping command is not unnecessary as it is. It allows server owners and users to echo (optionally formatted) messages to players, as well as to test for perceptible delays in command handling and tick rate, and there's nothing stopping server owners replacing the command should they want to.

We also do not access NMS directly in command classes.

**Comment by montlikadani** [comment]
All right, I just recommended this.
This invalid.

**Pull request closed without merging**
