### PR TITLE
Add {PLAYER} placeholder with uppercase in kits (again)

### PR DESCRIPTION
**Pull request by montlikadani**
[Request](https://github.com/EssentialsX/Essentials/pull/2929#issuecomment-606383782)

This should fixes https://github.com/EssentialsX/Essentials/pull/2929#issuecomment-599171020

### CODE REVIEW

**Comment by triagonal** [comment]
While this PR fixes the exception, this still does not solve the original issue. Like I mentioned before, KeywordReplacer replaces the `{PLAYER}` placeholder before the `String#replace` statements have a chance to do anything.

https://github.com/EssentialsX/Essentials/blob/c007700c590c8a96a40f4e7222a74f917e966d36/Essentials/src/com/earth2me/essentials/Kit.java#L148-L170

KeywordReplacer parses the text on line 151, and replaces the following placeholders:
https://github.com/EssentialsX/Essentials/blob/c007700c590c8a96a40f4e7222a74f917e966d36/Essentials/src/com/earth2me/essentials/textreader/KeywordReplacer.java#L120-L280

So, `{PLAYER}` is already replaced with the player's displayname by the time the `String#replace` statement has a chance to execute on line 168.

**Comment by montlikadani** [comment]
So we don't need the {player} and {PLAYER} placeholders either, because it's already implemented. This way it can be removed. I'm right?

**Comment by triagonal** [comment]
As KeywordReplacer currently only replaces placeholders that have capital letters, removing the line that replaces lowercase `{player}` would break existing setups that use this placeholder. 

Additionally, the `{PLAYER}` placeholder replaces the text with the player's displayname, while the `{player}` placeholder actually replaces the text with the player's username, which makes things more complicated.

**Comment by Ichbinjoe** [comment]
I'm going to trust @triagonal's review on this, obviously has more context to what went wrong last time.

**Review by triagonal — COMMENTED** [review]
By changing the match string to be lowercase you did solve the issue with `{player}`, but at the same time you also broke every other placeholder that KeywordReplacer provides. 

Either way, a change that modifies the behaviour of `{player}` or `{PLAYER}` will break multiple existing setups that rely on these two placeholders returning different values, and should only be done after careful consideration of when, how, and if we want to break these expectations.

**Pull request closed without merging**
