### PR TITLE
Teleport delay perms

### PR DESCRIPTION
**Pull request by Agazed**
With this PR you can assign players different teleport delay permissions just like multiple homes. This is useful for donors or staff who shouldn't have to wait as long to teleport. If you look around the internet you'll find a lot of people want this, or already thought it was implemented. I don't really contribute to big projects because I find them confusing, unless I really need something done, but it would be nice to not have to merge upstream every time I want to update.

With these changes you should depreciate getTeleportDelay() in favor of getTeleportDelay(IUser user). But I didn't want to make any radical changes.

### CODE REVIEW

**Comment by drtshock** [comment]
Please include a description whenever you make a PR. You should be explaining what you're implementing and why (whose needs are you meeting) and then talk about how you implemented it and why you did it the way you did.

**Comment by Agazed** [comment]
Done. The code is pretty short and self explanatory I think; which is why I figured I didn't need a description.

**Review by mdcfe — DISMISSED** [review]
Could you fix the indentation to consistently use spaces not tabs?

Also, it might be worth noting that if the user has multiple delays, the first in the list in the config will take priority (assuming that is the behaviour of iterating over the list in YAML).

Otherwise, this looks good.

**Comment by Agazed** [comment]
sry bout those commits my git fucked up

**Review by mdcfe — COMMENTED** [review]
I haven't build and tested this, but as far as I can tell this looks good to merge once tested.

**Comment by iLemon** [comment]
Was this ever completed?

**Comment by Ichbinjoe** [comment]
MD, you are actually wrong about the priority - the last will take priority over the first entries (and the default).

I think the behavior should be instead the following:

+ If the user has one teleport cooldown permission node, use the cooldown present with that node
+ If the user has multiple cooldown permission nodes, use the lowest cooldown value out of the nodes
+ If the user has no permission nodes, use the default teleport cooldown

**Comment by Ichbinjoe** [comment]
Closing as this PR has been inactive for some time now.

**Pull request closed without merging**
