### PR TITLE
Fixed wrong order of arguments (#2604)

### PR DESCRIPTION
**Pull request by ghost**
This PR is meant to fix issue #2604, however, fixing it would break other plugins that are built with this behavior expected.

### CODE REVIEW

**Review by triagonal — DISMISSED** [review]

**Review by mdcfe — CHANGES_REQUESTED** [review]
This will break all existing plugins that use the API and that assume these methods are incorrect.

**Comment by triagonal** [comment]
So how should we rectify the issue? Just add a comment in the event class?

**Comment by mdcfe** [comment]
@triagonal I think a note in Javadocs would be the best option - it would make it clear the event is incorrect.

This can be properly fixed if/when we decide to make sweeping changes to the API.

**Comment by triagonal** [comment]
Sounds good.

@scpketer - apologies for suggesting that it was such a simple fix. I overlooked the fact that it would be a breaking change. We could use this PR to add the note in the event's Javadocs instead.

**Comment by ghost** [comment]
I wonder why nobody else but me noticed that bug - I couldn't even suppose that `getAffected()` will ever return `null` (which I supposed to be possible with `getController()`.)

**Pull request closed without merging**
