### PR TITLE
Move kits to kits.yml

### PR DESCRIPTION
**Pull request by drtshock**
We will now use a separate kits.yml file.
Any kits that were defined in the config.yml will be migrated over to the kits.yml file automatically on startup.
Settings for createkitpastebin and first join kit were moved to this file as well.

Please let me know what your thoughts are on the implementation. I ran a test locally on the copying of kits multiple times and had no issues.

```[23:37:08 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[23:37:08 INFO]: [Essentials] Converting tools2
[23:37:08 INFO]: [Essentials] Converting tools2.delay
[23:37:08 INFO]: [Essentials] Converting tools2.items
[23:37:08 INFO]: [Essentials] Converting dtools2
[23:37:08 INFO]: [Essentials] Converting dtools2.delay
[23:37:08 INFO]: [Essentials] Converting dtools2.items
[23:37:08 INFO]: [Essentials] Converting notch2
[23:37:08 INFO]: [Essentials] Converting notch2.delay
[23:37:08 INFO]: [Essentials] Converting notch2.items
[23:37:08 INFO]: [Essentials] Converting color2
[23:37:08 INFO]: [Essentials] Converting color2.delay
[23:37:08 INFO]: [Essentials] Converting color2.items
[23:37:08 INFO]: [Essentials] Converting firework2
[23:37:08 INFO]: [Essentials] Converting firework2.delay
[23:37:08 INFO]: [Essentials] Converting firework2.items

### CODE REVIEW

**Comment by SupaHam** [comment]
Sorry, I do not approve of this current structure.

The idea of `kits.yml` is great, but a couple of changes need to be made to this implementation:
1. Consider keeping all configuration in `config.yml` as per convention (the file does exist to hold all values)
2. Add a `kits` root property that will be a 'list' of kit objects. e.g.
```yaml
kits:
  foo:
    items: 2
```
Following these two points will enable us to utilise the yaml saving and not messing up config comments. Albeit, the primary rationale behind it should be the conventions.

One more thing, if i'm not mistaken `"Attempting to convert old kits in `config.yml` to new kits.yml"` will print on every start up. If so, could we do a check to see if `kits` exists in `config.yml`, if so, proceed?

**Review by mdcfe — CHANGES_REQUESTED** [review]
Tried to review earlier to no avail, but the unfinished comment I wrote earlier and lost exactly reflects the changes SupaHam requested - keeping all kits under a `kits` key and config options staying in `config.yml` as comments will be lost when creating kits.

Also, something to bear in mind is @khobbits's suggestion that `pastebin-createkit` could now default to false, as it would lead to people not noticing the new feature.

Another thing to consider is to use `EssentialsUpgrade` as this appears to be the most relevant place for the config migration code to go, and allows us to track migrations easily through `upgrades-done.yml`.

**Comment by drtshock** [comment]
All issues addressed. Please let me know if you guys have any further suggestions :)

**Review by LaxWasHere — APPROVED** [review]

**Comment by mdcfe** [comment]
👍

**Comment by khobbits** [comment]
https://github.com/EssentialsX/Essentials/issues/1775

**Comment by DoNotSpamPls** [comment]
delete branch?

**Pull request merged**
