### PR TITLE
Turn off god mode on login if player doesn't have the permission.

### PR DESCRIPTION
**Pull request by ghost**
Implements #1445

### CODE REVIEW

**Review by LaxWasHere — APPROVED** [review]

**Comment by SupaHam** [comment]
Thank you sir.

**Comment by TNTUP** [comment]
Will re-fork EssX again to revert this commit because previous EssX was fine without this commit, as I god some friends and I don't want to give the permission but I allow them to keep it until I decide^^

**Comment by mdcfe** [comment]
@TNTUP Feel free to PR a config toggle for this behaviour if you're unhappy with it.

**Comment by TNTUP** [comment]
@md678685 If I know how to code java I could do that but I don't know how to^^ Something like "ess.getconfig" thing? I can try for my own fork but considering myself as a noob I don't think it would be worth PRing it :/

**Pull request merged**
