### PR TITLE
Made a new danish translation for Essentials X

### PR DESCRIPTION
**Pull request by falcken**
I just fixed some of the gramma mistakes, and translated some of the messages from scratch.

### CODE REVIEW

**Comment by drtshock** [comment]
Thanks for the help. Will get this merged :)

**Comment by drtshock** [comment]
Nevermind, our resident dutch person says no :(

**Comment by falcken** [comment]
Ehh why does he say no? I'm a Danish citizen, I'm sure there is no mistakes.

**Comment by falcken** [comment]
I will make a new pull request, with some "obviouse" Danish errors, i just spotted in my translation, hope thats ok ;)

**Pull request closed without merging**
