### PR TITLE
Random teleportation improvements

### PR DESCRIPTION
**Pull request by pop4959**
WIP improvements for Essentials' new random teleportation feature.

### CODE REVIEW

**Comment by CaszGamerMD** [comment]
_i reloaded config and saw nothing for settings for the /tpr
will there be the ability to set the min/max distance for the tpr?_

nvm i see its a separate file.

command cooldown?
add a message showing coords in chat?

**Comment by pop4959** [comment]
@CaszGamerMD Yeah it's a different file like how warps/homes/etc have their own files for saving data. Command cooldown can be set via config.yml still.

**Comment by ghost** [comment]
Suggestions:
 - Clicking on button with a block set in configuration behind it makes you random teleport
 - /rtp default alias

**Comment by pop4959** [comment]
> Suggestions:
> 
> * Clicking on button with a block set in configuration behind it makes you random teleport
> * /rtp default alias

@Helios19932 Random teleport sign is something that might be considered (which is along the line of Essentials' other sign features). Alias will not be added by default, as not to conflict with other random teleport plugins. You can set the alias yourself in commands.yml if you need it.

**Comment by SuspiciousLookingOwl** [comment]
Any plan on merging this soon? I have a private server for me and my friends and really want to add per world `/tpr` features, can't use other random teleport plugin because they are not compatible with essential's `/back`.

**Comment by pop4959** [comment]
I've been busy lately with other things, however I am still planning to get this finished before the Essentials 2.19 milestone. Ideally well before, so that it can be reviewed / tested thoroughly. I'll let you know when it's ready for testing.

**Comment by iShowee** [comment]
Ey, im interested in testing per-world rtp

**Pull request closed without merging**
