### PR TITLE
Allows console to retrieve player's home list

### LINKED ISSUE #2584: Allow home list from console
### Feature request

**Feature description**
I just want to be able to list all player homes from console!

**How the feature is useful**
I know we already have the in-game command `/<command> [player:]<name>` and using `/<command> [player:]` + TAB i can list all player homes, but not from console.

### PR DESCRIPTION
**Pull request by werogg**
Solves Issue #2584

### CODE REVIEW

**Review by triagonal — COMMENTED** [review]
The second `run` method should be moved directly under the first one to conform to existing code style.

**Comment by pop4959** [comment]
So this works slightly differently from the in-game version from the looks of it. Seems reasonable given that the console isn't going to be teleporting to any of these homes or anything, however.

**Comment by mdcfe** [comment]
Since the in-game version accepts `/home <username>:`, it might be worth checking for the colon and removing it (and throwing an error if they try to put a home name after the colon as if they're teleporting).

**Comment by pop4959** [comment]
This seems pretty simple, I'd just change the thing md mentioned to help avoid confusion.

**Comment by darbyjack** [comment]
Closing due to inactivity.

**Pull request closed without merging**
