### PR TITLE
Updated "createKitSuccess="

### PR DESCRIPTION
**Pull request by Remski01**
They have the old one, its now in the "kits.yml" not in "config.yml"

### CODE REVIEW

**Comment by Remski01** [comment]
Uhm, the "messages_hu.properties" have `config.yml-be.`, do i need to still change it to just `kits.yml` or we need to format it different there?

**Comment by Remski01** [comment]
**Do NOT update** the one in "messages_nl.properties ", that one is taken care of in https://github.com/EssentialsX/Essentials/pull/2129

**And i finish the others tomorrow.**

**Comment by montlikadani** [comment]
@DutchUser 
Write config.yml as kits.yml as it has been.

**Comment by mdcfe** [comment]
@DutchUser `messages_hu.properties` should be changed to `kits.yml` along with the others.

Thanks for the PR - I'll merge when you're ready.

**Comment by Remski01** [comment]
This one `messages_vi.properties` is missing 14 lines. (496, other's have 610)

Can maybe because it seem to have the `488` build.

[
X-Generator: crowdin.net
version: 488
Single quotes have to be doubled: 
Translations start here
by: BaoKunVN (Kun)
]

Not sure if it should be in PR, but i don't know an way to add those whitout schrewing the current one. Anybody else know a way? (A faster way then looking for everyone single `<thing>=` )

**Comment by DutchUser** [comment]
Also not sure how this should be formatted 

`createKitSuccess=\u00a76\u521b\u5efa\u793c\u5305: \u00a7f{0}\n\u00a76\u4f7f\u7528\u6b21\u6570: \u00a7f{1}\n\u00a76\u4fe1\u606f: \u00a7f{2}\n\u00a76\u590d\u5236\u4e0b\u9762\u7684\u4fe1\u606f\u5230config\u91cc\u9762.`

anybody know how it should be formatted?

**Comment by Remski01** [comment]
Alright, every locale should be updated and correctly now, we only need to wait on `messages_vi.properties` to have it updated in **every** locale,

**Comment by Remski01** [comment]
`If you've got Python installed and the EssentialsX repo cloned, you can run the Python script from here: https://gist.github.com/md678685/a5e435a79d3431040d91ea9d4b84026d`
**Source:** MD (not that one)

Hmm, i dont use Python. Going need my pc for that. Whats going be over 8 days. (After vacation)

ps: I ported it to here to not forget it.

**Comment by mdcfe** [comment]
[This link](https://gitlab.com/md678685/essx-scripts/-/jobs/artifacts/master/raw/out/locale.report.md?job=run_locale) will point to the most recent output from that script.

**Review by mdcfe — DISMISSED** [review]
I'm happy to merge this if the PR is ready.

**Comment by Remski01** [comment]
"Going add the other later today, 

* invalidItemFlagMeta
* noJailsDefined
* openingDisposal
* socialSpyMsgFormat
* socialSpyMutedPrefix
* tempbanJoin
* whoisUuid"

I thoughed i could the last few later today or tomorrow, however, its going need to wait till monday to finish what is started.

**Comment by mdcfe** [comment]
@DutchUser In a separate PR, or as part of this one?

**Comment by Remski01** [comment]
Ow, LOL. Seem that i forget the main one, haha.

**Review by mdcfe — APPROVED** [review]

**Comment by mdcfe** [comment]
@DutchUser Is this ready to be merged?

**Comment by Remski01** [comment]
Yea, its ready.

**Comment by mdcfe** [comment]
Thanks for all the translations fixes!

**Comment by Remski01** [comment]
NoProblemo.

**Pull request merged**
