### PR TITLE
Update messages_zh.properties

### PR DESCRIPTION
**Pull request by NyanMeow**
Add new message of Chinese

### CODE REVIEW

**Comment by mdcfe** [comment]
Is there a chance you could add these? They can be found in the original `messages.properties` file (see #1380).
* recentlyForeverAlone
* muteNotifyFor
* payConfirmToggleOn
* payConfirmToggleOff
* sellBulkPermission
* sellHandPermission
* timeSetWorldPermission
* msgDisabled
* msgDisabledFor
* msgEnabled
* msgEnabledFor
* msgIgnore
* minimumPayAmount

**Comment by NyanMeow** [comment]
Change done√

**Comment by mdcfe** [comment]
If anyone else can verify that these changes are accurate then I think this can be merged.

**Comment by CBM1014** [comment]
翻译还不错_(:зゝ∠)_
很棒
Good translation.
Great！

**Comment by SupaHam** [comment]
Thank you very much. I've merged your contributions to `2.x` branch with the conflict resolution I made above.

**Pull request merged**
