### PR TITLE
Add /discord command to display invite code

### PR DESCRIPTION
**Pull request by JRoy**
Att #4598

```yml
# The Discord invite URL that will be shown when a player when using the /discord command or in other areas.
discord-url: "https://discord.gg/invite-code"
```

### CODE REVIEW

**Review by pop4959 — APPROVED** [review]

**Comment by DaliborTrampota** [comment]
@JRoy hello, thank you for adding this feature for me, but it would be great if we could customize the message. Right now its "Join our discord server at {invite-url}" Little kids in our country barely know any english so I'd like to localize it. Its not just for me, i bet many other users find it useful and the config entry could look something like this: discord-command-message: "Join our discord server at {invite}!" and the invite would get replaced with the clickable invite link. Let me know what you think about this, and what are the chances of this being added. Thank you for your time!

**Comment by JRoy** [comment]
> @JRoy hello, thank you for adding this feature for me, but it would be great if we could customize the message. Right now its "Join our discord server at {invite-url}" Little kids in our country barely know any english so I'd like to localize it. Its not just for me, i bet many other users find it useful and the config entry could look something like this: discord-command-message: "Join our discord server at {invite}!" and the invite would get replaced with the clickable invite link. Let me know what you think about this, and what are the chances of this being added. Thank you for your time!

You can customize the message by making a custom locale file: https://essentialsx.net/wiki/Locale.html#customising-messages

The message you want to change is
```properties
discordCommandLink=\u00a76Join our Discord server at \u00a7c{0}\u00a76!
```

**Comment by DaliborTrampota** [comment]
Oh didn't know about that. Thank you!

**Comment by DaliborTrampota** [comment]
> > @JRoy hello, thank you for adding this feature for me, but it would be great if we could customize the message. Right now its "Join our discord server at {invite-url}" Little kids in our country barely know any english so I'd like to localize it. Its not just for me, i bet many other users find it useful and the config entry could look something like this: discord-command-message: "Join our discord server at {invite}!" and the invite would get replaced with the clickable invite link. Let me know what you think about this, and what are the chances of this being added. Thank you for your time!
> 
> You can customize the message by making a custom locale file: https://essentialsx.net/wiki/Locale.html#customising-messages
> 
> The message you want to change is
> 
> ```ini
> discordCommandLink=\u00a76Join our Discord server at \u00a7c{0}\u00a76!
> ```

Hey so I'm trying to edit it but first issue: there is no messages file and second I cant find the up-to-date messages file on github. All I could find are those 7 years old ones https://github.com/essentials/Essentials/tree/2.x/Essentials/src :( can you please link me and perhaps add a download/redirect link to this site so other users can find those messages files easily https://essentialsx.net/wiki/Locale.html#Supported-languages

Again thank you.

**Comment by JRoy** [comment]
> > > @JRoy hello, thank you for adding this feature for me, but it would be great if we could customize the message. Right now its "Join our discord server at {invite-url}" Little kids in our country barely know any english so I'd like to localize it. Its not just for me, i bet many other users find it useful and the config entry could look something like this: discord-command-message: "Join our discord server at {invite}!" and the invite would get replaced with the clickable invite link. Let me know what you think about this, and what are the chances of this being added. Thank you for your time!
> > 
> > 
> > You can customize the message by making a custom locale file: [essentialsx.net/wiki/Locale.html#customising-messages](https://essentialsx.net/wiki/Locale.html#customising-messages)
> > The message you want to change is
> > ```ini
> > discordCommandLink=\u00a76Join our Discord server at \u00a7c{0}\u00a76!
> > ```
> 
> Hey so I'm trying to edit it but first issue: there is no messages file and second I cant find the up-to-date messages file on github. All I could find are those 7 years old ones [essentials/Essentials@`2.x`/Essentials/src](https://github.com/essentials/Essentials/tree/2.x/Essentials/src?rgh-link-date=2021-12-01T20%3A44%3A51Z) :( can you please link me and perhaps add a download/redirect link to this site so other users can find those messages files easily [essentialsx.net/wiki/Locale.html#Supported-languages](https://essentialsx.net/wiki/Locale.html#Supported-languages)
> 
> Again thank you.

The latest would be here https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/messages.properties

**Pull request merged**
